// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Hcs.Model
{
    public partial class ContractImportRequestParty
    {
        public long uniqueId { get; set; }
        public Guid TransactionGUID { get; set; }
        [StringLength(32)]
        public string objectId { get; set; }
        [Key]
        public Guid TransportGUID { get; set; }
        [Required]
        [StringLength(60)]
        public string FirstName { get; set; }
        [Required]
        [StringLength(60)]
        public string Surname { get; set; }
        [StringLength(60)]
        public string Patronymic { get; set; }
        [StringLength(1)]
        public string Sex { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateOfBirth { get; set; }
        [StringLength(20)]
        public string DocumentTypeCode { get; set; }
        public Guid? DocumentTypeGUID { get; set; }
        [StringLength(45)]
        public string Series { get; set; }
        [StringLength(45)]
        public string Number { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? IssueDate { get; set; }
        [StringLength(11)]
        public string SNILS { get; set; }
        [StringLength(255)]
        public string PlaceBirth { get; set; }

        [ForeignKey(nameof(TransportGUID))]
        [InverseProperty(nameof(ContractImportRequest.ContractImportRequestParty))]
        public virtual ContractImportRequest TransportGU { get; set; }
    }
}