// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Hcs.Model
{
    public partial class DeviceImportResult
    {
        public DeviceImportResult()
        {
            DeviceImportResultErrors = new HashSet<DeviceImportResultError>();
        }

        public long uniqueId { get; set; }
        public Guid TransactionGUID { get; set; }
        [StringLength(32)]
        public string objectId { get; set; }
        [Key]
        public Guid TransportGUID { get; set; }
        public Guid? DeviceGUID { get; set; }
        public Guid? DeviceVersionGUID { get; set; }
        [StringLength(128)]
        public string DeviceUniqueNumber { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdateDate { get; set; }

        [InverseProperty(nameof(DeviceImportResultError.DeviceImportTransportGU))]
        public virtual ICollection<DeviceImportResultError> DeviceImportResultErrors { get; set; }
    }
}