// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Hcs.Model
{
    public partial class HouseImportResultLivingRoom
    {
        public HouseImportResultLivingRoom()
        {
            HouseImportResultLivingRoomErrors = new HashSet<HouseImportResultLivingRoomError>();
        }

        public long uniqueId { get; set; }
        public Guid TransactionGUID { get; set; }
        [StringLength(32)]
        public string objectId { get; set; }
        [Key]
        public Guid TransportGUID { get; set; }
        public Guid HouseImportTransportGUID { get; set; }
        public Guid? LivingRoomGUID { get; set; }
        [StringLength(31)]
        public string LivingRoomUniqueNumber { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdateDate { get; set; }

        [ForeignKey(nameof(HouseImportTransportGUID))]
        [InverseProperty(nameof(HouseImportResult.HouseImportResultLivingRooms))]
        public virtual HouseImportResult HouseImportTransportGU { get; set; }
        [InverseProperty(nameof(HouseImportResultLivingRoomError.HouseImportLivingRoomTransportGU))]
        public virtual ICollection<HouseImportResultLivingRoomError> HouseImportResultLivingRoomErrors { get; set; }
    }
}