// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Hcs.Model
{
    public partial class HouseImportRequest
    {
        public HouseImportRequest()
        {
            HouseImportRequestBlocks = new HashSet<HouseImportRequestBlock>();
            HouseImportRequestEntrances = new HashSet<HouseImportRequestEntrance>();
            HouseImportRequestLivingRooms = new HashSet<HouseImportRequestLivingRoom>();
            HouseImportRequestPremises = new HashSet<HouseImportRequestPremise>();
        }

        public long uniqueId { get; set; }
        public Guid TransactionGUID { get; set; }
        [StringLength(32)]
        public string objectId { get; set; }
        [Key]
        public Guid TransportGUID { get; set; }
        public Guid? HouseGUID { get; set; }
        public byte houseType { get; set; }
        public Guid FIASHouseGuid { get; set; }
        [StringLength(11)]
        public string OKTMO { get; set; }
        [StringLength(20)]
        public string OlsonTZCode { get; set; }
        public Guid? OlsonTZGUID { get; set; }
        [StringLength(255)]
        public string CadastralNumber { get; set; }
        public bool? InheritMissingValues { get; set; }
        public bool? MultipleHousesAddress { get; set; }

        [InverseProperty(nameof(HouseImportRequestBlock.HouseImportTransportGU))]
        public virtual ICollection<HouseImportRequestBlock> HouseImportRequestBlocks { get; set; }
        [InverseProperty(nameof(HouseImportRequestEntrance.HouseImportTransportGU))]
        public virtual ICollection<HouseImportRequestEntrance> HouseImportRequestEntrances { get; set; }
        [InverseProperty(nameof(HouseImportRequestLivingRoom.HouseImportTransportGU))]
        public virtual ICollection<HouseImportRequestLivingRoom> HouseImportRequestLivingRooms { get; set; }
        [InverseProperty(nameof(HouseImportRequestPremise.HouseImportTransportGU))]
        public virtual ICollection<HouseImportRequestPremise> HouseImportRequestPremises { get; set; }
    }
}