// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Hcs.Model
{
    public partial class HouseExportResult
    {
        public HouseExportResult()
        {
            HouseExportResultBlocks = new HashSet<HouseExportResultBlock>();
            HouseExportResultEntrances = new HashSet<HouseExportResultEntrance>();
            HouseExportResultLivingRooms = new HashSet<HouseExportResultLivingRoom>();
            HouseExportResultPremises = new HashSet<HouseExportResultPremise>();
        }

        public long uniqueId { get; set; }
        public Guid TransactionGUID { get; set; }
        [Key]
        public Guid TransportGUID { get; set; }
        public Guid? HouseGUID { get; set; }
        [Required]
        [StringLength(31)]
        public string HouseUniqueNumber { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime ModificationDate { get; set; }
        public byte houseType { get; set; }
        public Guid FIASHouseGuid { get; set; }
        [StringLength(11)]
        public string OKTMO { get; set; }
        [StringLength(20)]
        public string OlsonTZCode { get; set; }
        public Guid? OlsonTZGUID { get; set; }
        [StringLength(255)]
        public string CadastralNumber { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? TerminationDate { get; set; }
        [StringLength(20)]
        public string AnnulmentReasonCode { get; set; }
        public Guid? AnnulmentReasonGUID { get; set; }
        [StringLength(1024)]
        public string AnnulmentInfo { get; set; }
        public bool? MultipleHousesAddress { get; set; }

        [InverseProperty(nameof(HouseExportResultBlock.HouseExportTransportGU))]
        public virtual ICollection<HouseExportResultBlock> HouseExportResultBlocks { get; set; }
        [InverseProperty(nameof(HouseExportResultEntrance.HouseExportTransportGU))]
        public virtual ICollection<HouseExportResultEntrance> HouseExportResultEntrances { get; set; }
        [InverseProperty(nameof(HouseExportResultLivingRoom.HouseExportTransportGU))]
        public virtual ICollection<HouseExportResultLivingRoom> HouseExportResultLivingRooms { get; set; }
        [InverseProperty(nameof(HouseExportResultPremise.HouseExportTransportGU))]
        public virtual ICollection<HouseExportResultPremise> HouseExportResultPremises { get; set; }
    }
}