// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Hcs.Model
{
    public partial class OrganizationExportResultRole
    {
        public long uniqueId { get; set; }
        public Guid TransactionGUID { get; set; }
        [Key]
        public Guid TransportGUID { get; set; }
        public Guid OrganizationExportTransportGUID { get; set; }
        [Required]
        [StringLength(20)]
        public string OrganizationRoleCode { get; set; }
        public Guid OrganizationRoleGUID { get; set; }

        [ForeignKey(nameof(OrganizationExportTransportGUID))]
        [InverseProperty(nameof(OrganizationExportResult.OrganizationExportResultRoles))]
        public virtual OrganizationExportResult OrganizationExportTransportGU { get; set; }
    }
}