 
CREATE TABLE "public"."AccountExportRequest" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "TransportGUID" uuid NOT NULL , 
   "FIASHouseGuid" uuid NOT NULL 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE AccountExportRequest OWNER to "BillBerry";

 
CREATE TABLE "public"."AccountExportResult" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "TransportGUID" uuid NOT NULL , 
   "AccountGUID" uuid NOT NULL , 
   "AccountNumber" character varying(30) COLLATE pg_catalog."default" , 
   "UnifiedAccountNumber" character varying(10) COLLATE pg_catalog."default" NOT NULL , 
   "ServiceID" character varying(13) COLLATE pg_catalog."default" , 
   "IsRSOAccount" bool NOT NULL , 
   "CreationDate" date , 
   "LivingPersonsNumber" smallint , 
   "TotalSquare" numeric(20,10) , 
   "ResidentialSquare" numeric(20,10) , 
   "HeatedArea" numeric(20,10) , 
   "AccountCloseReasonCode" character varying(20) COLLATE pg_catalog."default" , 
   "AccountCloseReasonGUID" uuid , 
   "CloseDate" date , 
   "CloseDescription" character varying(250) COLLATE pg_catalog."default" , 
   "IsRenter" bool , 
   "IsAccountsDivided" bool , 
   "OrgVersionGUID" uuid 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE AccountExportResult OWNER to "BillBerry";

 
CREATE TABLE "public"."AccountExportResultPercentPremise" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "TransportGUID" uuid NOT NULL , 
   "AccountExportTransportGUID" uuid NOT NULL , 
   "FIASHouseGuid" uuid , 
   "PremisesGUID" uuid , 
   "LivingRoomGUID" uuid , 
   "SharePercent" numeric(20,10) 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE AccountExportResultPercentPremise OWNER to "BillBerry";

 
CREATE TABLE "public"."AccountImportRequest" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid NOT NULL , 
   "AccountGUID" uuid , 
   "AccountNumber" character varying(30) COLLATE pg_catalog."default" NOT NULL , 
   "IsRSOAccount" bool NOT NULL , 
   "CreationDate" date , 
   "LivingPersonsNumber" smallint , 
   "TotalSquare" numeric(20,10) , 
   "ResidentialSquare" numeric(20,10) , 
   "HeatedArea" numeric(20,10) , 
   "AccountCloseReasonCode" character varying(20) COLLATE pg_catalog."default" , 
   "AccountCloseReasonGUID" uuid , 
   "CloseDate" date , 
   "CloseDescription" character varying(250) COLLATE pg_catalog."default" , 
   "IsRenter" bool , 
   "IsAccountsDivided" bool , 
   "OrgVersionGUID" uuid 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE AccountImportRequest OWNER to "BillBerry";

 
CREATE TABLE "public"."AccountImportRequestPayer" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid NOT NULL , 
   "Surname" character varying(256) COLLATE pg_catalog."default" NOT NULL , 
   "FirstName" character varying(256) COLLATE pg_catalog."default" NOT NULL , 
   "Patronymic" character varying(256) COLLATE pg_catalog."default" , 
   "Sex" character varying(1) COLLATE pg_catalog."default" , 
   "DateOfBirth" date , 
   "SNILS" character varying(11) COLLATE pg_catalog."default" , 
   "DocumentTypeCode" character varying(20) COLLATE pg_catalog."default" , 
   "DocumentTypeGUID" uuid , 
   "Series" character varying(45) COLLATE pg_catalog."default" , 
   "Number" character varying(45) COLLATE pg_catalog."default" , 
   "IssueDate" date 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE AccountImportRequestPayer OWNER to "BillBerry";

 
CREATE TABLE "public"."AccountImportRequestPercentPremise" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid NOT NULL , 
   "AccountImportTransportGUID" uuid NOT NULL , 
   "FIASHouseGuid" uuid , 
   "PremisesGUID" uuid , 
   "LivingRoomGUID" uuid , 
   "SharePercent" numeric(20,10) 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE AccountImportRequestPercentPremise OWNER to "BillBerry";

 
CREATE TABLE "public"."AccountImportRequestReason" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid NOT NULL , 
   "AccountImportTransportGUID" uuid NOT NULL , 
   "ContractGUID" uuid NOT NULL 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE AccountImportRequestReason OWNER to "BillBerry";

 
CREATE TABLE "public"."AccountImportResult" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid NOT NULL , 
   "AccountGUID" uuid , 
   "UnifiedAccountNumber" character varying(10) COLLATE pg_catalog."default" , 
   "ServiceID" character varying(13) COLLATE pg_catalog."default" , 
   "UpdateDate" date 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE AccountImportResult OWNER to "BillBerry";

 
CREATE TABLE "public"."AccountImportResultError" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid NOT NULL , 
   "AccountImportTransportGUID" uuid NOT NULL , 
   "ErrorCode" character varying(32) COLLATE pg_catalog."default" NOT NULL , 
   "ErrorDescription" text COLLATE pg_catalog."default" NOT NULL 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE AccountImportResultError OWNER to "BillBerry";

 
CREATE TABLE "public"."AckImportCancellationRequest" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid NOT NULL , 
   "OrderGUID" uuid NOT NULL , 
   "PaymentDocumentID" character varying(18) COLLATE pg_catalog."default" 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE AckImportCancellationRequest OWNER to "BillBerry";

 
CREATE TABLE "public"."AckImportRequest" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid NOT NULL , 
   "OrderGUID" uuid NOT NULL , 
   "PaymentDocumentID" character varying(18) COLLATE pg_catalog."default" , 
   "AckImpossible" bool NOT NULL , 
   "AckImpossibleReason" character varying(210) COLLATE pg_catalog."default" , 
   "AmountRub" numeric(20,10) , 
   "HousingServiceCode" character varying(20) COLLATE pg_catalog."default" , 
   "HousingServiceGUID" uuid , 
   "MainMunicipalServiceCode" character varying(20) COLLATE pg_catalog."default" , 
   "MainMunicipalServiceGUID" uuid , 
   "AdditionalServiceCode" character varying(20) COLLATE pg_catalog."default" , 
   "AdditionalServiceGUID" uuid , 
   "PenaltyAndCourtCostCode" character varying(20) COLLATE pg_catalog."default" , 
   "PenaltyAndCourtCostGUID" uuid , 
   "MunicipalServiceCode" character varying(20) COLLATE pg_catalog."default" , 
   "MunicipalServiceGUID" uuid , 
   "BankBIK" character varying(9) COLLATE pg_catalog."default" , 
   "OperatingAccountNumber" character varying(20) COLLATE pg_catalog."default" , 
   "DelayPeriodMonth" unknown field , 
   "DelayPeriodYear" smallint , 
   "CapitalRepairPeriodMonth" unknown field , 
   "CapitalRepairPeriodYear" smallint 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE AckImportRequest OWNER to "BillBerry";

 
CREATE TABLE "public"."AckImportResult" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid NOT NULL , 
   "AckGUID" uuid , 
   "UniqueNumber" character varying(128) COLLATE pg_catalog."default" , 
   "UpdateDate" date 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE AckImportResult OWNER to "BillBerry";

 
CREATE TABLE "public"."AckImportResultError" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid NOT NULL , 
   "AckImportTransportGUID" uuid NOT NULL , 
   "ErrorCode" character varying(32) COLLATE pg_catalog."default" NOT NULL , 
   "ErrorDescription" text COLLATE pg_catalog."default" NOT NULL 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE AckImportResultError OWNER to "BillBerry";

 
CREATE TABLE "public"."AttachmentPostRequest" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid NOT NULL , 
   "Name" character varying(1024) COLLATE pg_catalog."default" NOT NULL , 
   "Description" character varying(500) COLLATE pg_catalog."default" NOT NULL , 
   "AttachmentBody" text COLLATE pg_catalog."default" NOT NULL , 
   "numCopies" smallint NOT NULL 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE AttachmentPostRequest OWNER to "BillBerry";

 
CREATE TABLE "public"."AttachmentPostResult" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid NOT NULL , 
   "AttachmentHASH" character varying(1024) COLLATE pg_catalog."default" NOT NULL , 
   "ErrorCode" character varying(32) COLLATE pg_catalog."default" , 
   "ErrorDescription" character varying(128) COLLATE pg_catalog."default" 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE AttachmentPostResult OWNER to "BillBerry";

 
CREATE TABLE "public"."AttachmentPostResultCopy" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid NOT NULL , 
   "AttachmentPostTransportGUID" uuid NOT NULL , 
   "AttachmentGUID" uuid NOT NULL 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE AttachmentPostResultCopy OWNER to "BillBerry";

 
CREATE TABLE "public"."ContractImportRequest" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid NOT NULL , 
   "ContractGUID" uuid , 
   "ComptetionDate" date , 
   "ShowStartDate" smallint , 
   "ShowStartDateNextMonth" bool , 
   "ShowEndDate" smallint , 
   "ShowEndDateNextMonth" bool , 
   "ContractConclusionReasonCode" character varying(20) COLLATE pg_catalog."default" , 
   "ContractConclusionReasonGUID" uuid , 
   "ContractingParty" unknown field NOT NULL , 
   "CountingResource" character varying(1) COLLATE pg_catalog."default" , 
   "IsContract" bool NOT NULL , 
   "ContractNumber" character varying(30) COLLATE pg_catalog."default" , 
   "SigningDate" date , 
   "EffectiveDate" date , 
   "BillingDate" smallint , 
   "PaymentDate" smallint , 
   "ProvidingInformationDate" smallint , 
   "BillingDateType" character varying(1) COLLATE pg_catalog."default" , 
   "PaymentDateType" character varying(1) COLLATE pg_catalog."default" , 
   "ProvidingInformationDateType" character varying(1) COLLATE pg_catalog."default" , 
   "IsPlannedVolume" bool NOT NULL , 
   "SpecifyingQualityIndicators" character varying(1) COLLATE pg_catalog."default" NOT NULL , 
   "MeteringDeviceInformation" bool , 
   "VolumeDepends" bool , 
   "OneTimePayment" bool , 
   "IndefiniteTerm" bool , 
   "AutomaticRollOverOneYear" bool , 
   "AccrualProcedure" character varying(1) COLLATE pg_catalog."default" , 
   "IndicationsAnyDay" bool , 
   "PlannedVolumeType" character varying(1) COLLATE pg_catalog."default" , 
   "OrgGUID" uuid 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE ContractImportRequest OWNER to "BillBerry";

 
CREATE TABLE "public"."ContractImportRequestAttachment" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid NOT NULL , 
   "ContractImportTransportGUID" uuid NOT NULL , 
   "Name" character varying(1024) COLLATE pg_catalog."default" NOT NULL , 
   "Description" character varying(500) COLLATE pg_catalog."default" NOT NULL , 
   "AttachmentBody" text COLLATE pg_catalog."default" , 
   "AttachmentHASH" text COLLATE pg_catalog."default" , 
   "AttachmentGUID" uuid 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE ContractImportRequestAttachment OWNER to "BillBerry";

 
CREATE TABLE "public"."ContractImportRequestObjectAddress" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid NOT NULL , 
   "ContractImportTransportGUID" uuid NOT NULL , 
   "houseType" unknown field , 
   "FIASHouseGuid" uuid NOT NULL , 
   "ApartmentNumber" character varying(255) COLLATE pg_catalog."default" , 
   "RoomNumber" character varying(255) COLLATE pg_catalog."default" 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE ContractImportRequestObjectAddress OWNER to "BillBerry";

 
CREATE TABLE "public"."ContractImportRequestObjectServiceResource" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid NOT NULL , 
   "ContractImportObjectAddressTransportGUID" uuid NOT NULL , 
   "ContractImportSubjectTransportGUID" uuid NOT NULL , 
   "StartSupplyDate" date NOT NULL , 
   "EndSupplyDate" date , 
   "OpenOrNot" character varying(32) COLLATE pg_catalog."default" , 
   "CentralizedOrNot" character varying(32) COLLATE pg_catalog."default" 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE ContractImportRequestObjectServiceResource OWNER to "BillBerry";

 
CREATE TABLE "public"."ContractImportRequestParty" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid NOT NULL , 
   "FirstName" character varying(60) COLLATE pg_catalog."default" NOT NULL , 
   "Surname" character varying(60) COLLATE pg_catalog."default" NOT NULL , 
   "Patronymic" character varying(60) COLLATE pg_catalog."default" , 
   "Sex" character varying(1) COLLATE pg_catalog."default" , 
   "DateOfBirth" date , 
   "DocumentTypeCode" character varying(20) COLLATE pg_catalog."default" , 
   "DocumentTypeGUID" uuid , 
   "Series" character varying(45) COLLATE pg_catalog."default" , 
   "Number" character varying(45) COLLATE pg_catalog."default" , 
   "IssueDate" date , 
   "SNILS" character varying(11) COLLATE pg_catalog."default" , 
   "PlaceBirth" character varying(255) COLLATE pg_catalog."default" 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE ContractImportRequestParty OWNER to "BillBerry";

 
CREATE TABLE "public"."ContractImportRequestSubject" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid NOT NULL , 
   "ContractImportTransportGUID" uuid NOT NULL , 
   "MunicipalServiceCode" character varying(20) COLLATE pg_catalog."default" NOT NULL , 
   "MunicipalServiceGUID" uuid NOT NULL , 
   "ChargeableResourceCode" character varying(20) COLLATE pg_catalog."default" NOT NULL , 
   "ChargeableResourceGUID" uuid NOT NULL , 
   "StartSupplyDate" date NOT NULL , 
   "EndSupplyDate" date , 
   "Volume" numeric(20,10) , 
   "Unit" character varying(4) COLLATE pg_catalog."default" , 
   "FeedingMode" character varying(250) COLLATE pg_catalog."default" 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE ContractImportRequestSubject OWNER to "BillBerry";

 
CREATE TABLE "public"."ContractImportRequestSubjectQualityIndicator" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid NOT NULL , 
   "ContractImportSubjectTransportGUID" uuid NOT NULL , 
   "ContractImportObjectAddressTransportGUID" uuid , 
   "QualityIndicatorCode" character varying(20) COLLATE pg_catalog."default" , 
   "QualityIndicatorGUID" uuid , 
   "Number" numeric(20,10) , 
   "StartRange" numeric(20,10) , 
   "EndRange" numeric(20,10) , 
   "OKEI" character varying(4) COLLATE pg_catalog."default" , 
   "Correspond" bool , 
   "IndicatorName" character varying(1000) COLLATE pg_catalog."default" 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE ContractImportRequestSubjectQualityIndicator OWNER to "BillBerry";

 
CREATE TABLE "public"."ContractImportResult" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid NOT NULL , 
   "ContractGUID" uuid , 
   "ContractVersionGUID" uuid , 
   "UpdateDate" date 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE ContractImportResult OWNER to "BillBerry";

 
CREATE TABLE "public"."ContractImportResultError" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid NOT NULL , 
   "ContractImportTransportGUID" uuid NOT NULL , 
   "ContractImportObjectAddressTransportGUID" uuid , 
   "ContractImportSubjectTransportGUID" uuid , 
   "ErrorCode" character varying(32) COLLATE pg_catalog."default" NOT NULL , 
   "ErrorDescription" text COLLATE pg_catalog."default" NOT NULL 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE ContractImportResultError OWNER to "BillBerry";

 
CREATE TABLE "public"."DeviceExportRequest" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "TransportGUID" uuid NOT NULL , 
   "DeviceGUID" uuid , 
   "FIASHouseGuid" uuid 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE DeviceExportRequest OWNER to "BillBerry";

 
CREATE TABLE "public"."DeviceExportResult" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "TransportGUID" uuid NOT NULL , 
   "DeviceGUID" uuid NOT NULL , 
   "DeviceVersionGUID" uuid NOT NULL , 
   "StatusRootDoc" character varying(32) COLLATE pg_catalog."default" NOT NULL , 
   "deviceType" unknown field NOT NULL , 
   "individualDeviceType" unknown field , 
   "DeviceNumber" character varying(50) COLLATE pg_catalog."default" NOT NULL , 
   "DeviceStamp" character varying(100) COLLATE pg_catalog."default" , 
   "DeviceModel" character varying(100) COLLATE pg_catalog."default" , 
   "InstallationDate" date , 
   "CommissioningDate" date , 
   "RemoteMeteringMode" bool NOT NULL , 
   "RemoteMeteringInfo" character varying(2000) COLLATE pg_catalog."default" , 
   "FirstVerificationDate" date , 
   "DeviceCalibrationIntervalCode" character varying(20) COLLATE pg_catalog."default" , 
   "DeviceCalibrationIntervalGUID" uuid , 
   "FactorySealDate" date , 
   "TemperatureSensor" bool NOT NULL , 
   "PressureSensor" bool NOT NULL , 
   "ConsumedVolume" bool 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE DeviceExportResult OWNER to "BillBerry";

 
CREATE TABLE "public"."DeviceExportResultAccount" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "TransportGUID" uuid NOT NULL , 
   "DeviceExportTransportGUID" uuid NOT NULL , 
   "AccountGUID" uuid NOT NULL 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE DeviceExportResultAccount OWNER to "BillBerry";

 
CREATE TABLE "public"."DeviceExportResultAddress" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "TransportGUID" uuid NOT NULL , 
   "DeviceExportTransportGUID" uuid NOT NULL , 
   "AddressGUID" uuid NOT NULL 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE DeviceExportResultAddress OWNER to "BillBerry";

 
CREATE TABLE "public"."DeviceImportArchiveRequest" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid NOT NULL , 
   "DeviceVersionGUID" uuid NOT NULL , 
   "DeviceArchivingReasonCode" character varying(20) COLLATE pg_catalog."default" NOT NULL , 
   "DeviceArchivingReasonGUID" uuid NOT NULL 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE DeviceImportArchiveRequest OWNER to "BillBerry";

 
CREATE TABLE "public"."DeviceImportReplaceRequest" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid NOT NULL , 
   "DeviceVersionGUID" uuid NOT NULL , 
   "VerificationDate" date NOT NULL , 
   "PlannedVerification" bool , 
   "DeviceFaultReasonCode" character varying(20) COLLATE pg_catalog."default" , 
   "DeviceFaultReasonGUID" uuid , 
   "ReplacingDeviceVersionGUID" uuid NOT NULL 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE DeviceImportReplaceRequest OWNER to "BillBerry";

 
CREATE TABLE "public"."DeviceImportReplaceRequestValue" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid NOT NULL , 
   "DeviceImportReplaceTransportGUID" uuid NOT NULL , 
   "MunicipalResourceCode" character varying(20) COLLATE pg_catalog."default" NOT NULL , 
   "MunicipalResourceGUID" uuid NOT NULL , 
   "ValueT1" numeric(20,10) NOT NULL , 
   "ValueT2" numeric(20,10) , 
   "ValueT3" numeric(20,10) 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE DeviceImportReplaceRequestValue OWNER to "BillBerry";

 
CREATE TABLE "public"."DeviceImportRequest" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid NOT NULL , 
   "DeviceVersionGUID" uuid , 
   "deviceType" unknown field NOT NULL , 
   "individualDeviceType" unknown field , 
   "DeviceNumber" character varying(50) COLLATE pg_catalog."default" NOT NULL , 
   "DeviceStamp" character varying(100) COLLATE pg_catalog."default" NOT NULL , 
   "DeviceModel" character varying(100) COLLATE pg_catalog."default" NOT NULL , 
   "InstallationDate" date , 
   "CommissioningDate" date , 
   "RemoteMeteringMode" bool NOT NULL , 
   "RemoteMeteringInfo" character varying(2000) COLLATE pg_catalog."default" , 
   "FirstVerificationDate" date , 
   "DeviceCalibrationIntervalCode" character varying(20) COLLATE pg_catalog."default" , 
   "DeviceCalibrationIntervalGUID" uuid , 
   "FactorySealDate" date NOT NULL , 
   "TemperatureSensor" bool NOT NULL , 
   "TemperatureSensingElementInfo" character varying(2000) COLLATE pg_catalog."default" , 
   "PressureSensor" bool NOT NULL , 
   "PressureSensingElementInfo" character varying(2000) COLLATE pg_catalog."default" , 
   "InstallationPlace" character varying(1) COLLATE pg_catalog."default" , 
   "ConsumedVolume" bool 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE DeviceImportRequest OWNER to "BillBerry";

 
CREATE TABLE "public"."DeviceImportRequestAccount" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid NOT NULL , 
   "DeviceImportTransportGUID" uuid NOT NULL , 
   "AccountGUID" uuid NOT NULL 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE DeviceImportRequestAccount OWNER to "BillBerry";

 
CREATE TABLE "public"."DeviceImportRequestAddress" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid NOT NULL , 
   "DeviceImportTransportGUID" uuid NOT NULL , 
   "AddressGUID" uuid NOT NULL 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE DeviceImportRequestAddress OWNER to "BillBerry";

 
CREATE TABLE "public"."DeviceImportRequestLinkedDevice" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid NOT NULL , 
   "DeviceImportTransportGUID" uuid NOT NULL , 
   "DeviceVersionGUID" uuid NOT NULL 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE DeviceImportRequestLinkedDevice OWNER to "BillBerry";

 
CREATE TABLE "public"."DeviceImportRequestValue" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid NOT NULL , 
   "DeviceImportTransportGUID" uuid NOT NULL , 
   "MunicipalResourceCode" character varying(20) COLLATE pg_catalog."default" NOT NULL , 
   "MunicipalResourceGUID" uuid NOT NULL , 
   "ValueT1" numeric(20,10) NOT NULL , 
   "ValueT2" numeric(20,10) , 
   "ValueT3" numeric(20,10) , 
   "TransformationRatio" numeric(20,10) 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE DeviceImportRequestValue OWNER to "BillBerry";

 
CREATE TABLE "public"."DeviceImportResult" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid NOT NULL , 
   "DeviceGUID" uuid , 
   "DeviceVersionGUID" uuid , 
   "DeviceUniqueNumber" character varying(128) COLLATE pg_catalog."default" , 
   "UpdateDate" date 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE DeviceImportResult OWNER to "BillBerry";

 
CREATE TABLE "public"."DeviceImportResultError" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid NOT NULL , 
   "DeviceImportTransportGUID" uuid NOT NULL , 
   "ErrorCode" character varying(32) COLLATE pg_catalog."default" NOT NULL , 
   "ErrorDescription" text COLLATE pg_catalog."default" NOT NULL 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE DeviceImportResultError OWNER to "BillBerry";

 
CREATE TABLE "public"."DeviceValueExportRequest" 
( 
   "TransportGUID" uuid NOT NULL , 
   "FIASHouseGuid" uuid NOT NULL , 
   "CommissioningDateFrom" date , 
   "CommissioningDateTo" date , 
   "SearchArchived" bool , 
   "ArchiveDateFrom" date , 
   "ArchiveDateTo" date , 
   "InputDateFrom" date , 
   "InputDateTo" date , 
   "ExcludePersonAsDataSource" bool , 
   "ExcludeCurrentOrgAsDataSource" bool , 
   "ExcludeOtherOrgAsDataSource" bool , 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE DeviceValueExportRequest OWNER to "BillBerry";

 
CREATE TABLE "public"."DeviceValueExportRequestDevice" 
( 
   "TransportGUID" uuid NOT NULL , 
   "DeviceValueExportTransportGUID" uuid NOT NULL , 
   "DeviceGUID" uuid NOT NULL , 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE DeviceValueExportRequestDevice OWNER to "BillBerry";

 
CREATE TABLE "public"."DeviceValueExportRequestDeviceType" 
( 
   "TransportGUID" uuid NOT NULL , 
   "DeviceValueExportTransportGUID" uuid NOT NULL , 
   "DeviceTypeCode" character varying(20) COLLATE pg_catalog."default" NOT NULL , 
   "DeviceTypeGUID" uuid NOT NULL , 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE DeviceValueExportRequestDeviceType OWNER to "BillBerry";

 
CREATE TABLE "public"."DeviceValueExportRequestMunicipalResource" 
( 
   "TransportGUID" uuid NOT NULL , 
   "DeviceValueExportTransportGUID" uuid NOT NULL , 
   "MunicipalResourceCode" character varying(20) COLLATE pg_catalog."default" NOT NULL , 
   "MunicipalResourceGUID" uuid NOT NULL , 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE DeviceValueExportRequestMunicipalResource OWNER to "BillBerry";

 
CREATE TABLE "public"."DeviceValueExportResult" 
( 
   "TransportGUID" uuid NOT NULL , 
   "DeviceGUID" uuid NOT NULL , 
   "deviceShowValueType" unknown field NOT NULL , 
   "DateValue" date , 
   "MunicipalResourceCode" character varying(20) COLLATE pg_catalog."default" NOT NULL , 
   "MunicipalResourceGUID" uuid NOT NULL , 
   "ValueT1" numeric(20,10) NOT NULL , 
   "ValueT2" numeric(20,10) , 
   "ValueT3" numeric(20,10) , 
   "EnterIntoSystem" date NOT NULL , 
   "OrgPPAGUID" uuid , 
   "ReadingsSource" character varying(1024) COLLATE pg_catalog."default" , 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE DeviceValueExportResult OWNER to "BillBerry";

 
CREATE TABLE "public"."DeviceValueImportRequest" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid NOT NULL , 
   "DeviceVersionGUID" uuid NOT NULL , 
   "deviceShowValueType" unknown field NOT NULL , 
   "DateValue" date NOT NULL , 
   "MunicipalResourceCode" character varying(20) COLLATE pg_catalog."default" NOT NULL , 
   "MunicipalResourceGUID" uuid NOT NULL , 
   "ValueT1" numeric(20,10) NOT NULL , 
   "ValueT2" numeric(20,10) , 
   "ValueT3" numeric(20,10) 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE DeviceValueImportRequest OWNER to "BillBerry";

 
CREATE TABLE "public"."DeviceValueImportResult" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid NOT NULL , 
   "DeviceValueGUID" uuid , 
   "UpdateDate" date 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE DeviceValueImportResult OWNER to "BillBerry";

 
CREATE TABLE "public"."DeviceValueImportResultError" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid NOT NULL , 
   "DeviceValueImportTransportGUID" uuid NOT NULL , 
   "ErrorCode" character varying(32) COLLATE pg_catalog."default" NOT NULL , 
   "ErrorDescription" text COLLATE pg_catalog."default" NOT NULL 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE DeviceValueImportResultError OWNER to "BillBerry";

 
CREATE TABLE "public"."HouseExportRequest" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "TransportGUID" uuid NOT NULL , 
   "FIASHouseGuid" uuid NOT NULL 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE HouseExportRequest OWNER to "BillBerry";

 
CREATE TABLE "public"."HouseExportResult" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "TransportGUID" uuid NOT NULL , 
   "HouseGUID" uuid , 
   "HouseUniqueNumber" character varying(31) COLLATE pg_catalog."default" NOT NULL , 
   "ModificationDate" date NOT NULL , 
   "houseType" unknown field NOT NULL , 
   "FIASHouseGuid" uuid NOT NULL , 
   "OKTMO" character varying(11) COLLATE pg_catalog."default" , 
   "OlsonTZCode" character varying(20) COLLATE pg_catalog."default" , 
   "OlsonTZGUID" uuid , 
   "CadastralNumber" character varying(255) COLLATE pg_catalog."default" , 
   "TerminationDate" date , 
   "AnnulmentReasonCode" character varying(20) COLLATE pg_catalog."default" , 
   "AnnulmentReasonGUID" uuid , 
   "AnnulmentInfo" character varying(1024) COLLATE pg_catalog."default" , 
   "MultipleHousesAddress" bool 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE HouseExportResult OWNER to "BillBerry";

 
CREATE TABLE "public"."HouseExportResultBlock" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "TransportGUID" uuid NOT NULL , 
   "HouseExportTransportGUID" uuid NOT NULL , 
   "BlockGUID" uuid NOT NULL , 
   "BlockUniqueNumber" character varying(31) COLLATE pg_catalog."default" NOT NULL , 
   "ModificationDate" date NOT NULL , 
   "blockType" unknown field NOT NULL , 
   "BlockNum" character varying(255) COLLATE pg_catalog."default" NOT NULL , 
   "TotalArea" numeric(20,10) , 
   "ResidentPremiseTypeCode" character varying(20) COLLATE pg_catalog."default" , 
   "ResidentPremiseTypeGUID" uuid , 
   "CadastralNumber" character varying(255) COLLATE pg_catalog."default" , 
   "TerminationDate" date , 
   "AnnulmentReasonCode" character varying(20) COLLATE pg_catalog."default" , 
   "AnnulmentReasonGUID" uuid , 
   "AnnulmentInfo" character varying(1024) COLLATE pg_catalog."default" , 
   "InformationConfirmed" bool 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE HouseExportResultBlock OWNER to "BillBerry";

 
CREATE TABLE "public"."HouseExportResultEntrance" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "TransportGUID" uuid NOT NULL , 
   "HouseExportTransportGUID" uuid NOT NULL , 
   "EntranceGUID" uuid NOT NULL , 
   "ModificationDate" date NOT NULL , 
   "EntranceNum" character varying(255) COLLATE pg_catalog."default" , 
   "TerminationDate" date , 
   "AnnulmentReasonCode" character varying(20) COLLATE pg_catalog."default" , 
   "AnnulmentReasonGUID" uuid , 
   "AnnulmentInfo" character varying(1024) COLLATE pg_catalog."default" , 
   "InformationConfirmed" bool 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE HouseExportResultEntrance OWNER to "BillBerry";

 
CREATE TABLE "public"."HouseExportResultLivingRoom" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "TransportGUID" uuid NOT NULL , 
   "HouseExportTransportGUID" uuid NOT NULL , 
   "HouseExportPremiseTransportGUID" uuid , 
   "HouseExportBlockTransportGUID" uuid , 
   "LivingRoomGUID" uuid NOT NULL , 
   "LivingRoomUniqueNumber" character varying(31) COLLATE pg_catalog."default" NOT NULL , 
   "ModificationDate" date NOT NULL , 
   "RoomNumber" character varying(255) COLLATE pg_catalog."default" , 
   "Square" numeric(20,10) , 
   "CadastralNumber" character varying(255) COLLATE pg_catalog."default" , 
   "TerminationDate" date , 
   "AnnulmentReasonCode" character varying(20) COLLATE pg_catalog."default" , 
   "AnnulmentReasonGUID" uuid , 
   "AnnulmentInfo" character varying(1024) COLLATE pg_catalog."default" , 
   "InformationConfirmed" bool 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE HouseExportResultLivingRoom OWNER to "BillBerry";

 
CREATE TABLE "public"."HouseExportResultPremise" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "TransportGUID" uuid NOT NULL , 
   "HouseExportTransportGUID" uuid NOT NULL , 
   "HouseExportEntranceTransportGUID" uuid , 
   "PremisesGUID" uuid NOT NULL , 
   "PremisesUniqueNumber" character varying(31) COLLATE pg_catalog."default" NOT NULL , 
   "ModificationDate" date NOT NULL , 
   "premiseType" unknown field NOT NULL , 
   "PremisesNum" character varying(255) COLLATE pg_catalog."default" , 
   "TotalArea" numeric(20,10) , 
   "ResidentPremiseTypeCode" character varying(20) COLLATE pg_catalog."default" , 
   "ResidentPremiseTypeGUID" uuid , 
   "CadastralNumber" character varying(255) COLLATE pg_catalog."default" , 
   "TerminationDate" date , 
   "AnnulmentReasonCode" character varying(20) COLLATE pg_catalog."default" , 
   "AnnulmentReasonGUID" uuid , 
   "AnnulmentInfo" character varying(1024) COLLATE pg_catalog."default" , 
   "InformationConfirmed" bool 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE HouseExportResultPremise OWNER to "BillBerry";

 
CREATE TABLE "public"."HouseImportRequest" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid NOT NULL , 
   "HouseGUID" uuid , 
   "houseType" unknown field NOT NULL , 
   "FIASHouseGuid" uuid NOT NULL , 
   "OKTMO" character varying(11) COLLATE pg_catalog."default" , 
   "OlsonTZCode" character varying(20) COLLATE pg_catalog."default" , 
   "OlsonTZGUID" uuid , 
   "CadastralNumber" character varying(255) COLLATE pg_catalog."default" , 
   "InheritMissingValues" bool , 
   "MultipleHousesAddress" bool 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE HouseImportRequest OWNER to "BillBerry";

 
CREATE TABLE "public"."HouseImportRequestBlock" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid NOT NULL , 
   "HouseImportTransportGUID" uuid NOT NULL , 
   "BlockGUID" uuid , 
   "blockType" unknown field NOT NULL , 
   "BlockNum" character varying(255) COLLATE pg_catalog."default" NOT NULL , 
   "TotalArea" numeric(20,10) , 
   "ResidentPremiseTypeCode" character varying(20) COLLATE pg_catalog."default" , 
   "ResidentPremiseTypeGUID" uuid , 
   "CadastralNumber" character varying(255) COLLATE pg_catalog."default" , 
   "AnnulmentReasonCode" character varying(20) COLLATE pg_catalog."default" , 
   "AnnulmentReasonGUID" uuid , 
   "AnnulmentInfo" character varying(1024) COLLATE pg_catalog."default" 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE HouseImportRequestBlock OWNER to "BillBerry";

 
CREATE TABLE "public"."HouseImportRequestEntrance" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid NOT NULL , 
   "HouseImportTransportGUID" uuid NOT NULL , 
   "EntranceGUID" uuid , 
   "EntranceNum" character varying(255) COLLATE pg_catalog."default" NOT NULL , 
   "AnnulmentReasonCode" character varying(20) COLLATE pg_catalog."default" , 
   "AnnulmentReasonGUID" uuid , 
   "AnnulmentInfo" character varying(1024) COLLATE pg_catalog."default" 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE HouseImportRequestEntrance OWNER to "BillBerry";

 
CREATE TABLE "public"."HouseImportRequestLivingRoom" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid NOT NULL , 
   "HouseImportTransportGUID" uuid NOT NULL , 
   "HouseImportPremiseTransportGUID" uuid , 
   "HouseImportBlockTransportGUID" uuid , 
   "LivingRoomGUID" uuid , 
   "RoomNumber" character varying(255) COLLATE pg_catalog."default" NOT NULL , 
   "Square" numeric(20,10) , 
   "CadastralNumber" character varying(255) COLLATE pg_catalog."default" , 
   "AnnulmentReasonCode" character varying(20) COLLATE pg_catalog."default" , 
   "AnnulmentReasonGUID" uuid , 
   "AnnulmentInfo" character varying(1024) COLLATE pg_catalog."default" 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE HouseImportRequestLivingRoom OWNER to "BillBerry";

 
CREATE TABLE "public"."HouseImportRequestPremise" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid NOT NULL , 
   "HouseImportTransportGUID" uuid NOT NULL , 
   "HouseImportEntranceTransportGUID" uuid , 
   "PremisesGUID" uuid , 
   "premiseType" unknown field NOT NULL , 
   "PremisesNum" character varying(255) COLLATE pg_catalog."default" NOT NULL , 
   "TotalArea" numeric(20,10) , 
   "ResidentPremiseTypeCode" character varying(20) COLLATE pg_catalog."default" , 
   "ResidentPremiseTypeGUID" uuid , 
   "CadastralNumber" character varying(255) COLLATE pg_catalog."default" , 
   "AnnulmentReasonCode" character varying(20) COLLATE pg_catalog."default" , 
   "AnnulmentReasonGUID" uuid , 
   "AnnulmentInfo" character varying(1024) COLLATE pg_catalog."default" 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE HouseImportRequestPremise OWNER to "BillBerry";

 
CREATE TABLE "public"."HouseImportResult" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid NOT NULL , 
   "HouseGUID" uuid , 
   "HouseUniqueNumber" character varying(31) COLLATE pg_catalog."default" , 
   "UpdateDate" date 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE HouseImportResult OWNER to "BillBerry";

 
CREATE TABLE "public"."HouseImportResultBlock" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid NOT NULL , 
   "HouseImportTransportGUID" uuid NOT NULL , 
   "BlockGUID" uuid , 
   "BlockUniqueNumber" character varying(31) COLLATE pg_catalog."default" , 
   "UpdateDate" date 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE HouseImportResultBlock OWNER to "BillBerry";

 
CREATE TABLE "public"."HouseImportResultBlockError" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid NOT NULL , 
   "HouseImportBlockTransportGUID" uuid NOT NULL , 
   "ErrorCode" character varying(32) COLLATE pg_catalog."default" NOT NULL , 
   "ErrorDescription" text COLLATE pg_catalog."default" NOT NULL 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE HouseImportResultBlockError OWNER to "BillBerry";

 
CREATE TABLE "public"."HouseImportResultEntrance" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid NOT NULL , 
   "HouseImportTransportGUID" uuid NOT NULL , 
   "EntranceGUID" uuid , 
   "UpdateDate" date 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE HouseImportResultEntrance OWNER to "BillBerry";

 
CREATE TABLE "public"."HouseImportResultEntranceError" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid NOT NULL , 
   "HouseImportEntranceTransportGUID" uuid NOT NULL , 
   "ErrorCode" character varying(32) COLLATE pg_catalog."default" NOT NULL , 
   "ErrorDescription" text COLLATE pg_catalog."default" NOT NULL 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE HouseImportResultEntranceError OWNER to "BillBerry";

 
CREATE TABLE "public"."HouseImportResultError" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid NOT NULL , 
   "HouseImportTransportGUID" uuid NOT NULL , 
   "ErrorCode" character varying(32) COLLATE pg_catalog."default" NOT NULL , 
   "ErrorDescription" text COLLATE pg_catalog."default" NOT NULL 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE HouseImportResultError OWNER to "BillBerry";

 
CREATE TABLE "public"."HouseImportResultLivingRoom" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid NOT NULL , 
   "HouseImportTransportGUID" uuid NOT NULL , 
   "LivingRoomGUID" uuid , 
   "LivingRoomUniqueNumber" character varying(31) COLLATE pg_catalog."default" , 
   "UpdateDate" date 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE HouseImportResultLivingRoom OWNER to "BillBerry";

 
CREATE TABLE "public"."HouseImportResultLivingRoomError" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid NOT NULL , 
   "HouseImportLivingRoomTransportGUID" uuid NOT NULL , 
   "ErrorCode" character varying(32) COLLATE pg_catalog."default" NOT NULL , 
   "ErrorDescription" text COLLATE pg_catalog."default" NOT NULL 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE HouseImportResultLivingRoomError OWNER to "BillBerry";

 
CREATE TABLE "public"."HouseImportResultPremise" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid NOT NULL , 
   "HouseImportTransportGUID" uuid NOT NULL , 
   "PremisesGUID" uuid , 
   "PremisesUniqueNumber" character varying(31) COLLATE pg_catalog."default" , 
   "UpdateDate" date 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE HouseImportResultPremise OWNER to "BillBerry";

 
CREATE TABLE "public"."HouseImportResultPremiseError" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid NOT NULL , 
   "HouseImportPremiseTransportGUID" uuid NOT NULL , 
   "ErrorCode" character varying(32) COLLATE pg_catalog."default" NOT NULL , 
   "ErrorDescription" text COLLATE pg_catalog."default" NOT NULL 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE HouseImportResultPremiseError OWNER to "BillBerry";

 
CREATE TABLE "public"."NotificationImportDeleteRequest" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid NOT NULL , 
   "NotificationGUID" uuid NOT NULL 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE NotificationImportDeleteRequest OWNER to "BillBerry";

 
CREATE TABLE "public"."NotificationImportRequest" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid NOT NULL , 
   "NotificationGUID" uuid , 
   "Topic" character varying(200) COLLATE pg_catalog."default" NOT NULL , 
   "Content" character varying(2000) COLLATE pg_catalog."default" , 
   "IsImportant" bool NOT NULL , 
   "StartDate" date , 
   "EndDate" date 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE NotificationImportRequest OWNER to "BillBerry";

 
CREATE TABLE "public"."NotificationImportRequestAccountDebt" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid NOT NULL , 
   "NotificationImportTransportGUID" uuid NOT NULL , 
   "UnifiedAccountNumber" character varying(10) COLLATE pg_catalog."default" NOT NULL , 
   "TotalDebt" numeric(20,10) NOT NULL 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE NotificationImportRequestAccountDebt OWNER to "BillBerry";

 
CREATE TABLE "public"."NotificationImportResult" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid NOT NULL , 
   "NotificationGUID" uuid , 
   "UpdateDate" date 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE NotificationImportResult OWNER to "BillBerry";

 
CREATE TABLE "public"."NotificationImportResultError" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid NOT NULL , 
   "NotificationImportTransportGUID" uuid NOT NULL , 
   "ErrorCode" character varying(32) COLLATE pg_catalog."default" NOT NULL , 
   "ErrorDescription" text COLLATE pg_catalog."default" NOT NULL 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE NotificationImportResultError OWNER to "BillBerry";

 
CREATE TABLE "public"."NsiExportRequest" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "TransportGUID" uuid NOT NULL , 
   "RegistryNumber" integer NOT NULL , 
   "ModifiedAfter" date 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE NsiExportRequest OWNER to "BillBerry";

 
CREATE TABLE "public"."NsiExportResult" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "TransportGUID" uuid NOT NULL , 
   "RegistryNumber" integer NOT NULL , 
   "Code" character varying(20) COLLATE pg_catalog."default" NOT NULL , 
   "GUID" uuid NOT NULL , 
   "Modified" date NOT NULL , 
   "IsActual" bool NOT NULL 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE NsiExportResult OWNER to "BillBerry";

 
CREATE TABLE "public"."NsiExportResultField" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "TransportGUID" uuid NOT NULL , 
   "NsiExportTransportGUID" uuid NOT NULL , 
   "Name" character varying(200) COLLATE pg_catalog."default" NOT NULL , 
   "Value" character varying(1024) COLLATE pg_catalog."default" NOT NULL 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE NsiExportResultField OWNER to "BillBerry";

 
CREATE TABLE "public"."OrderImportCancellationRequest" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid NOT NULL , 
   "OrderID" character varying(32) COLLATE pg_catalog."default" NOT NULL , 
   "CancellationDate" date NOT NULL , 
   "Comment" character varying(210) COLLATE pg_catalog."default" 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE OrderImportCancellationRequest OWNER to "BillBerry";

 
CREATE TABLE "public"."OrderImportRequest" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid NOT NULL , 
   "OrderDate" date NOT NULL , 
   "AmountRub" numeric(20,10) NOT NULL , 
   "Year" smallint , 
   "Month" unknown field , 
   "ServiceID" character varying(13) COLLATE pg_catalog."default" , 
   "PaymentDocumentID" character varying(18) COLLATE pg_catalog."default" 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE OrderImportRequest OWNER to "BillBerry";

 
CREATE TABLE "public"."OrderImportResult" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid NOT NULL , 
   "OrderGUID" uuid , 
   "OrderID" character varying(32) COLLATE pg_catalog."default" , 
   "UpdateDate" date 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE OrderImportResult OWNER to "BillBerry";

 
CREATE TABLE "public"."OrderImportResultError" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid NOT NULL , 
   "OrderImportTransportGUID" uuid NOT NULL , 
   "ErrorCode" character varying(32) COLLATE pg_catalog."default" NOT NULL , 
   "ErrorDescription" text COLLATE pg_catalog."default" NOT NULL 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE OrderImportResultError OWNER to "BillBerry";

 
CREATE TABLE "public"."OrganizationExportRequest" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "TransportGUID" uuid NOT NULL , 
   "LastEditingDateFrom" date 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE OrganizationExportRequest OWNER to "BillBerry";

 
CREATE TABLE "public"."OrganizationExportRequestData" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "TransportGUID" uuid NOT NULL , 
   "OrganizationExportTransportGUID" uuid NOT NULL , 
   "orgType" unknown field NOT NULL , 
   "OrgGUID" uuid , 
   "OrgVersionGUID" uuid , 
   "OGRN" character varying(15) COLLATE pg_catalog."default" , 
   "KPP" character varying(9) COLLATE pg_catalog."default" , 
   "OrgPPAGUID" uuid , 
   "IsRegistered" bool 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE OrganizationExportRequestData OWNER to "BillBerry";

 
CREATE TABLE "public"."OrganizationExportResult" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "TransportGUID" uuid NOT NULL , 
   "orgType" unknown field NOT NULL , 
   "OrgGUID" uuid NOT NULL , 
   "OrgVersionGUID" uuid NOT NULL , 
   "RegistryOrganizationStatus" character varying(1) COLLATE pg_catalog."default" , 
   "OrgPPAGUID" uuid , 
   "IsRegistered" bool , 
   "IsVersionActual" bool NOT NULL , 
   "VersionLastEditingDate" date NOT NULL 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE OrganizationExportResult OWNER to "BillBerry";

 
CREATE TABLE "public"."OrganizationExportResultEntp" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "TransportGUID" uuid NOT NULL , 
   "FirstName" character varying(255) COLLATE pg_catalog."default" NOT NULL , 
   "Surname" character varying(255) COLLATE pg_catalog."default" NOT NULL , 
   "Patronymic" character varying(255) COLLATE pg_catalog."default" , 
   "Sex" character varying(1) COLLATE pg_catalog."default" , 
   "OGRN" character varying(15) COLLATE pg_catalog."default" NOT NULL , 
   "INN" character varying(12) COLLATE pg_catalog."default" , 
   "StateRegistrationDate" date 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE OrganizationExportResultEntp OWNER to "BillBerry";

 
CREATE TABLE "public"."OrganizationExportResultLegal" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "TransportGUID" uuid NOT NULL , 
   "FullName" character varying(4000) COLLATE pg_catalog."default" NOT NULL , 
   "ShortName" character varying(500) COLLATE pg_catalog."default" , 
   "CommercialName" character varying(255) COLLATE pg_catalog."default" , 
   "OGRN" character varying(13) COLLATE pg_catalog."default" NOT NULL , 
   "INN" character varying(10) COLLATE pg_catalog."default" , 
   "KPP" character varying(9) COLLATE pg_catalog."default" , 
   "OKOPF" character varying(5) COLLATE pg_catalog."default" , 
   "StateRegistrationDate" date , 
   "ActivityEndDate" date , 
   "Address" text COLLATE pg_catalog."default" , 
   "FIASHouseGuid" uuid 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE OrganizationExportResultLegal OWNER to "BillBerry";

 
CREATE TABLE "public"."OrganizationExportResultRole" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "TransportGUID" uuid NOT NULL , 
   "OrganizationExportTransportGUID" uuid NOT NULL , 
   "OrganizationRoleCode" character varying(20) COLLATE pg_catalog."default" NOT NULL , 
   "OrganizationRoleGUID" uuid NOT NULL 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE OrganizationExportResultRole OWNER to "BillBerry";

 
CREATE TABLE "public"."PaymentExportRequest" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "TransportGUID" uuid NOT NULL , 
   "Month" unknown field , 
   "Year" smallint , 
   "FIASHouseGuid" uuid 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE PaymentExportRequest OWNER to "BillBerry";

 
CREATE TABLE "public"."PaymentExportRequestAccount" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid NOT NULL , 
   "PaymentExportTransportGUID" uuid NOT NULL , 
   "AccountGUID" uuid , 
   "AccountNumber" character varying(30) COLLATE pg_catalog."default" , 
   "UnifiedAccountNumber" character varying(10) COLLATE pg_catalog."default" , 
   "ServiceID" character varying(13) COLLATE pg_catalog."default" 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE PaymentExportRequestAccount OWNER to "BillBerry";

 
CREATE TABLE "public"."PaymentExportRequestDocument" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid NOT NULL , 
   "PaymentExportTransportGUID" uuid NOT NULL , 
   "PaymentDocumentID" character varying(18) COLLATE pg_catalog."default" , 
   "PaymentDocumentNumber" character varying(30) COLLATE pg_catalog."default" 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE PaymentExportRequestDocument OWNER to "BillBerry";

 
CREATE TABLE "public"."PaymentExportResult" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "TransportGUID" uuid NOT NULL , 
   "PaymentDocumentID" character varying(18) COLLATE pg_catalog."default" NOT NULL , 
   "PaymentDocumentNumber" character varying(30) COLLATE pg_catalog."default" , 
   "AccountGUID" uuid NOT NULL , 
   "Withdraw" bool NOT NULL 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE PaymentExportResult OWNER to "BillBerry";

 
CREATE TABLE "public"."PaymentImportRequest" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid NOT NULL , 
   "PaymentDocumentID" character varying(18) COLLATE pg_catalog."default" , 
   "PaymentDocumentNumber" character varying(30) COLLATE pg_catalog."default" , 
   "AccountGUID" uuid NOT NULL , 
   "Month" unknown field NOT NULL , 
   "Year" smallint NOT NULL , 
   "ConfirmAmountsCorrect" bool , 
   "BankBIK" character varying(9) COLLATE pg_catalog."default" NOT NULL , 
   "OperatingAccountNumber" character varying(20) COLLATE pg_catalog."default" NOT NULL , 
   "DebtPreviousPeriods" numeric(20,10) , 
   "AdvanceBllingPeriod" numeric(20,10) , 
   "TotalPiecemealPaymentSum" numeric(20,10) , 
   "PaymentsTaken" unknown field , 
   "AdditionalInformation" character varying(1000) COLLATE pg_catalog."default" , 
   "TotalPayableByPD" numeric(20,10) , 
   "TotalPayableByChargeInfo" numeric(20,10) , 
   "TotalPayableByPDWithDebtAndAdvance" numeric(20,10) , 
   "TotalByPenaltiesAndCourtCosts" numeric(20,10) , 
   "PaidCash" numeric(20,10) , 
   "DateOfLastReceivedPayment" date , 
   "LimitIndex" numeric(20,10) , 
   "SubsidiesCompensationSocialSupport" numeric(20,10) 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE PaymentImportRequest OWNER to "BillBerry";

 
CREATE TABLE "public"."PaymentImportRequestChargesMunicipalService" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid NOT NULL , 
   "PaymentImportTransportGUID" uuid NOT NULL , 
   "MainMunicipalServiceCode" character varying(20) COLLATE pg_catalog."default" NOT NULL , 
   "MainMunicipalServiceGUID" uuid NOT NULL , 
   "Rate" numeric(20,10) NOT NULL , 
   "TotalPayable" numeric(20,10) NOT NULL , 
   "AccountingPeriodTotal" numeric(20,10) , 
   "CalcExplanation" character varying(4000) COLLATE pg_catalog."default" , 
   "MoneyRecalculation" numeric(20,10) , 
   "MoneyDiscount" numeric(20,10) , 
   "VolumeI" numeric(20,10) , 
   "VolumeO" numeric(20,10) , 
   "DeterminingMethodI" character varying(1) COLLATE pg_catalog."default" , 
   "DeterminingMethodO" character varying(1) COLLATE pg_catalog."default" , 
   "RecalculationReason" character varying(500) COLLATE pg_catalog."default" , 
   "Sum" numeric(20,10) , 
   "IndividualConsumptionPayable" numeric(20,10) , 
   "CommunalConsumptionPayable" numeric(20,10) , 
   "MultiplyingFactorRatio" numeric(20,10) , 
   "MultiplyingFactorAmount" numeric(20,10) , 
   "AmountI" numeric(20,10) , 
   "AmountO" numeric(20,10) , 
   "DebtPreviousPeriodsOrAdvanceBillingPeriod" numeric(20,10) , 
   "Penalties" numeric(20,10) , 
   "StateFees" numeric(20,10) , 
   "CourtCosts" numeric(20,10) , 
   "TotalPayableOverall" numeric(20,10) 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE PaymentImportRequestChargesMunicipalService OWNER to "BillBerry";

 
CREATE TABLE "public"."PaymentImportRequestChargesMunicipalServiceNorm" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid NOT NULL , 
   "IndividualConsumptionCurrentValue" numeric(20,10) , 
   "HouseOverallNeedsCurrentValue" numeric(20,10) , 
   "HouseTotalIndividualConsumption" numeric(20,10) , 
   "HouseTotalHouseOverallNeeds" numeric(20,10) , 
   "HouseOverallNeedsNorm" numeric(20,10) , 
   "IndividualConsumptionNorm" numeric(20,10) 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE PaymentImportRequestChargesMunicipalServiceNorm OWNER to "BillBerry";

 
CREATE TABLE "public"."PaymentImportRequestDebtMunicipalService" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid NOT NULL , 
   "PaymentImportTransportGUID" uuid NOT NULL , 
   "MainMunicipalServiceCode" character varying(20) COLLATE pg_catalog."default" NOT NULL , 
   "MainMunicipalServiceGUID" uuid NOT NULL , 
   "Month" unknown field NOT NULL , 
   "Year" smallint NOT NULL , 
   "TotalPayable" numeric(20,10) NOT NULL 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE PaymentImportRequestDebtMunicipalService OWNER to "BillBerry";

 
CREATE TABLE "public"."PaymentImportRequestPenaltyAndCourtCost" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid NOT NULL , 
   "PaymentImportTransportGUID" uuid NOT NULL , 
   "PenaltyAndCourtCostCode" character varying(20) COLLATE pg_catalog."default" NOT NULL , 
   "PenaltyAndCourtCostGUID" uuid NOT NULL , 
   "Cause" character varying(1000) COLLATE pg_catalog."default" NOT NULL , 
   "TotalPayable" numeric(20,10) NOT NULL 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE PaymentImportRequestPenaltyAndCourtCost OWNER to "BillBerry";

 
CREATE TABLE "public"."PaymentImportResult" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid NOT NULL , 
   "PaymentDocumentGUID" uuid , 
   "PaymentDocumentID" character varying(18) COLLATE pg_catalog."default" , 
   "UpdateDate" date 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE PaymentImportResult OWNER to "BillBerry";

 
CREATE TABLE "public"."PaymentImportResultError" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid NOT NULL , 
   "PaymentImportTransportGUID" uuid NOT NULL , 
   "ErrorCode" character varying(32) COLLATE pg_catalog."default" NOT NULL , 
   "ErrorDescription" text COLLATE pg_catalog."default" NOT NULL 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE PaymentImportResultError OWNER to "BillBerry";

 
CREATE TABLE "public"."PaymentImportWithdrawRequest" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid NOT NULL , 
   "PaymentDocumentID" character varying(18) COLLATE pg_catalog."default" NOT NULL 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE PaymentImportWithdrawRequest OWNER to "BillBerry";

 
CREATE TABLE "public"."SettlementImportAnnulmentRequest" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid NOT NULL , 
   "SettlementGUID" uuid NOT NULL , 
   "ReasonOfAnnulment" character varying(2000) COLLATE pg_catalog."default" NOT NULL 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE SettlementImportAnnulmentRequest OWNER to "BillBerry";

 
CREATE TABLE "public"."SettlementImportRequest" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid NOT NULL , 
   "SettlementGUID" uuid , 
   "ContractGUID" uuid NOT NULL 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE SettlementImportRequest OWNER to "BillBerry";

 
CREATE TABLE "public"."SettlementImportRequestPeriod" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid NOT NULL , 
   "SettlementImportTransportGUID" uuid NOT NULL , 
   "Month" unknown field NOT NULL , 
   "Year" smallint NOT NULL 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE SettlementImportRequestPeriod OWNER to "BillBerry";

 
CREATE TABLE "public"."SettlementImportRequestPeriodAnnulment" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid NOT NULL , 
   "ReasonOfAnnulment" character varying(2000) COLLATE pg_catalog."default" NOT NULL 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE SettlementImportRequestPeriodAnnulment OWNER to "BillBerry";

 
CREATE TABLE "public"."SettlementImportRequestPeriodInfo" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid NOT NULL , 
   "Credted" numeric(20,10) NOT NULL , 
   "Receipt" numeric(20,10) NOT NULL , 
   "Debts" numeric(20,10) NOT NULL , 
   "Overpayment" numeric(20,10) NOT NULL , 
   "Paid" numeric(20,10) 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE SettlementImportRequestPeriodInfo OWNER to "BillBerry";

 
CREATE TABLE "public"."SettlementImportResult" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid NOT NULL , 
   "SettlementGUID" uuid , 
   "UpdateDate" date 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE SettlementImportResult OWNER to "BillBerry";

 
CREATE TABLE "public"."SettlementImportResultError" 
( 
   "uniqueId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid NOT NULL , 
   "SettlementImportTransportGUID" uuid NOT NULL , 
   "ErrorCode" character varying(32) COLLATE pg_catalog."default" NOT NULL , 
   "ErrorDescription" text COLLATE pg_catalog."default" NOT NULL 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE SettlementImportResultError OWNER to "BillBerry";

 
CREATE TABLE "public"."SysOperation" 
( 
   "OperationId" integer NOT NULL , 
   "OperationName" character varying(128) COLLATE pg_catalog."default" NOT NULL , 
   "Name" character varying(1024) COLLATE pg_catalog."default" NOT NULL , 
   "PacketSize" integer NOT NULL 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE SysOperation OWNER to "BillBerry";

 
CREATE TABLE "public"."SysParams" 
( 
   "Id" integer NOT NULL , 
   "VersionNumber" character varying(32) COLLATE pg_catalog."default" NOT NULL 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE SysParams OWNER to "BillBerry";

 
CREATE TABLE "public"."SysRegistry" 
( 
   "RegistryId" integer NOT NULL , 
   "RegistryName" character varying(128) COLLATE pg_catalog."default" NOT NULL , 
   "Name" character varying(1024) COLLATE pg_catalog."default" NOT NULL 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE SysRegistry OWNER to "BillBerry";

 
CREATE TABLE "public"."SysTransaction" 
( 
   "TransactionGUID" uuid NOT NULL , 
   "ListGUID" uuid , 
   "ClientId" character varying(32) COLLATE pg_catalog."default" NOT NULL , 
   "OperationId" integer NOT NULL , 
   "StartDate" date NOT NULL , 
   "EndDate" date , 
   "StatusId" integer NOT NULL , 
   "LastExecutionDate" date , 
   "NextExecutionDate" date , 
   "ResultId" integer , 
   "ErrorCode" character varying(32) COLLATE pg_catalog."default" , 
   "ErrorDescription" character varying(4000) COLLATE pg_catalog."default" 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE SysTransaction OWNER to "BillBerry";

 
CREATE TABLE "public"."SysTransactionLog" 
( 
   "TransactionLogId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "LogDate" date NOT NULL , 
   "LogData" character varying(1024) COLLATE pg_catalog."default" , 
   "ErrorCode" character varying(32) COLLATE pg_catalog."default" , 
   "ErrorDescription" text COLLATE pg_catalog."default" , 
   "ErrorStackTrace" text COLLATE pg_catalog."default" 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE SysTransactionLog OWNER to "BillBerry";

 
CREATE TABLE "public"."SysTransactionObject" 
( 
   "TransactionObjectId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" NOT NULL , 
   "comment" text COLLATE pg_catalog."default" , 
   "operation" integer NOT NULL , 
   "group" integer , 
   "param" text COLLATE pg_catalog."default" 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE SysTransactionObject OWNER to "BillBerry";

 
CREATE TABLE "public"."SysTransactionObjectError" 
( 
   "TransactionObjectErrorId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" NOT NULL , 
   "errorCode" character varying(32) COLLATE pg_catalog."default" NOT NULL , 
   "errorDescription" text COLLATE pg_catalog."default" 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE SysTransactionObjectError OWNER to "BillBerry";

 
CREATE TABLE "public"."SysTransactionParam" 
( 
   "TransactionParamId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "ParamName" character varying(128) COLLATE pg_catalog."default" NOT NULL , 
   "ParamValue" character varying(1024) COLLATE pg_catalog."default" 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE SysTransactionParam OWNER to "BillBerry";

 
CREATE TABLE "public"."SysTransactionState2" 
( 
   "TransactionStateId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "StateGUID" uuid NOT NULL , 
   "AsyncStateGUID" uuid , 
   "TransactionGUID" uuid NOT NULL , 
   "OperationId" integer NOT NULL , 
   "StateTypeId" unknown field NOT NULL , 
   "StateDate" date NOT NULL , 
   "StateData" text COLLATE pg_catalog."default" 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE SysTransactionState2 OWNER to "BillBerry";

 
CREATE TABLE "public"."SysTransactionStateType" 
( 
   "TransactionStateTypeId" unknown field NOT NULL , 
   "TransactionStateTypeName" character varying(128) COLLATE pg_catalog."default" NOT NULL 
) TABLESPACE "BillBerryTS"; 
 ALTER TABLE SysTransactionStateType OWNER to "BillBerry";


