 
CREATE TABLE "gis_hcs"."AccountExportRequest" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "FIASHouseGuid" uuid UNIQUE NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."AccountExportRequest" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."AccountExportResult" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "AccountGUID" uuid UNIQUE NOT NULL , 
   "AccountNumber" character varying(30) COLLATE pg_catalog."default" , 
   "UnifiedAccountNumber" character varying(10) COLLATE pg_catalog."default" NOT NULL , 
   "ServiceID" character varying(13) COLLATE pg_catalog."default" , 
   "IsRSOAccount" bool NOT NULL , 
   "CreationDate" date , 
   "LivingPersonsNumber" smallint , 
   "TotalSquare" numeric(20,10) , 
   "ResidentialSquare" numeric(20,10) , 
   "HeatedArea" numeric(20,10) , 
   "AccountCloseReasonCode" character varying(20) COLLATE pg_catalog."default" , 
   "AccountCloseReasonGUID" uuid UNIQUE , 
   "CloseDate" date , 
   "CloseDescription" character varying(250) COLLATE pg_catalog."default" , 
   "IsRenter" bool , 
   "IsAccountsDivided" bool , 
   "OrgVersionGUID" uuid UNIQUE 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."AccountExportResult" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."AccountExportResultPercentPremise" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "AccountExportTransportGUID" uuid UNIQUE NOT NULL , 
   "FIASHouseGuid" uuid UNIQUE , 
   "PremisesGUID" uuid UNIQUE , 
   "LivingRoomGUID" uuid UNIQUE , 
   "SharePercent" numeric(20,10) 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."AccountExportResultPercentPremise" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."AccountImportRequest" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "AccountGUID" uuid UNIQUE , 
   "AccountNumber" character varying(30) COLLATE pg_catalog."default" NOT NULL , 
   "IsRSOAccount" bool NOT NULL , 
   "CreationDate" date , 
   "LivingPersonsNumber" smallint , 
   "TotalSquare" numeric(20,10) , 
   "ResidentialSquare" numeric(20,10) , 
   "HeatedArea" numeric(20,10) , 
   "AccountCloseReasonCode" character varying(20) COLLATE pg_catalog."default" , 
   "AccountCloseReasonGUID" uuid UNIQUE , 
   "CloseDate" date , 
   "CloseDescription" character varying(250) COLLATE pg_catalog."default" , 
   "IsRenter" bool , 
   "IsAccountsDivided" bool , 
   "OrgVersionGUID" uuid UNIQUE 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."AccountImportRequest" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."AccountImportRequestPayer" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "Surname" character varying(256) COLLATE pg_catalog."default" NOT NULL , 
   "FirstName" character varying(256) COLLATE pg_catalog."default" NOT NULL , 
   "Patronymic" character varying(256) COLLATE pg_catalog."default" , 
   "Sex" character varying(1) COLLATE pg_catalog."default" , 
   "DateOfBirth" date , 
   "SNILS" character varying(11) COLLATE pg_catalog."default" , 
   "DocumentTypeCode" character varying(20) COLLATE pg_catalog."default" , 
   "DocumentTypeGUID" uuid UNIQUE , 
   "Series" character varying(45) COLLATE pg_catalog."default" , 
   "Number" character varying(45) COLLATE pg_catalog."default" , 
   "IssueDate" date 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."AccountImportRequestPayer" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."AccountImportRequestPercentPremise" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "AccountImportTransportGUID" uuid UNIQUE NOT NULL , 
   "FIASHouseGuid" uuid UNIQUE , 
   "PremisesGUID" uuid UNIQUE , 
   "LivingRoomGUID" uuid UNIQUE , 
   "SharePercent" numeric(20,10) 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."AccountImportRequestPercentPremise" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."AccountImportRequestReason" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "AccountImportTransportGUID" uuid UNIQUE NOT NULL , 
   "ContractGUID" uuid UNIQUE NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."AccountImportRequestReason" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."AccountImportResult" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "AccountGUID" uuid UNIQUE , 
   "UnifiedAccountNumber" character varying(10) COLLATE pg_catalog."default" , 
   "ServiceID" character varying(13) COLLATE pg_catalog."default" , 
   "UpdateDate" date 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."AccountImportResult" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."AccountImportResultError" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "AccountImportTransportGUID" uuid UNIQUE NOT NULL , 
   "ErrorCode" character varying(32) COLLATE pg_catalog."default" NOT NULL , 
   "ErrorDescription" text COLLATE pg_catalog."default" NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."AccountImportResultError" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."AckImportCancellationRequest" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "OrderGUID" uuid UNIQUE NOT NULL , 
   "PaymentDocumentID" character varying(18) COLLATE pg_catalog."default" 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."AckImportCancellationRequest" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."AckImportRequest" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "OrderGUID" uuid UNIQUE NOT NULL , 
   "PaymentDocumentID" character varying(18) COLLATE pg_catalog."default" , 
   "AckImpossible" bool NOT NULL , 
   "AckImpossibleReason" character varying(210) COLLATE pg_catalog."default" , 
   "AmountRub" numeric(20,10) , 
   "HousingServiceCode" character varying(20) COLLATE pg_catalog."default" , 
   "HousingServiceGUID" uuid UNIQUE , 
   "MainMunicipalServiceCode" character varying(20) COLLATE pg_catalog."default" , 
   "MainMunicipalServiceGUID" uuid UNIQUE , 
   "AdditionalServiceCode" character varying(20) COLLATE pg_catalog."default" , 
   "AdditionalServiceGUID" uuid UNIQUE , 
   "PenaltyAndCourtCostCode" character varying(20) COLLATE pg_catalog."default" , 
   "PenaltyAndCourtCostGUID" uuid UNIQUE , 
   "MunicipalServiceCode" character varying(20) COLLATE pg_catalog."default" , 
   "MunicipalServiceGUID" uuid UNIQUE , 
   "BankBIK" character varying(9) COLLATE pg_catalog."default" , 
   "OperatingAccountNumber" character varying(20) COLLATE pg_catalog."default" , 
   "DelayPeriodMonth" smallint , 
   "DelayPeriodYear" smallint , 
   "CapitalRepairPeriodMonth" smallint , 
   "CapitalRepairPeriodYear" smallint 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."AckImportRequest" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."AckImportResult" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "AckGUID" uuid UNIQUE , 
   "UniqueNumber" character varying(128) COLLATE pg_catalog."default" , 
   "UpdateDate" date 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."AckImportResult" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."AckImportResultError" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "AckImportTransportGUID" uuid UNIQUE NOT NULL , 
   "ErrorCode" character varying(32) COLLATE pg_catalog."default" NOT NULL , 
   "ErrorDescription" text COLLATE pg_catalog."default" NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."AckImportResultError" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."AttachmentPostRequest" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "Name" character varying(1024) COLLATE pg_catalog."default" NOT NULL , 
   "Description" character varying(500) COLLATE pg_catalog."default" NOT NULL , 
   "AttachmentBody" text COLLATE pg_catalog."default" NOT NULL , 
   "numCopies" smallint NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."AttachmentPostRequest" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."AttachmentPostResult" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "AttachmentHASH" character varying(1024) COLLATE pg_catalog."default" NOT NULL , 
   "ErrorCode" character varying(32) COLLATE pg_catalog."default" , 
   "ErrorDescription" character varying(128) COLLATE pg_catalog."default" 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."AttachmentPostResult" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."AttachmentPostResultCopy" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "AttachmentPostTransportGUID" uuid UNIQUE NOT NULL , 
   "AttachmentGUID" uuid UNIQUE NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."AttachmentPostResultCopy" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."ContractImportRequest" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "ContractGUID" uuid UNIQUE , 
   "ComptetionDate" date , 
   "ShowStartDate" smallint , 
   "ShowStartDateNextMonth" bool , 
   "ShowEndDate" smallint , 
   "ShowEndDateNextMonth" bool , 
   "ContractConclusionReasonCode" character varying(20) COLLATE pg_catalog."default" , 
   "ContractConclusionReasonGUID" uuid UNIQUE , 
   "ContractingParty" smallint NOT NULL , 
   "CountingResource" character varying(1) COLLATE pg_catalog."default" , 
   "IsContract" bool NOT NULL , 
   "ContractNumber" character varying(30) COLLATE pg_catalog."default" , 
   "SigningDate" date , 
   "EffectiveDate" date , 
   "BillingDate" smallint , 
   "PaymentDate" smallint , 
   "ProvidingInformationDate" smallint , 
   "BillingDateType" character varying(1) COLLATE pg_catalog."default" , 
   "PaymentDateType" character varying(1) COLLATE pg_catalog."default" , 
   "ProvidingInformationDateType" character varying(1) COLLATE pg_catalog."default" , 
   "IsPlannedVolume" bool NOT NULL , 
   "SpecifyingQualityIndicators" character varying(1) COLLATE pg_catalog."default" NOT NULL , 
   "MeteringDeviceInformation" bool , 
   "VolumeDepends" bool , 
   "OneTimePayment" bool , 
   "IndefiniteTerm" bool , 
   "AutomaticRollOverOneYear" bool , 
   "AccrualProcedure" character varying(1) COLLATE pg_catalog."default" , 
   "IndicationsAnyDay" bool , 
   "PlannedVolumeType" character varying(1) COLLATE pg_catalog."default" , 
   "OrgGUID" uuid UNIQUE 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."ContractImportRequest" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."ContractImportRequestAttachment" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "ContractImportTransportGUID" uuid UNIQUE NOT NULL , 
   "Name" character varying(1024) COLLATE pg_catalog."default" NOT NULL , 
   "Description" character varying(500) COLLATE pg_catalog."default" NOT NULL , 
   "AttachmentBody" text COLLATE pg_catalog."default" , 
   "AttachmentHASH" text COLLATE pg_catalog."default" , 
   "AttachmentGUID" uuid UNIQUE 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."ContractImportRequestAttachment" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."ContractImportRequestObjectAddress" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "ContractImportTransportGUID" uuid UNIQUE NOT NULL , 
   "houseType" smallint , 
   "FIASHouseGuid" uuid UNIQUE NOT NULL , 
   "ApartmentNumber" character varying(255) COLLATE pg_catalog."default" , 
   "RoomNumber" character varying(255) COLLATE pg_catalog."default" 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."ContractImportRequestObjectAddress" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."ContractImportRequestObjectServiceResource" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "ContractImportObjectAddressTransportGUID" uuid UNIQUE NOT NULL , 
   "ContractImportSubjectTransportGUID" uuid UNIQUE NOT NULL , 
   "StartSupplyDate" date NOT NULL , 
   "EndSupplyDate" date , 
   "OpenOrNot" character varying(32) COLLATE pg_catalog."default" , 
   "CentralizedOrNot" character varying(32) COLLATE pg_catalog."default" 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."ContractImportRequestObjectServiceResource" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."ContractImportRequestParty" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "FirstName" character varying(60) COLLATE pg_catalog."default" NOT NULL , 
   "Surname" character varying(60) COLLATE pg_catalog."default" NOT NULL , 
   "Patronymic" character varying(60) COLLATE pg_catalog."default" , 
   "Sex" character varying(1) COLLATE pg_catalog."default" , 
   "DateOfBirth" date , 
   "DocumentTypeCode" character varying(20) COLLATE pg_catalog."default" , 
   "DocumentTypeGUID" uuid UNIQUE , 
   "Series" character varying(45) COLLATE pg_catalog."default" , 
   "Number" character varying(45) COLLATE pg_catalog."default" , 
   "IssueDate" date , 
   "SNILS" character varying(11) COLLATE pg_catalog."default" , 
   "PlaceBirth" character varying(255) COLLATE pg_catalog."default" 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."ContractImportRequestParty" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."ContractImportRequestSubject" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "ContractImportTransportGUID" uuid UNIQUE NOT NULL , 
   "MunicipalServiceCode" character varying(20) COLLATE pg_catalog."default" NOT NULL , 
   "MunicipalServiceGUID" uuid UNIQUE NOT NULL , 
   "ChargeableResourceCode" character varying(20) COLLATE pg_catalog."default" NOT NULL , 
   "ChargeableResourceGUID" uuid UNIQUE NOT NULL , 
   "StartSupplyDate" date NOT NULL , 
   "EndSupplyDate" date , 
   "Volume" numeric(20,10) , 
   "Unit" character varying(4) COLLATE pg_catalog."default" , 
   "FeedingMode" character varying(250) COLLATE pg_catalog."default" 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."ContractImportRequestSubject" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."ContractImportRequestSubjectQualityIndicator" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "ContractImportSubjectTransportGUID" uuid UNIQUE NOT NULL , 
   "ContractImportObjectAddressTransportGUID" uuid UNIQUE , 
   "QualityIndicatorCode" character varying(20) COLLATE pg_catalog."default" , 
   "QualityIndicatorGUID" uuid UNIQUE , 
   "Number" numeric(20,10) , 
   "StartRange" numeric(20,10) , 
   "EndRange" numeric(20,10) , 
   "OKEI" character varying(4) COLLATE pg_catalog."default" , 
   "Correspond" bool , 
   "IndicatorName" character varying(1000) COLLATE pg_catalog."default" 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."ContractImportRequestSubjectQualityIndicator" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."ContractImportResult" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "ContractGUID" uuid UNIQUE , 
   "ContractVersionGUID" uuid UNIQUE , 
   "UpdateDate" date 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."ContractImportResult" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."ContractImportResultError" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "ContractImportTransportGUID" uuid UNIQUE NOT NULL , 
   "ContractImportObjectAddressTransportGUID" uuid UNIQUE , 
   "ContractImportSubjectTransportGUID" uuid UNIQUE , 
   "ErrorCode" character varying(32) COLLATE pg_catalog."default" NOT NULL , 
   "ErrorDescription" text COLLATE pg_catalog."default" NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."ContractImportResultError" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."DeviceExportRequest" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "DeviceGUID" uuid UNIQUE , 
   "FIASHouseGuid" uuid UNIQUE 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."DeviceExportRequest" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."DeviceExportResult" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "DeviceGUID" uuid UNIQUE NOT NULL , 
   "DeviceVersionGUID" uuid UNIQUE NOT NULL , 
   "StatusRootDoc" character varying(32) COLLATE pg_catalog."default" NOT NULL , 
   "deviceType" smallint NOT NULL , 
   "individualDeviceType" smallint , 
   "DeviceNumber" character varying(50) COLLATE pg_catalog."default" NOT NULL , 
   "DeviceStamp" character varying(100) COLLATE pg_catalog."default" , 
   "DeviceModel" character varying(100) COLLATE pg_catalog."default" , 
   "InstallationDate" date , 
   "CommissioningDate" date , 
   "RemoteMeteringMode" bool NOT NULL , 
   "RemoteMeteringInfo" character varying(2000) COLLATE pg_catalog."default" , 
   "FirstVerificationDate" date , 
   "DeviceCalibrationIntervalCode" character varying(20) COLLATE pg_catalog."default" , 
   "DeviceCalibrationIntervalGUID" uuid UNIQUE , 
   "FactorySealDate" date , 
   "TemperatureSensor" bool NOT NULL , 
   "PressureSensor" bool NOT NULL , 
   "ConsumedVolume" bool 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."DeviceExportResult" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."DeviceExportResultAccount" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "DeviceExportTransportGUID" uuid UNIQUE NOT NULL , 
   "AccountGUID" uuid UNIQUE NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."DeviceExportResultAccount" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."DeviceExportResultAddress" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "DeviceExportTransportGUID" uuid UNIQUE NOT NULL , 
   "AddressGUID" uuid UNIQUE NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."DeviceExportResultAddress" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."DeviceImportArchiveRequest" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "DeviceVersionGUID" uuid UNIQUE NOT NULL , 
   "DeviceArchivingReasonCode" character varying(20) COLLATE pg_catalog."default" NOT NULL , 
   "DeviceArchivingReasonGUID" uuid UNIQUE NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."DeviceImportArchiveRequest" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."DeviceImportReplaceRequest" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "DeviceVersionGUID" uuid UNIQUE NOT NULL , 
   "VerificationDate" date NOT NULL , 
   "PlannedVerification" bool , 
   "DeviceFaultReasonCode" character varying(20) COLLATE pg_catalog."default" , 
   "DeviceFaultReasonGUID" uuid UNIQUE , 
   "ReplacingDeviceVersionGUID" uuid UNIQUE NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."DeviceImportReplaceRequest" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."DeviceImportReplaceRequestValue" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "DeviceImportReplaceTransportGUID" uuid UNIQUE NOT NULL , 
   "MunicipalResourceCode" character varying(20) COLLATE pg_catalog."default" NOT NULL , 
   "MunicipalResourceGUID" uuid UNIQUE NOT NULL , 
   "ValueT1" numeric(20,10) NOT NULL , 
   "ValueT2" numeric(20,10) , 
   "ValueT3" numeric(20,10) 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."DeviceImportReplaceRequestValue" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."DeviceImportRequest" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "DeviceVersionGUID" uuid UNIQUE , 
   "deviceType" smallint NOT NULL , 
   "individualDeviceType" smallint , 
   "DeviceNumber" character varying(50) COLLATE pg_catalog."default" NOT NULL , 
   "DeviceStamp" character varying(100) COLLATE pg_catalog."default" NOT NULL , 
   "DeviceModel" character varying(100) COLLATE pg_catalog."default" NOT NULL , 
   "InstallationDate" date , 
   "CommissioningDate" date , 
   "RemoteMeteringMode" bool NOT NULL , 
   "RemoteMeteringInfo" character varying(2000) COLLATE pg_catalog."default" , 
   "FirstVerificationDate" date , 
   "DeviceCalibrationIntervalCode" character varying(20) COLLATE pg_catalog."default" , 
   "DeviceCalibrationIntervalGUID" uuid UNIQUE , 
   "FactorySealDate" date NOT NULL , 
   "TemperatureSensor" bool NOT NULL , 
   "TemperatureSensingElementInfo" character varying(2000) COLLATE pg_catalog."default" , 
   "PressureSensor" bool NOT NULL , 
   "PressureSensingElementInfo" character varying(2000) COLLATE pg_catalog."default" , 
   "InstallationPlace" character varying(1) COLLATE pg_catalog."default" , 
   "ConsumedVolume" bool 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."DeviceImportRequest" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."DeviceImportRequestAccount" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "DeviceImportTransportGUID" uuid UNIQUE NOT NULL , 
   "AccountGUID" uuid UNIQUE NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."DeviceImportRequestAccount" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."DeviceImportRequestAddress" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "DeviceImportTransportGUID" uuid UNIQUE NOT NULL , 
   "AddressGUID" uuid UNIQUE NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."DeviceImportRequestAddress" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."DeviceImportRequestLinkedDevice" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "DeviceImportTransportGUID" uuid UNIQUE NOT NULL , 
   "DeviceVersionGUID" uuid UNIQUE NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."DeviceImportRequestLinkedDevice" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."DeviceImportRequestValue" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "DeviceImportTransportGUID" uuid UNIQUE NOT NULL , 
   "MunicipalResourceCode" character varying(20) COLLATE pg_catalog."default" NOT NULL , 
   "MunicipalResourceGUID" uuid UNIQUE NOT NULL , 
   "ValueT1" numeric(20,10) NOT NULL , 
   "ValueT2" numeric(20,10) , 
   "ValueT3" numeric(20,10) , 
   "TransformationRatio" numeric(20,10) 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."DeviceImportRequestValue" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."DeviceImportResult" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "DeviceGUID" uuid UNIQUE , 
   "DeviceVersionGUID" uuid UNIQUE , 
   "DeviceUniqueNumber" character varying(128) COLLATE pg_catalog."default" , 
   "UpdateDate" date 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."DeviceImportResult" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."DeviceImportResultError" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "DeviceImportTransportGUID" uuid UNIQUE NOT NULL , 
   "ErrorCode" character varying(32) COLLATE pg_catalog."default" NOT NULL , 
   "ErrorDescription" text COLLATE pg_catalog."default" NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."DeviceImportResultError" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."DeviceValueExportRequest" 
( 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "FIASHouseGuid" uuid UNIQUE NOT NULL , 
   "CommissioningDateFrom" date , 
   "CommissioningDateTo" date , 
   "SearchArchived" bool , 
   "ArchiveDateFrom" date , 
   "ArchiveDateTo" date , 
   "InputDateFrom" date , 
   "InputDateTo" date , 
   "ExcludePersonAsDataSource" bool , 
   "ExcludeCurrentOrgAsDataSource" bool , 
   "ExcludeOtherOrgAsDataSource" bool , 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."DeviceValueExportRequest" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."DeviceValueExportRequestDevice" 
( 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "DeviceValueExportTransportGUID" uuid UNIQUE NOT NULL , 
   "DeviceGUID" uuid UNIQUE NOT NULL , 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."DeviceValueExportRequestDevice" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."DeviceValueExportRequestDeviceType" 
( 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "DeviceValueExportTransportGUID" uuid UNIQUE NOT NULL , 
   "DeviceTypeCode" character varying(20) COLLATE pg_catalog."default" NOT NULL , 
   "DeviceTypeGUID" uuid UNIQUE NOT NULL , 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."DeviceValueExportRequestDeviceType" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."DeviceValueExportRequestMunicipalResource" 
( 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "DeviceValueExportTransportGUID" uuid UNIQUE NOT NULL , 
   "MunicipalResourceCode" character varying(20) COLLATE pg_catalog."default" NOT NULL , 
   "MunicipalResourceGUID" uuid UNIQUE NOT NULL , 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."DeviceValueExportRequestMunicipalResource" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."DeviceValueExportResult" 
( 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "DeviceGUID" uuid UNIQUE NOT NULL , 
   "deviceShowValueType" smallint NOT NULL , 
   "DateValue" date , 
   "MunicipalResourceCode" character varying(20) COLLATE pg_catalog."default" NOT NULL , 
   "MunicipalResourceGUID" uuid UNIQUE NOT NULL , 
   "ValueT1" numeric(20,10) NOT NULL , 
   "ValueT2" numeric(20,10) , 
   "ValueT3" numeric(20,10) , 
   "EnterIntoSystem" date NOT NULL , 
   "OrgPPAGUID" uuid UNIQUE , 
   "ReadingsSource" character varying(1024) COLLATE pg_catalog."default" , 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."DeviceValueExportResult" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."DeviceValueImportRequest" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "DeviceVersionGUID" uuid UNIQUE NOT NULL , 
   "deviceShowValueType" smallint NOT NULL , 
   "DateValue" date NOT NULL , 
   "MunicipalResourceCode" character varying(20) COLLATE pg_catalog."default" NOT NULL , 
   "MunicipalResourceGUID" uuid UNIQUE NOT NULL , 
   "ValueT1" numeric(20,10) NOT NULL , 
   "ValueT2" numeric(20,10) , 
   "ValueT3" numeric(20,10) 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."DeviceValueImportRequest" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."DeviceValueImportResult" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "DeviceValueGUID" uuid UNIQUE , 
   "UpdateDate" date 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."DeviceValueImportResult" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."DeviceValueImportResultError" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "DeviceValueImportTransportGUID" uuid UNIQUE NOT NULL , 
   "ErrorCode" character varying(32) COLLATE pg_catalog."default" NOT NULL , 
   "ErrorDescription" text COLLATE pg_catalog."default" NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."DeviceValueImportResultError" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."HouseExportRequest" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "FIASHouseGuid" uuid UNIQUE NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."HouseExportRequest" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."HouseExportResult" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "HouseGUID" uuid UNIQUE , 
   "HouseUniqueNumber" character varying(31) COLLATE pg_catalog."default" NOT NULL , 
   "ModificationDate" date NOT NULL , 
   "houseType" smallint NOT NULL , 
   "FIASHouseGuid" uuid UNIQUE NOT NULL , 
   "OKTMO" character varying(11) COLLATE pg_catalog."default" , 
   "OlsonTZCode" character varying(20) COLLATE pg_catalog."default" , 
   "OlsonTZGUID" uuid UNIQUE , 
   "CadastralNumber" character varying(255) COLLATE pg_catalog."default" , 
   "TerminationDate" date , 
   "AnnulmentReasonCode" character varying(20) COLLATE pg_catalog."default" , 
   "AnnulmentReasonGUID" uuid UNIQUE , 
   "AnnulmentInfo" character varying(1024) COLLATE pg_catalog."default" , 
   "MultipleHousesAddress" bool 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."HouseExportResult" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."HouseExportResultBlock" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "HouseExportTransportGUID" uuid UNIQUE NOT NULL , 
   "BlockGUID" uuid UNIQUE NOT NULL , 
   "BlockUniqueNumber" character varying(31) COLLATE pg_catalog."default" NOT NULL , 
   "ModificationDate" date NOT NULL , 
   "blockType" smallint NOT NULL , 
   "BlockNum" character varying(255) COLLATE pg_catalog."default" NOT NULL , 
   "TotalArea" numeric(20,10) , 
   "ResidentPremiseTypeCode" character varying(20) COLLATE pg_catalog."default" , 
   "ResidentPremiseTypeGUID" uuid UNIQUE , 
   "CadastralNumber" character varying(255) COLLATE pg_catalog."default" , 
   "TerminationDate" date , 
   "AnnulmentReasonCode" character varying(20) COLLATE pg_catalog."default" , 
   "AnnulmentReasonGUID" uuid UNIQUE , 
   "AnnulmentInfo" character varying(1024) COLLATE pg_catalog."default" , 
   "InformationConfirmed" bool 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."HouseExportResultBlock" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."HouseExportResultEntrance" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "HouseExportTransportGUID" uuid UNIQUE NOT NULL , 
   "EntranceGUID" uuid UNIQUE NOT NULL , 
   "ModificationDate" date NOT NULL , 
   "EntranceNum" character varying(255) COLLATE pg_catalog."default" , 
   "TerminationDate" date , 
   "AnnulmentReasonCode" character varying(20) COLLATE pg_catalog."default" , 
   "AnnulmentReasonGUID" uuid UNIQUE , 
   "AnnulmentInfo" character varying(1024) COLLATE pg_catalog."default" , 
   "InformationConfirmed" bool 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."HouseExportResultEntrance" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."HouseExportResultLivingRoom" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "HouseExportTransportGUID" uuid UNIQUE NOT NULL , 
   "HouseExportPremiseTransportGUID" uuid UNIQUE , 
   "HouseExportBlockTransportGUID" uuid UNIQUE , 
   "LivingRoomGUID" uuid UNIQUE NOT NULL , 
   "LivingRoomUniqueNumber" character varying(31) COLLATE pg_catalog."default" NOT NULL , 
   "ModificationDate" date NOT NULL , 
   "RoomNumber" character varying(255) COLLATE pg_catalog."default" , 
   "Square" numeric(20,10) , 
   "CadastralNumber" character varying(255) COLLATE pg_catalog."default" , 
   "TerminationDate" date , 
   "AnnulmentReasonCode" character varying(20) COLLATE pg_catalog."default" , 
   "AnnulmentReasonGUID" uuid UNIQUE , 
   "AnnulmentInfo" character varying(1024) COLLATE pg_catalog."default" , 
   "InformationConfirmed" bool 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."HouseExportResultLivingRoom" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."HouseExportResultPremise" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "HouseExportTransportGUID" uuid UNIQUE NOT NULL , 
   "HouseExportEntranceTransportGUID" uuid UNIQUE , 
   "PremisesGUID" uuid UNIQUE NOT NULL , 
   "PremisesUniqueNumber" character varying(31) COLLATE pg_catalog."default" NOT NULL , 
   "ModificationDate" date NOT NULL , 
   "premiseType" smallint NOT NULL , 
   "PremisesNum" character varying(255) COLLATE pg_catalog."default" , 
   "TotalArea" numeric(20,10) , 
   "ResidentPremiseTypeCode" character varying(20) COLLATE pg_catalog."default" , 
   "ResidentPremiseTypeGUID" uuid UNIQUE , 
   "CadastralNumber" character varying(255) COLLATE pg_catalog."default" , 
   "TerminationDate" date , 
   "AnnulmentReasonCode" character varying(20) COLLATE pg_catalog."default" , 
   "AnnulmentReasonGUID" uuid UNIQUE , 
   "AnnulmentInfo" character varying(1024) COLLATE pg_catalog."default" , 
   "InformationConfirmed" bool 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."HouseExportResultPremise" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."HouseImportRequest" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "HouseGUID" uuid UNIQUE , 
   "houseType" smallint NOT NULL , 
   "FIASHouseGuid" uuid UNIQUE NOT NULL , 
   "OKTMO" character varying(11) COLLATE pg_catalog."default" , 
   "OlsonTZCode" character varying(20) COLLATE pg_catalog."default" , 
   "OlsonTZGUID" uuid UNIQUE , 
   "CadastralNumber" character varying(255) COLLATE pg_catalog."default" , 
   "InheritMissingValues" bool , 
   "MultipleHousesAddress" bool 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."HouseImportRequest" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."HouseImportRequestBlock" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "HouseImportTransportGUID" uuid UNIQUE NOT NULL , 
   "BlockGUID" uuid UNIQUE , 
   "blockType" smallint NOT NULL , 
   "BlockNum" character varying(255) COLLATE pg_catalog."default" NOT NULL , 
   "TotalArea" numeric(20,10) , 
   "ResidentPremiseTypeCode" character varying(20) COLLATE pg_catalog."default" , 
   "ResidentPremiseTypeGUID" uuid UNIQUE , 
   "CadastralNumber" character varying(255) COLLATE pg_catalog."default" , 
   "AnnulmentReasonCode" character varying(20) COLLATE pg_catalog."default" , 
   "AnnulmentReasonGUID" uuid UNIQUE , 
   "AnnulmentInfo" character varying(1024) COLLATE pg_catalog."default" 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."HouseImportRequestBlock" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."HouseImportRequestEntrance" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "HouseImportTransportGUID" uuid UNIQUE NOT NULL , 
   "EntranceGUID" uuid UNIQUE , 
   "EntranceNum" character varying(255) COLLATE pg_catalog."default" NOT NULL , 
   "AnnulmentReasonCode" character varying(20) COLLATE pg_catalog."default" , 
   "AnnulmentReasonGUID" uuid UNIQUE , 
   "AnnulmentInfo" character varying(1024) COLLATE pg_catalog."default" 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."HouseImportRequestEntrance" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."HouseImportRequestLivingRoom" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "HouseImportTransportGUID" uuid UNIQUE NOT NULL , 
   "HouseImportPremiseTransportGUID" uuid UNIQUE , 
   "HouseImportBlockTransportGUID" uuid UNIQUE , 
   "LivingRoomGUID" uuid UNIQUE , 
   "RoomNumber" character varying(255) COLLATE pg_catalog."default" NOT NULL , 
   "Square" numeric(20,10) , 
   "CadastralNumber" character varying(255) COLLATE pg_catalog."default" , 
   "AnnulmentReasonCode" character varying(20) COLLATE pg_catalog."default" , 
   "AnnulmentReasonGUID" uuid UNIQUE , 
   "AnnulmentInfo" character varying(1024) COLLATE pg_catalog."default" 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."HouseImportRequestLivingRoom" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."HouseImportRequestPremise" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "HouseImportTransportGUID" uuid UNIQUE NOT NULL , 
   "HouseImportEntranceTransportGUID" uuid UNIQUE , 
   "PremisesGUID" uuid UNIQUE , 
   "premiseType" smallint NOT NULL , 
   "PremisesNum" character varying(255) COLLATE pg_catalog."default" NOT NULL , 
   "TotalArea" numeric(20,10) , 
   "ResidentPremiseTypeCode" character varying(20) COLLATE pg_catalog."default" , 
   "ResidentPremiseTypeGUID" uuid UNIQUE , 
   "CadastralNumber" character varying(255) COLLATE pg_catalog."default" , 
   "AnnulmentReasonCode" character varying(20) COLLATE pg_catalog."default" , 
   "AnnulmentReasonGUID" uuid UNIQUE , 
   "AnnulmentInfo" character varying(1024) COLLATE pg_catalog."default" 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."HouseImportRequestPremise" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."HouseImportResult" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "HouseGUID" uuid UNIQUE , 
   "HouseUniqueNumber" character varying(31) COLLATE pg_catalog."default" , 
   "UpdateDate" date 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."HouseImportResult" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."HouseImportResultBlock" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "HouseImportTransportGUID" uuid UNIQUE NOT NULL , 
   "BlockGUID" uuid UNIQUE , 
   "BlockUniqueNumber" character varying(31) COLLATE pg_catalog."default" , 
   "UpdateDate" date 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."HouseImportResultBlock" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."HouseImportResultBlockError" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "HouseImportBlockTransportGUID" uuid UNIQUE NOT NULL , 
   "ErrorCode" character varying(32) COLLATE pg_catalog."default" NOT NULL , 
   "ErrorDescription" text COLLATE pg_catalog."default" NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."HouseImportResultBlockError" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."HouseImportResultEntrance" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "HouseImportTransportGUID" uuid UNIQUE NOT NULL , 
   "EntranceGUID" uuid UNIQUE , 
   "UpdateDate" date 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."HouseImportResultEntrance" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."HouseImportResultEntranceError" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "HouseImportEntranceTransportGUID" uuid UNIQUE NOT NULL , 
   "ErrorCode" character varying(32) COLLATE pg_catalog."default" NOT NULL , 
   "ErrorDescription" text COLLATE pg_catalog."default" NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."HouseImportResultEntranceError" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."HouseImportResultError" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "HouseImportTransportGUID" uuid UNIQUE NOT NULL , 
   "ErrorCode" character varying(32) COLLATE pg_catalog."default" NOT NULL , 
   "ErrorDescription" text COLLATE pg_catalog."default" NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."HouseImportResultError" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."HouseImportResultLivingRoom" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "HouseImportTransportGUID" uuid UNIQUE NOT NULL , 
   "LivingRoomGUID" uuid UNIQUE , 
   "LivingRoomUniqueNumber" character varying(31) COLLATE pg_catalog."default" , 
   "UpdateDate" date 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."HouseImportResultLivingRoom" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."HouseImportResultLivingRoomError" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "HouseImportLivingRoomTransportGUID" uuid UNIQUE NOT NULL , 
   "ErrorCode" character varying(32) COLLATE pg_catalog."default" NOT NULL , 
   "ErrorDescription" text COLLATE pg_catalog."default" NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."HouseImportResultLivingRoomError" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."HouseImportResultPremise" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "HouseImportTransportGUID" uuid UNIQUE NOT NULL , 
   "PremisesGUID" uuid UNIQUE , 
   "PremisesUniqueNumber" character varying(31) COLLATE pg_catalog."default" , 
   "UpdateDate" date 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."HouseImportResultPremise" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."HouseImportResultPremiseError" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "HouseImportPremiseTransportGUID" uuid UNIQUE NOT NULL , 
   "ErrorCode" character varying(32) COLLATE pg_catalog."default" NOT NULL , 
   "ErrorDescription" text COLLATE pg_catalog."default" NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."HouseImportResultPremiseError" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."NotificationImportDeleteRequest" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "NotificationGUID" uuid UNIQUE NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."NotificationImportDeleteRequest" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."NotificationImportRequest" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "NotificationGUID" uuid UNIQUE , 
   "Topic" character varying(200) COLLATE pg_catalog."default" NOT NULL , 
   "Content" character varying(2000) COLLATE pg_catalog."default" , 
   "IsImportant" bool NOT NULL , 
   "StartDate" date , 
   "EndDate" date 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."NotificationImportRequest" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."NotificationImportRequestAccountDebt" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "NotificationImportTransportGUID" uuid UNIQUE NOT NULL , 
   "UnifiedAccountNumber" character varying(10) COLLATE pg_catalog."default" NOT NULL , 
   "TotalDebt" numeric(20,10) NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."NotificationImportRequestAccountDebt" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."NotificationImportResult" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "NotificationGUID" uuid UNIQUE , 
   "UpdateDate" date 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."NotificationImportResult" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."NotificationImportResultError" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "NotificationImportTransportGUID" uuid UNIQUE NOT NULL , 
   "ErrorCode" character varying(32) COLLATE pg_catalog."default" NOT NULL , 
   "ErrorDescription" text COLLATE pg_catalog."default" NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."NotificationImportResultError" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."NsiExportRequest" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "RegistryNumber" integer NOT NULL , 
   "ModifiedAfter" date 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."NsiExportRequest" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."NsiExportResult" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "RegistryNumber" integer NOT NULL , 
   "Code" character varying(20) COLLATE pg_catalog."default" NOT NULL , 
   "GUID" uuid UNIQUE NOT NULL , 
   "Modified" date NOT NULL , 
   "IsActual" bool NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."NsiExportResult" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."NsiExportResultField" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "NsiExportTransportGUID" uuid UNIQUE NOT NULL , 
   "Name" character varying(200) COLLATE pg_catalog."default" NOT NULL , 
   "Value" character varying(1024) COLLATE pg_catalog."default" NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."NsiExportResultField" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."OrderImportCancellationRequest" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "OrderID" character varying(32) COLLATE pg_catalog."default" NOT NULL , 
   "CancellationDate" date NOT NULL , 
   "Comment" character varying(210) COLLATE pg_catalog."default" 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."OrderImportCancellationRequest" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."OrderImportRequest" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "OrderDate" date NOT NULL , 
   "AmountRub" numeric(20,10) NOT NULL , 
   "Year" smallint , 
   "Month" smallint , 
   "ServiceID" character varying(13) COLLATE pg_catalog."default" , 
   "PaymentDocumentID" character varying(18) COLLATE pg_catalog."default" 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."OrderImportRequest" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."OrderImportResult" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "OrderGUID" uuid UNIQUE , 
   "OrderID" character varying(32) COLLATE pg_catalog."default" , 
   "UpdateDate" date 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."OrderImportResult" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."OrderImportResultError" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "OrderImportTransportGUID" uuid UNIQUE NOT NULL , 
   "ErrorCode" character varying(32) COLLATE pg_catalog."default" NOT NULL , 
   "ErrorDescription" text COLLATE pg_catalog."default" NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."OrderImportResultError" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."OrganizationExportRequest" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "LastEditingDateFrom" date 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."OrganizationExportRequest" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."OrganizationExportRequestData" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "OrganizationExportTransportGUID" uuid UNIQUE NOT NULL , 
   "orgType" smallint NOT NULL , 
   "OrgGUID" uuid UNIQUE , 
   "OrgVersionGUID" uuid UNIQUE , 
   "OGRN" character varying(15) COLLATE pg_catalog."default" , 
   "KPP" character varying(9) COLLATE pg_catalog."default" , 
   "OrgPPAGUID" uuid UNIQUE , 
   "IsRegistered" bool 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."OrganizationExportRequestData" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."OrganizationExportResult" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "orgType" smallint NOT NULL , 
   "OrgGUID" uuid UNIQUE NOT NULL , 
   "OrgVersionGUID" uuid UNIQUE NOT NULL , 
   "RegistryOrganizationStatus" character varying(1) COLLATE pg_catalog."default" , 
   "OrgPPAGUID" uuid UNIQUE , 
   "IsRegistered" bool , 
   "IsVersionActual" bool NOT NULL , 
   "VersionLastEditingDate" date NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."OrganizationExportResult" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."OrganizationExportResultEntp" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "FirstName" character varying(255) COLLATE pg_catalog."default" NOT NULL , 
   "Surname" character varying(255) COLLATE pg_catalog."default" NOT NULL , 
   "Patronymic" character varying(255) COLLATE pg_catalog."default" , 
   "Sex" character varying(1) COLLATE pg_catalog."default" , 
   "OGRN" character varying(15) COLLATE pg_catalog."default" NOT NULL , 
   "INN" character varying(12) COLLATE pg_catalog."default" , 
   "StateRegistrationDate" date 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."OrganizationExportResultEntp" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."OrganizationExportResultLegal" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "FullName" character varying(4000) COLLATE pg_catalog."default" NOT NULL , 
   "ShortName" character varying(500) COLLATE pg_catalog."default" , 
   "CommercialName" character varying(255) COLLATE pg_catalog."default" , 
   "OGRN" character varying(13) COLLATE pg_catalog."default" NOT NULL , 
   "INN" character varying(10) COLLATE pg_catalog."default" , 
   "KPP" character varying(9) COLLATE pg_catalog."default" , 
   "OKOPF" character varying(5) COLLATE pg_catalog."default" , 
   "StateRegistrationDate" date , 
   "ActivityEndDate" date , 
   "Address" text COLLATE pg_catalog."default" , 
   "FIASHouseGuid" uuid UNIQUE 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."OrganizationExportResultLegal" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."OrganizationExportResultRole" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "OrganizationExportTransportGUID" uuid UNIQUE NOT NULL , 
   "OrganizationRoleCode" character varying(20) COLLATE pg_catalog."default" NOT NULL , 
   "OrganizationRoleGUID" uuid UNIQUE NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."OrganizationExportResultRole" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."PaymentExportRequest" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "Month" smallint , 
   "Year" smallint , 
   "FIASHouseGuid" uuid UNIQUE 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."PaymentExportRequest" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."PaymentExportRequestAccount" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "PaymentExportTransportGUID" uuid UNIQUE NOT NULL , 
   "AccountGUID" uuid UNIQUE , 
   "AccountNumber" character varying(30) COLLATE pg_catalog."default" , 
   "UnifiedAccountNumber" character varying(10) COLLATE pg_catalog."default" , 
   "ServiceID" character varying(13) COLLATE pg_catalog."default" 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."PaymentExportRequestAccount" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."PaymentExportRequestDocument" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "PaymentExportTransportGUID" uuid UNIQUE NOT NULL , 
   "PaymentDocumentID" character varying(18) COLLATE pg_catalog."default" , 
   "PaymentDocumentNumber" character varying(30) COLLATE pg_catalog."default" 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."PaymentExportRequestDocument" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."PaymentExportResult" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "PaymentDocumentID" character varying(18) COLLATE pg_catalog."default" NOT NULL , 
   "PaymentDocumentNumber" character varying(30) COLLATE pg_catalog."default" , 
   "AccountGUID" uuid UNIQUE NOT NULL , 
   "Withdraw" bool NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."PaymentExportResult" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."PaymentImportRequest" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "PaymentDocumentID" character varying(18) COLLATE pg_catalog."default" , 
   "PaymentDocumentNumber" character varying(30) COLLATE pg_catalog."default" , 
   "AccountGUID" uuid UNIQUE NOT NULL , 
   "Month" smallint NOT NULL , 
   "Year" smallint NOT NULL , 
   "ConfirmAmountsCorrect" bool , 
   "BankBIK" character varying(9) COLLATE pg_catalog."default" NOT NULL , 
   "OperatingAccountNumber" character varying(20) COLLATE pg_catalog."default" NOT NULL , 
   "DebtPreviousPeriods" numeric(20,10) , 
   "AdvanceBllingPeriod" numeric(20,10) , 
   "TotalPiecemealPaymentSum" numeric(20,10) , 
   "PaymentsTaken" smallint , 
   "AdditionalInformation" character varying(1000) COLLATE pg_catalog."default" , 
   "TotalPayableByPD" numeric(20,10) , 
   "TotalPayableByChargeInfo" numeric(20,10) , 
   "TotalPayableByPDWithDebtAndAdvance" numeric(20,10) , 
   "TotalByPenaltiesAndCourtCosts" numeric(20,10) , 
   "PaidCash" numeric(20,10) , 
   "DateOfLastReceivedPayment" date , 
   "LimitIndex" numeric(20,10) , 
   "SubsidiesCompensationSocialSupport" numeric(20,10) 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."PaymentImportRequest" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."PaymentImportRequestChargesMunicipalService" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "PaymentImportTransportGUID" uuid UNIQUE NOT NULL , 
   "MainMunicipalServiceCode" character varying(20) COLLATE pg_catalog."default" NOT NULL , 
   "MainMunicipalServiceGUID" uuid UNIQUE NOT NULL , 
   "Rate" numeric(20,10) NOT NULL , 
   "TotalPayable" numeric(20,10) NOT NULL , 
   "AccountingPeriodTotal" numeric(20,10) , 
   "CalcExplanation" character varying(4000) COLLATE pg_catalog."default" , 
   "MoneyRecalculation" numeric(20,10) , 
   "MoneyDiscount" numeric(20,10) , 
   "VolumeI" numeric(20,10) , 
   "VolumeO" numeric(20,10) , 
   "DeterminingMethodI" character varying(1) COLLATE pg_catalog."default" , 
   "DeterminingMethodO" character varying(1) COLLATE pg_catalog."default" , 
   "RecalculationReason" character varying(500) COLLATE pg_catalog."default" , 
   "Sum" numeric(20,10) , 
   "IndividualConsumptionPayable" numeric(20,10) , 
   "CommunalConsumptionPayable" numeric(20,10) , 
   "MultiplyingFactorRatio" numeric(20,10) , 
   "MultiplyingFactorAmount" numeric(20,10) , 
   "AmountI" numeric(20,10) , 
   "AmountO" numeric(20,10) , 
   "DebtPreviousPeriodsOrAdvanceBillingPeriod" numeric(20,10) , 
   "Penalties" numeric(20,10) , 
   "StateFees" numeric(20,10) , 
   "CourtCosts" numeric(20,10) , 
   "TotalPayableOverall" numeric(20,10) 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."PaymentImportRequestChargesMunicipalService" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."PaymentImportRequestChargesMunicipalServiceNorm" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "IndividualConsumptionCurrentValue" numeric(20,10) , 
   "HouseOverallNeedsCurrentValue" numeric(20,10) , 
   "HouseTotalIndividualConsumption" numeric(20,10) , 
   "HouseTotalHouseOverallNeeds" numeric(20,10) , 
   "HouseOverallNeedsNorm" numeric(20,10) , 
   "IndividualConsumptionNorm" numeric(20,10) 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."PaymentImportRequestChargesMunicipalServiceNorm" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."PaymentImportRequestDebtMunicipalService" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "PaymentImportTransportGUID" uuid UNIQUE NOT NULL , 
   "MainMunicipalServiceCode" character varying(20) COLLATE pg_catalog."default" NOT NULL , 
   "MainMunicipalServiceGUID" uuid UNIQUE NOT NULL , 
   "Month" smallint NOT NULL , 
   "Year" smallint NOT NULL , 
   "TotalPayable" numeric(20,10) NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."PaymentImportRequestDebtMunicipalService" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."PaymentImportRequestPenaltyAndCourtCost" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "PaymentImportTransportGUID" uuid UNIQUE NOT NULL , 
   "PenaltyAndCourtCostCode" character varying(20) COLLATE pg_catalog."default" NOT NULL , 
   "PenaltyAndCourtCostGUID" uuid UNIQUE NOT NULL , 
   "Cause" character varying(1000) COLLATE pg_catalog."default" NOT NULL , 
   "TotalPayable" numeric(20,10) NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."PaymentImportRequestPenaltyAndCourtCost" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."PaymentImportResult" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "PaymentDocumentGUID" uuid UNIQUE , 
   "PaymentDocumentID" character varying(18) COLLATE pg_catalog."default" , 
   "UpdateDate" date 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."PaymentImportResult" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."PaymentImportResultError" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "PaymentImportTransportGUID" uuid UNIQUE NOT NULL , 
   "ErrorCode" character varying(32) COLLATE pg_catalog."default" NOT NULL , 
   "ErrorDescription" text COLLATE pg_catalog."default" NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."PaymentImportResultError" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."PaymentImportWithdrawRequest" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "PaymentDocumentID" character varying(18) COLLATE pg_catalog."default" NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."PaymentImportWithdrawRequest" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."SettlementImportAnnulmentRequest" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "SettlementGUID" uuid UNIQUE NOT NULL , 
   "ReasonOfAnnulment" character varying(2000) COLLATE pg_catalog."default" NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."SettlementImportAnnulmentRequest" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."SettlementImportRequest" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "SettlementGUID" uuid UNIQUE , 
   "ContractGUID" uuid UNIQUE NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."SettlementImportRequest" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."SettlementImportRequestPeriod" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "SettlementImportTransportGUID" uuid UNIQUE NOT NULL , 
   "Month" smallint NOT NULL , 
   "Year" smallint NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."SettlementImportRequestPeriod" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."SettlementImportRequestPeriodAnnulment" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "ReasonOfAnnulment" character varying(2000) COLLATE pg_catalog."default" NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."SettlementImportRequestPeriodAnnulment" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."SettlementImportRequestPeriodInfo" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "Credted" numeric(20,10) NOT NULL , 
   "Receipt" numeric(20,10) NOT NULL , 
   "Debts" numeric(20,10) NOT NULL , 
   "Overpayment" numeric(20,10) NOT NULL , 
   "Paid" numeric(20,10) 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."SettlementImportRequestPeriodInfo" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."SettlementImportResult" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "SettlementGUID" uuid UNIQUE , 
   "UpdateDate" date 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."SettlementImportResult" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."SettlementImportResultError" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid UNIQUE PRIMARY KEY , 
   "SettlementImportTransportGUID" uuid UNIQUE NOT NULL , 
   "ErrorCode" character varying(32) COLLATE pg_catalog."default" NOT NULL , 
   "ErrorDescription" text COLLATE pg_catalog."default" NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."SettlementImportResultError" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."SysOperation" 
( 
   "OperationId" integer PRIMARY KEY , 
   "OperationName" character varying(128) COLLATE pg_catalog."default" NOT NULL , 
   "Name" character varying(1024) COLLATE pg_catalog."default" NOT NULL , 
   "PacketSize" integer NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."SysOperation" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."SysParams" 
( 
   "Id" integer PRIMARY KEY , 
   "VersionNumber" character varying(32) COLLATE pg_catalog."default" NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."SysParams" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."SysRegistry" 
( 
   "RegistryId" integer PRIMARY KEY , 
   "RegistryName" character varying(128) COLLATE pg_catalog."default" NOT NULL , 
   "Name" character varying(1024) COLLATE pg_catalog."default" NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."SysRegistry" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."SysTransaction" 
( 
   "TransactionGUID" uuid UNIQUE PRIMARY KEY , 
   "ListGUID" uuid UNIQUE , 
   "ClientId" character varying(32) COLLATE pg_catalog."default" NOT NULL , 
   "OperationId" integer NOT NULL , 
   "StartDate" date NOT NULL , 
   "EndDate" date , 
   "StatusId" integer NOT NULL , 
   "LastExecutionDate" date , 
   "NextExecutionDate" date , 
   "ResultId" integer , 
   "ErrorCode" character varying(32) COLLATE pg_catalog."default" , 
   "ErrorDescription" character varying(4000) COLLATE pg_catalog."default" 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."SysTransaction" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."SysTransactionLog" 
( 
   "TransactionLogId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "LogDate" date NOT NULL , 
   "LogData" character varying(1024) COLLATE pg_catalog."default" , 
   "ErrorCode" character varying(32) COLLATE pg_catalog."default" , 
   "ErrorDescription" text COLLATE pg_catalog."default" , 
   "ErrorStackTrace" text COLLATE pg_catalog."default" 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."SysTransactionLog" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."SysTransactionObject" 
( 
   "TransactionObjectId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" NOT NULL , 
   "comment" text COLLATE pg_catalog."default" , 
   "operation" integer NOT NULL , 
   "group" integer , 
   "param" text COLLATE pg_catalog."default" 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."SysTransactionObject" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."SysTransactionObjectError" 
( 
   "TransactionObjectErrorId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" NOT NULL , 
   "errorCode" character varying(32) COLLATE pg_catalog."default" NOT NULL , 
   "errorDescription" text COLLATE pg_catalog."default" 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."SysTransactionObjectError" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."SysTransactionParam" 
( 
   "TransactionParamId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "ParamName" character varying(128) COLLATE pg_catalog."default" NOT NULL , 
   "ParamValue" character varying(1024) COLLATE pg_catalog."default" 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."SysTransactionParam" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."SysTransactionState2" 
( 
   "TransactionStateId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "StateGUID" uuid UNIQUE NOT NULL , 
   "AsyncStateGUID" uuid UNIQUE , 
   "TransactionGUID" uuid UNIQUE NOT NULL , 
   "OperationId" integer NOT NULL , 
   "StateTypeId" smallint NOT NULL , 
   "StateDate" date NOT NULL , 
   "StateData" text COLLATE pg_catalog."default" 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."SysTransactionState2" OWNER to "gis_hcs";
 
CREATE TABLE "gis_hcs"."SysTransactionStateType" 
( 
   "TransactionStateTypeId" smallint PRIMARY KEY , 
   "TransactionStateTypeName" character varying(128) COLLATE pg_catalog."default" NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "gis_hcs"."SysTransactionStateType" OWNER to "gis_hcs";

