//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Core.Context
{
    using Microsoft.EntityFrameworkCore;
    using Server.Core.Model;

    public partial class EntityContext : DbContext
    {
        public virtual DbSet<BUILD> BUILD { get; set; }//;
        public virtual DbSet<Server.Core.Model.NSI_STREET> NSI_STREET { get; set; }
        public virtual DbSet<NSI_STREET_TYPE> NSI_STREET_TYPE { get; set; }

        public virtual DbSet<NSI_VILLAGE> NSI_VILLAGE { get; set; }
        public virtual DbSet<NSI_VILLAGE_TYPE> NSI_VILLAGE_TYPE { get; set; }


    }
}
