//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Core.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class CHAT : IEntityObject, IEntityLog
    {
        #region Columns
        long IEntityObject.Id { get { return CHAT_ID; } }//;
        [KeyAttribute()]
        public long CHAT_ID { get; set; }//;
        public string TITLE { get; set; }//;
        public string DESCRIPTION { get; set; }//;
        public string MESSAGE { get; set; }//;
        public string USERS { get; set; }//;
        public System.Nullable<int> OWNER_ID { get; set; }//;
        public System.Nullable<int> STABLE_ID { get; set; }//;
        public System.Nullable<long> ID { get; set; }//;
        public System.Nullable<System.DateTime> CRT_DATE { get; set; }//;
        public System.Nullable<System.DateTime> MFY_DATE { get; set; }//;
        public System.Nullable<int> MFY_SUSER_ID { get; set; }//;
        #endregion
        #region Navigation - parents
        // 
        // FK_SYS_USER_CHAT   [SYS_USER.SUSER_ID]
        [ForeignKey("OWNER_ID")]
        public virtual SYS_USER SYS_USER { get; set; }//;
        #endregion
    }
}
