//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Core.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    
    public partial class DEAL_EXT : IEntityObject, IEntityLog, IEntityPeriod
    {
        
        #region Columns
        long IEntityObject.Id { get { return DEAL_EXT_ID; } }//;
        
        [KeyAttribute()]
        public long DEAL_EXT_ID { get; set; }//;
        
        public long DEAL_ID { get; set; }//;
        
        public System.DateTime DATE_BEG { get; set; }//;
        
        public System.Nullable<System.DateTime> DATE_END { get; set; }//;
        
        public System.Nullable<long> BUYER_ID { get; set; }//;
        
        public System.Nullable<int> NPENALTY_ID { get; set; }//;
        
        public System.Nullable<long> PARTNER_RS_ID { get; set; }//;
        
        public System.Nullable<int> OKONH { get; set; }//;
        
        public string OKVED { get; set; }//;
        
        public System.Nullable<long> SIGNATORY_ID { get; set; }//;
        
        public System.Nullable<int> PENALTY_PERCENT { get; set; }//;
        
        public System.Nullable<int> DAY_OPL { get; set; }//;
        
        public System.Nullable<long> SELLER_ID { get; set; }//;
        
        public System.Nullable<long> PAYER_ID { get; set; }//;
        
        public System.Nullable<long> CONSIGNEE_ID { get; set; }//;
        
        public string COMMENT { get; set; }//;
        
        public System.Nullable<System.DateTime> CONTRACT_BEG { get; set; }//;
        
        public System.Nullable<System.DateTime> CONTRACT_END { get; set; }//;
        
        public System.Nullable<System.DateTime> CRT_DATE { get; set; }//;
        
        public System.Nullable<System.DateTime> MFY_DATE { get; set; }//;
        
        public System.Nullable<int> MFY_SUSER_ID { get; set; }//;
        
        public System.Nullable<int> STATUS { get; set; }//;
        
        public System.Nullable<long> BUILD_DELIVERY_ID { get; set; }//;
        
        public string FLAT_DELIVERY { get; set; }//;
        
        public System.Nullable<long> SELLER_RS_ID { get; set; }//;
        #endregion
        
        #region Navigation - parents
        // FK_DEAL_EXT_DEAL
        [InverseProperty("DEAL_ID")]
        public virtual DEAL DEAL { get; set; }//;
        
        // FK_DEAL_EXT_PARTNER1
        [InverseProperty("SELLER_ID")]
        public virtual PARTNER PARTNER { get; set; }//;
        
        // FK_DEAL_EXT_PARTNER2
        [InverseProperty("PAYER_ID")]
        public virtual PARTNER PARTNER1 { get; set; }//;
        
        // FK_DEAL_EXT_PARTNER3
        [InverseProperty("CONSIGNEE_ID")]
        public virtual PARTNER PARTNER2 { get; set; }//;
        
        // FK_DEAL_EXT_PARTNER_1
        [InverseProperty("BUYER_ID")]
        public virtual PARTNER PARTNER3 { get; set; }//;
        #endregion
    }
}
