//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Core.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    
    public partial class DOCUMENT : IEntityObject, IEntityLog
    {
        
        #region Columns
        long IEntityObject.Id { get { return DOCUMENT_ID; } }//;
        
        [KeyAttribute()]
        public long DOCUMENT_ID { get; set; }//;
        
        public System.Nullable<int> NDOCUMENT_ID { get; set; }//;
        
        public System.Nullable<long> PARTNER_ID { get; set; }//;
        
        public System.Nullable<long> DEAL_ID { get; set; }//;
        
        public System.Nullable<long> LIST_PAYMENT_ID { get; set; }//;
        
        public string DOCUMENT_NUM { get; set; }//;
        
        public string OLD_NUM { get; set; }//;
        
        public string DETAIL { get; set; }//;
        
        public string DESTINATION { get; set; }//;
        
        public System.Nullable<int> NREAZON_ID { get; set; }//;
        
        public System.Nullable<System.DateTime> DATE_BEG { get; set; }//;
        
        public System.Nullable<int> NDOCUMENT_STATUS_ID { get; set; }//;
        
        public System.Nullable<int> NPRODUCT_ID { get; set; }//;
        
        public System.Nullable<long> FACILITY_ID { get; set; }//;
        
        public System.Nullable<int> NDOCUMENT_IMPORTANT_ID { get; set; }//;
        
        public string URL_CALC { get; set; }//;
        
        public string DOCUMENT_NAME { get; set; }//;
        
        public string COMMENT { get; set; }//;
        
        public System.Nullable<System.DateTime> CRT_DATE { get; set; }//;
        
        public System.Nullable<System.DateTime> MFY_DATE { get; set; }//;
        
        public System.Nullable<int> MFY_SUSER_ID { get; set; }//;
        
        public System.Nullable<System.DateTime> DATE_END { get; set; }//;
        
        public System.Nullable<long> BANK_TRANSACTION_ID { get; set; }//;
        
        public System.Nullable<int> NDOCUMENT_SUBTYPE_ID { get; set; }//;
        
        public System.Nullable<long> CALC_ITEM_ID { get; set; }//;
        
        public System.Nullable<long> CURR_STATE_ID { get; set; }//;
        
        public System.Nullable<long> OWNER_ID { get; set; }//;
        
        public System.Nullable<long> CURR_EVENT_ID { get; set; }//;
        
        public System.Nullable<long> PROCESS_ID { get; set; }//;
        
        public System.Nullable<int> NTAG_ID { get; set; }//;
        
        public System.Nullable<long> CONS_PARENT_ID { get; set; }//;
        
        public string DOCUMENT_SERIES { get; set; }//;
        
        public string DOCUMENT_ISSUER { get; set; }//;
        
        public System.Nullable<long> CHARGE_ITEM_ID { get; set; }//;
        
        public System.Nullable<long> CONSUM_ID { get; set; }//;
        
        public System.Nullable<int> NMETOD_GET_ID { get; set; }//;
        
        public System.Nullable<System.DateTime> ACCOUNT_PERIOD { get; set; }//;
        
        public System.Nullable<long> DOCUMENT_NUM_INT { get; set; }//;
        #endregion
        
        #region Navigation - parents
        // FK_DOCUMENT_DEAL
        [InverseProperty("DEAL_ID")]
        public virtual DEAL DEAL { get; set; }//;
        
        // FK_DOCUMENT_DOCUMENT
        [InverseProperty("CONS_PARENT_ID")]
        public virtual DOCUMENT DOCUMENT1 { get; set; }//;
        
        // FK_DOCUMENT_FACILITY
        [InverseProperty("FACILITY_ID")]
        public virtual FACILITY FACILITY { get; set; }//;
        
        // FK_DOCUMENT_NSI_PRODUCT
        [InverseProperty("NPRODUCT_ID")]
        public virtual NSI_PRODUCT NSI_PRODUCT { get; set; }//;
        
        // FK_DOCUMENT_NSI_REAZON
        [InverseProperty("NREAZON_ID")]
        public virtual NSI_REAZON NSI_REAZON { get; set; }//;
        
        // FK_DOCUMENT_NSI_TAG
        [InverseProperty("NTAG_ID")]
        public virtual NSI_TAG NSI_TAG { get; set; }//;
        
        // FK_DOCUMENT_PARTNER
        [InverseProperty("PARTNER_ID")]
        public virtual PARTNER PARTNER { get; set; }//;
        #endregion
        
        #region Navigation - children
        // FK_DOCUMENT_DOCUMENT
        public virtual ICollection<DOCUMENT> DOCUMENT2 { get; set; }//;
        
        // FK_DOCUMENT_ITEM_DOCUMENT
        public virtual ICollection<DOCUMENT_ITEM> DOCUMENT_ITEM { get; set; }//;
        
        // FK_DOCUMENT_RELATION_DOCUMENT
        public virtual ICollection<DOCUMENT_RELATION> DOCUMENT_RELATION { get; set; }//;
        
        // FK_DOCUMENT_STORAGE_DOCUMENT
        public virtual ICollection<DOCUMENT_STORAGE> DOCUMENT_STORAGE { get; set; }//;
        
        // FK_EVENT_DOCUMENT
        public virtual ICollection<EVENT> EVENT { get; set; }//;
        
        // FK_EVENT_STATE_DOCUMENT
        public virtual ICollection<EVENT_STATE> EVENT_STATE { get; set; }//;
        
        // FK_PARTNER_RELATION_DOCUMENT
        public virtual ICollection<PARTNER_RELATION> PARTNER_RELATION { get; set; }//;
        
        // FK_TASK_EXECUTION_DOCUMENT
        public virtual ICollection<TASK_EXECUTION> TASK_EXECUTION { get; set; }//;
        
        // FK_TASK_EXECUTION_DETAIL_DOCUMENT
        public virtual ICollection<TASK_EXECUTION_DETAIL> TASK_EXECUTION_DETAIL { get; set; }//;
        #endregion
        
        #region Constructor
        public DOCUMENT()
        {
            this.DOCUMENT2 = new HashSet<DOCUMENT>();
            this.DOCUMENT_ITEM = new HashSet<DOCUMENT_ITEM>();
            this.DOCUMENT_RELATION = new HashSet<DOCUMENT_RELATION>();
            this.DOCUMENT_STORAGE = new HashSet<DOCUMENT_STORAGE>();
            this.EVENT = new HashSet<EVENT>();
            this.EVENT_STATE = new HashSet<EVENT_STATE>();
            this.PARTNER_RELATION = new HashSet<PARTNER_RELATION>();
            this.TASK_EXECUTION = new HashSet<TASK_EXECUTION>();
            this.TASK_EXECUTION_DETAIL = new HashSet<TASK_EXECUTION_DETAIL>();
        }
        #endregion
    }
}
