//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Core.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class EQUIPMENT_METER : IEntityObject, IEntityLog
    {
        #region Columns
        long IEntityObject.Id { get { return EQUIPMENT_ID; } }//;
        [KeyAttribute()]
        public long EQUIPMENT_ID { get; set; }//;
        public System.Nullable<int> NMETER_ID { get; set; }//;
        public string ZAV_NUM { get; set; }//;
        public System.Nullable<System.DateTime> MANUFACT_DATE { get; set; }//;
        public System.Nullable<System.DateTime> CHECK_DATE { get; set; }//;
        public System.Nullable<System.DateTime> USE_DATE_END { get; set; }//;
        public System.Nullable<int> NMETER_TIMER_ID { get; set; }//;
        public string TIMER_NUM { get; set; }//;
        public System.Nullable<System.DateTime> DATE_EPD { get; set; }//;
        public string EPD { get; set; }//;
        public System.Nullable<long> PARTNER_PERS_ID { get; set; }//;
        public System.Nullable<System.DateTime> CRT_DATE { get; set; }//;
        public System.Nullable<System.DateTime> MFY_DATE { get; set; }//;
        public System.Nullable<int> MFY_SUSER_ID { get; set; }//;
        #endregion
        #region Navigation - parents
        // 
        // FK_EQUIPMENT_METER_NSI_METER   [NSI_METER.NMETER_ID]
        [ForeignKey("NMETER_ID")]
        public virtual NSI_METER NSI_METER { get; set; }//;
        #endregion
    }
}
