//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Core.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class EVENT_SCHEM : IEntityObject, IEntityLog
    {
        #region Columns
        long IEntityObject.Id { get { return EVENT_SCHEM_ID; } }//;
        [KeyAttribute()]
        public long EVENT_SCHEM_ID { get; set; }//;
        public string EVENT_SCHEM_NAME { get; set; }//;
        public long PARENT_ID { get; set; }//;
        public long CHILD_ID { get; set; }//;
        public int NEVENT_SCHEM_ID { get; set; }//;
        public System.Nullable<System.DateTime> CRT_DATE { get; set; }//;
        public System.Nullable<System.DateTime> MFY_DATE { get; set; }//;
        public System.Nullable<int> MFY_SUSER_ID { get; set; }//;
        #endregion
        #region Navigation - parents
        // 
        // FK_EVENT_SCHEM_EVENT   [EVENT.EVENT_ID]
        [ForeignKey("PARENT_ID")]
        public virtual EVENT EVENT { get; set; }//;
        // 
        // FK_EVENT_SCHEM_EVENT1   [EVENT.EVENT_ID]   #1
        [ForeignKey("CHILD_ID")]
        public virtual EVENT EVENT1 { get; set; }//;
        #endregion
    }
}
