//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Core.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class NSI_EVENT_STATE : IEntityObject, IEntityLog
    {
        #region Columns
        long IEntityObject.Id { get { return NEVENT_STATE_ID; } }//;
        [KeyAttribute()]
        public int NEVENT_STATE_ID { get; set; }//;
        public string NEVENT_STATE_NAME { get; set; }//;
        public System.Nullable<System.DateTime> CRT_DATE { get; set; }//;
        public System.Nullable<System.DateTime> MFY_DATE { get; set; }//;
        public System.Nullable<int> MFY_SUSER_ID { get; set; }//;
        public System.Nullable<int> COURIER_CONTROL { get; set; }//;
        #endregion
        #region Navigation - children
        // 
        // FK_DOCUMENT_ACTION_STATE_NSI_ACTION_STATE   [EVENT_STATE.NEVENT_STATE_ID]
        public virtual ICollection<EVENT_STATE> EVENT_STATE { get; set; }//;
        // 
        // FK_SYS_HELP_NSI_EVENT_STATE   [SYS_HELP.NEVENT_STATE_ID]
        public virtual ICollection<SYS_HELP> SYS_HELP { get; set; }//;
        #endregion
        #region Constructor
        public NSI_EVENT_STATE()
        {
            this.EVENT_STATE = new HashSet<EVENT_STATE>();
            this.SYS_HELP = new HashSet<SYS_HELP>();
        }
        #endregion
    }
}
