//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Core.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    
    public partial class NSI_TASK_CONFIG : IEntityObject, IEntityLog
    {
        
        #region Columns
        long IEntityObject.Id { get { return NTASK_CONFIG_ID; } }//;
        
        [KeyAttribute()]
        public int NTASK_CONFIG_ID { get; set; }//;
        
        public string NTASK_CONFIG_NAME { get; set; }//;
        
        public System.Nullable<int> NTASK_ID { get; set; }//;
        
        public string DETAIL { get; set; }//;
        
        public string COMMENT { get; set; }//;
        
        public System.Nullable<short> IS_DEFAULT { get; set; }//;
        
        public System.Nullable<System.DateTime> CRT_DATE { get; set; }//;
        
        public System.Nullable<System.DateTime> MFY_DATE { get; set; }//;
        
        public System.Nullable<int> MFY_SUSER_ID { get; set; }//;
        #endregion
        
        #region Navigation - parents
        // FK_NSI_TASK_CONFIG_NTASK_ID
        [InverseProperty("NTASK_ID")]
        public virtual NSI_TASK NSI_TASK { get; set; }//;
        #endregion
        
        #region Navigation - children
        // FK_TASK_CONFIG_RELATION_NTASK_CONFIG_ID
        public virtual ICollection<TASK_CONFIG_RELATION> TASK_CONFIG_RELATION { get; set; }//;
        #endregion
        
        #region Constructor
        public NSI_TASK_CONFIG()
        {
            this.TASK_CONFIG_RELATION = new HashSet<TASK_CONFIG_RELATION>();
        }
        #endregion
    }
}
