//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Core.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class NSI_METER_PARAM : IEntityObject, IEntityLog
    {
        #region Columns
        long IEntityObject.Id { get { return NMETER_PARAM_ID; } }//;
        [KeyAttribute()]
        public int NMETER_PARAM_ID { get; set; }//;
        public System.Nullable<int> NMETER_ID { get; set; }//;
        public string NMETER_PARAM_NAME { get; set; }//;
        public System.Nullable<int> FORMAT_ALL { get; set; }//;
        public System.Nullable<int> FORMAT_AFTER { get; set; }//;
        public System.Nullable<int> NZONE_ID { get; set; }//;
        public System.Nullable<int> NCALC_ID { get; set; }//;
        public System.Nullable<short> DIRECTION { get; set; }//;
        public System.Nullable<int> NMETER_CONFIG_ID { get; set; }//;
        public System.Nullable<System.DateTime> CRT_DATE { get; set; }//;
        public System.Nullable<System.DateTime> MFY_DATE { get; set; }//;
        public System.Nullable<int> MFY_SUSER_ID { get; set; }//;
        #endregion
        #region Navigation - parents
        // 
        // FK_NSI_METER_PARAM_NSI_PRODUCT_KIND   [NSI_CALC.NCALC_ID]
        [ForeignKey("NCALC_ID")]
        public virtual NSI_CALC NSI_CALC { get; set; }//;
        // 
        // FK_NSI_METER_PARAM_NSI_METER   [NSI_METER.NMETER_ID]
        [ForeignKey("NMETER_ID")]
        public virtual NSI_METER NSI_METER { get; set; }//;
        // 
        // FK_NSI_METER_PARAM_NSI_METER_CONFIG   [NSI_METER_CONFIG.NMETER_CONFIG_ID]
        [ForeignKey("NMETER_CONFIG_ID")]
        public virtual NSI_METER_CONFIG NSI_METER_CONFIG { get; set; }//;
        // 
        // FK_NSI_METER_PARAM_NSI_ZONE   [NSI_ZONE.NZONE_ID]
        [ForeignKey("NZONE_ID")]
        public virtual NSI_ZONE NSI_ZONE { get; set; }//;
        #endregion
    }
}
