//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Core.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class NSI_TASK_JOB : IEntityObject, IEntityLog, IEntityPeriod
    {
        #region Columns
        long IEntityObject.Id { get { return NTASK_JOB_ID; } }//;
        [KeyAttribute()]
        public int NTASK_JOB_ID { get; set; }//;
        public System.DateTime DATE_BEG { get; set; }//;
        public System.Nullable<System.DateTime> DATE_END { get; set; }//;
        public System.Nullable<int> THREAD_COUNT { get; set; }//;
        public System.Nullable<short> THREAD_AUTO { get; set; }//;
        public string CRON { get; set; }//;
        public string NTASK_JOB_NAME { get; set; }//;
        public string NTASK_JOB_SNAME { get; set; }//;
        public System.Nullable<System.DateTime> CRT_DATE { get; set; }//;
        public System.Nullable<System.DateTime> MFY_DATE { get; set; }//;
        public System.Nullable<int> MFY_SUSER_ID { get; set; }//;
        #endregion
        #region Navigation - children
        // 
        // FK_NSI_TASK_JOB_SCHEM_NSI_TASK_JOB1   [NSI_TASK_JOB_SCHEM.PARENT_ID]
        public virtual ICollection<NSI_TASK_JOB_SCHEM> NSI_TASK_JOB_SCHEM { get; set; }//;
        // 
        // FK_NSI_TASK_JOB_SCHEM_NSI_TASK_JOB   [NSI_TASK_JOB_SCHEM.CHILD_ID]   #1
        public virtual ICollection<NSI_TASK_JOB_SCHEM> NSI_TASK_JOB_SCHEM1 { get; set; }//;
        #endregion
        #region Constructor
        public NSI_TASK_JOB()
        {
            this.NSI_TASK_JOB_SCHEM = new HashSet<NSI_TASK_JOB_SCHEM>();
            this.NSI_TASK_JOB_SCHEM1 = new HashSet<NSI_TASK_JOB_SCHEM>();
        }
        #endregion
    }
}
