//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Core.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class NSI_DATA_SOURCE : IEntityObject, IEntityLog
    {
        #region Columns
        long IEntityObject.Id { get { return NDATA_SOURCE_ID; } }//;
        [KeyAttribute()]
        public int NDATA_SOURCE_ID { get; set; }//;
        public string NDATA_SOURCE_NAME { get; set; }//;
        public System.Nullable<short> ASKUE { get; set; }//;
        public string DETAIL { get; set; }//;
        public System.Nullable<System.DateTime> CRT_DATE { get; set; }//;
        public System.Nullable<System.DateTime> MFY_DATE { get; set; }//;
        public System.Nullable<int> MFY_SUSER_ID { get; set; }//;
        #endregion
        #region Navigation - children
        // 
        // FK_EVENT_NSI_DATA_SOURCE   [EVENT.NDATA_SOURCE_ID]
        public virtual ICollection<EVENT> EVENT { get; set; }//;
        // 
        // FK_SYS_BASE_RELATION_NSI_DATA_SOURCE   [SYS_BASE_RELATION.NDATA_SOURCE_ID]
        public virtual ICollection<SYS_BASE_RELATION> SYS_BASE_RELATION { get; set; }//;
        #endregion
        #region Constructor
        public NSI_DATA_SOURCE()
        {
            this.EVENT = new HashSet<EVENT>();
            this.SYS_BASE_RELATION = new HashSet<SYS_BASE_RELATION>();
        }
        #endregion
    }
}
