//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Core.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    
    public partial class NSI_ALGORITHM_IMPL : IEntityObject, IEntityLog
    {
        
        #region Columns
        long IEntityObject.Id { get { return NALGORITHM_IMPL_ID; } }//;
        
        [KeyAttribute()]
        public int NALGORITHM_IMPL_ID { get; set; }//;
        
        public int NALGORITHM_ID { get; set; }//;
        
        public string HANDLER_LIB { get; set; }//;
        
        public string HANDLER_TYPE { get; set; }//;
        
        public string HANDLER_METHOD { get; set; }//;
        
        public string COMMENT { get; set; }//;
        
        public System.Nullable<int> PRECISION_LEVEL { get; set; }//;
        
        public string DEVELOPER { get; set; }//;
        
        public System.Nullable<System.DateTime> CRT_DATE { get; set; }//;
        
        public System.Nullable<System.DateTime> MFY_DATE { get; set; }//;
        
        public System.Nullable<int> MFY_SUSER_ID { get; set; }//;
        #endregion
        
        #region Navigation - parents
        // FK_NSI_ALGORITHM_IMPL_NSI_ALGORITHM
        [InverseProperty("NALGORITHM_ID")]
        public virtual NSI_ALGORITHM NSI_ALGORITHM { get; set; }//;
        #endregion
        
        #region Navigation - children
        // FK_NSI_ALGORITHM_IMPL_BINDING_NSI_ALGORITHM_IMPL
        public virtual ICollection<NSI_ALGORITHM_IMPL_BINDING> NSI_ALGORITHM_IMPL_BINDING { get; set; }//;
        
        // FK_NSI_ALGORITHM_IMPL_BINDING_NSI_ALGORITHM_IMPL_Dummy
        public virtual ICollection<NSI_ALGORITHM_IMPL_BINDING> NSI_ALGORITHM_IMPL_BINDING1 { get; set; }//;
        
        // FK_NSI_ALGORITHM_IMPL_BINDING_NSI_ALGORITHM_IMPL_Dummy
        public virtual ICollection<NSI_ALGORITHM_IMPL_BINDING> NSI_ALGORITHM_IMPL_BINDING2 { get; set; }//;
        #endregion
        
        #region Constructor
        public NSI_ALGORITHM_IMPL()
        {
            this.NSI_ALGORITHM_IMPL_BINDING = new HashSet<NSI_ALGORITHM_IMPL_BINDING>();
            this.NSI_ALGORITHM_IMPL_BINDING1 = new HashSet<NSI_ALGORITHM_IMPL_BINDING>();
            this.NSI_ALGORITHM_IMPL_BINDING2 = new HashSet<NSI_ALGORITHM_IMPL_BINDING>();
        }
        #endregion
    }
}
