//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Core.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class NSI_DOCUMENT_ITEM : IEntityObject, IEntityLog
    {
        #region Columns
        long IEntityObject.Id { get { return NDOCUMENT_ITEM_ID; } }//;
        [KeyAttribute()]
        public int NDOCUMENT_ITEM_ID { get; set; }//;
        public string NDOCUMENT_ITEM_NAME { get; set; }//;
        public System.Nullable<System.DateTime> CRT_DATE { get; set; }//;
        public System.Nullable<System.DateTime> MFY_DATE { get; set; }//;
        public System.Nullable<int> MFY_SUSER_ID { get; set; }//;
        #endregion
        #region Navigation - children
        // 
        // FK_NSI_DOCUMENT_ITEM_DOCUMENT_ITEM   [DOCUMENT_ITEM.NDOCUMENT_ITEM_ID]
        public virtual ICollection<DOCUMENT_ITEM> DOCUMENT_ITEM { get; set; }//;
        // 
        // FK_SYS_HELP_NSI_DOCUMENT_ITEM   [SYS_HELP.NDOCUMENT_ITEM_ID]
        public virtual ICollection<SYS_HELP> SYS_HELP { get; set; }//;
        // 
        // FK_SYS_HELP_INDEX_NSI_DOCUMENT_ITEM   [SYS_HELP_INDEX.NDOCUMENT_ITEM_ID]
        public virtual ICollection<SYS_HELP_INDEX> SYS_HELP_INDEX { get; set; }//;
        #endregion
        #region Constructor
        public NSI_DOCUMENT_ITEM()
        {
            this.SYS_HELP = new HashSet<SYS_HELP>();
            this.SYS_HELP_INDEX = new HashSet<SYS_HELP_INDEX>();
            this.DOCUMENT_ITEM = new HashSet<DOCUMENT_ITEM>();
        }
        #endregion
    }
}
