//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Core.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    
    public partial class NSI_TASK : IEntityObject, IEntityLog
    {
        
        #region Columns
        long IEntityObject.Id { get { return NTASK_ID; } }//;
        
        [KeyAttribute()]
        public int NTASK_ID { get; set; }//;
        
        public string NTASK_NAME { get; set; }//;
        
        public string PARAM { get; set; }//;
        
        public System.Nullable<int> STABLE_ID { get; set; }//;
        
        public System.Nullable<short> IS_TEMPLATE { get; set; }//;
        
        public System.Nullable<int> TIMEOUT { get; set; }//;
        
        public System.Nullable<short> IS_DISABLE { get; set; }//;
        
        public System.Guid HANDLER_GUID { get; set; }//;
        
        public System.Nullable<int> MAX_RESTART_ATTEMPT_COUNT { get; set; }//;
        
        public string HANDLER_LIB { get; set; }//;
        
        public string HANDLER_TYPE { get; set; }//;
        
        public string COMMENT { get; set; }//;
        
        public System.Nullable<int> PARENT_ID { get; set; }//;
        
        public System.Nullable<int> SOURCE_ID { get; set; }//;
        
        public System.Nullable<int> NODE_TYPE_ID { get; set; }//;
        
        public System.Nullable<System.DateTime> CRT_DATE { get; set; }//;
        
        public System.Nullable<System.DateTime> MFY_DATE { get; set; }//;
        
        public System.Nullable<int> MFY_SUSER_ID { get; set; }//;
        #endregion
        
        #region Navigation - parents
        // FK_NSI_TASK_PARENT_ID
        [InverseProperty("PARENT_ID")]
        public virtual NSI_TASK NSI_TASK { get; set; }//;
        
        // FK_NSI_TASK_SOURCE_ID
        [InverseProperty("SOURCE_ID")]
        public virtual NSI_TASK NSI_TASK1 { get; set; }//;
        
        // FK_NSI_TASK_SYS_TABLE
        [InverseProperty("STABLE_ID")]
        public virtual SYS_TABLE SYS_TABLE { get; set; }//;
        #endregion
        
        #region Navigation - children
        // FK_NSI_TASK_PARENT_ID
        public virtual ICollection<NSI_TASK> NSI_TASK { get; set; }//;
        
        // FK_NSI_TASK_SOURCE_ID
        public virtual ICollection<NSI_TASK> NSI_TASK1 { get; set; }//;
        
        // FK_NSI_TASK_CONFIG_NTASK_ID
        public virtual ICollection<NSI_TASK_CONFIG> NSI_TASK_CONFIG { get; set; }//;
        
        // FK_TASK_REESTR_NSI_TASK
        public virtual ICollection<TASK> TASK { get; set; }//;
        #endregion
        
        #region Constructor
        public NSI_TASK()
        {
            this.NSI_TASK = new HashSet<NSI_TASK>();
            this.NSI_TASK1 = new HashSet<NSI_TASK>();
            this.NSI_TASK_CONFIG = new HashSet<NSI_TASK_CONFIG>();
            this.TASK = new HashSet<TASK>();
        }
        #endregion
    }
}
