//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Core.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class NSI_HCS : IEntityObject, IEntityLog
    {
        #region Columns
        long IEntityObject.Id { get { return NHCS_ID; } }//;
        [KeyAttribute()]
        public int NHCS_ID { get; set; }//;
        public string NHCS_NAME { get; set; }//;
        public System.Nullable<System.DateTime> CRT_DATE { get; set; }//;
        public System.Nullable<System.DateTime> MFY_DATE { get; set; }//;
        public System.Nullable<int> MFY_SUSER_ID { get; set; }//;
        public int NHCS_TYPE_ID { get; set; }//;
        #endregion
        #region Navigation - children
        // 
        // FK_NSI_HCS_VALUE_NSI_HCS   [NSI_HCS_VALUE.NHCS_ID]
        public virtual ICollection<NSI_HCS_VALUE> NSI_HCS_VALUE { get; set; }//;
        #endregion
        #region Constructor
        public NSI_HCS()
        {
            this.NSI_HCS_VALUE = new HashSet<NSI_HCS_VALUE>();
        }
        #endregion
    }
}
