//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Core.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class NSI_CONFIG : IEntityObject, IEntityLog
    {
        #region Columns
        long IEntityObject.Id { get { return NCONFIG_ID; } }//;
        [KeyAttribute()]
        public int NCONFIG_ID { get; set; }//;
        public string NCONFIG_NAME { get; set; }//;
        public int STABLE_ID { get; set; }//;
        public long ID { get; set; }//;
        public string COMMENT { get; set; }//;
        public string DATA { get; set; }//;
        public System.Nullable<System.DateTime> CRT_DATE { get; set; }//;
        public System.Nullable<System.DateTime> MFY_DATE { get; set; }//;
        public System.Nullable<int> MFY_SUSER_ID { get; set; }//;
        #endregion
        #region Navigation - parents
        // 
        // FK_NSI_CONFIG_SYS_TABLE   [SYS_TABLE.STABLE_ID]
        [ForeignKey("STABLE_ID")]
        public virtual SYS_TABLE SYS_TABLE { get; set; }//;
        #endregion
    }
}
