//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Core.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class NSI_ACCOUNT_PERIOD : IEntityObject, IEntityLog
    {
        #region Columns
        long IEntityObject.Id { get { return NACCOUNT_PERIOD_ID; } }//;
        [KeyAttribute()]
        public int NACCOUNT_PERIOD_ID { get; set; }//;
        public System.Nullable<System.DateTime> ACCOUNT_PERIOD { get; set; }//;
        public System.Nullable<long> PARTNER_ID { get; set; }//;
        public System.Nullable<System.DateTime> PAYMENT_PERIOD { get; set; }//;
        public System.Nullable<int> NDEPARTMENT_ID { get; set; }//;
        public System.Nullable<int> ACCOUNT_PERIOD_TYPE { get; set; }//;
        public System.Nullable<System.DateTime> CRT_DATE { get; set; }//;
        public System.Nullable<System.DateTime> MFY_DATE { get; set; }//;
        public System.Nullable<int> MFY_SUSER_ID { get; set; }//;
        public string NACCOUNT_PERIOD_NAME { get; set; }//;
        #endregion
        #region Navigation - parents
        // 
        // FK_NSI_ACCOUNT_PERIOD_PARTNER   [PARTNER.PARTNER_ID]
        [ForeignKey("PARTNER_ID")]
        public virtual PARTNER PARTNER { get; set; }//;
        #endregion
        #region Navigation - children
        // 
        // FK_DEAL_NSI_ACCOUNT_PERIOD   [DEAL.NACCOUNT_PERIOD_ID]
        public virtual ICollection<DEAL> DEAL { get; set; }//;
        #endregion
        #region Constructor
        public NSI_ACCOUNT_PERIOD()
        {
            this.DEAL = new HashSet<DEAL>();
        }
        #endregion
    }
}
