//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Core.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    
    public partial class NSI_METER_CONFIG : IEntityObject, IEntityLog
    {
        
        #region Columns
        long IEntityObject.Id { get { return NMETER_CONFIG_ID; } }//;
        
        [KeyAttribute()]
        public int NMETER_CONFIG_ID { get; set; }//;
        
        public System.Nullable<int> NMETER_ID { get; set; }//;
        
        public string NMETER_CONFIG_NAME { get; set; }//;
        
        public System.Nullable<int> NZONE_UNION_ID { get; set; }//;
        
        public System.Nullable<System.DateTime> CRT_DATE { get; set; }//;
        
        public System.Nullable<System.DateTime> MFY_DATE { get; set; }//;
        
        public System.Nullable<int> MFY_SUSER_ID { get; set; }//;
        #endregion
        
        #region Navigation - parents
        // FK_NSI_METER_CONFIG_NSI_METER
        [InverseProperty("NMETER_ID")]
        public virtual NSI_METER NSI_METER { get; set; }//;
        
        // FK_NSI_METER_CONFIG_NSI_ZONE_UNION
        [InverseProperty("NZONE_UNION_ID")]
        public virtual NSI_ZONE_UNION NSI_ZONE_UNION { get; set; }//;
        #endregion
        
        #region Navigation - children
        // FK_NSI_METER_PARAM_NSI_METER_CONFIG
        public virtual ICollection<NSI_METER_PARAM> NSI_METER_PARAM { get; set; }//;
        #endregion
        
        #region Constructor
        public NSI_METER_CONFIG()
        {
            this.NSI_METER_PARAM = new HashSet<NSI_METER_PARAM>();
        }
        #endregion
    }
}
