//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Core.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    
    public partial class PARTNER_EXT : IEntityObject, IEntityLog, IEntityPeriod
    {
        
        #region Columns
        long IEntityObject.Id { get { return PARTNER_EXT_ID; } }//;
        
        [KeyAttribute()]
        public long PARTNER_EXT_ID { get; set; }//;
        
        public System.Nullable<long> PARTNER_ID { get; set; }//;
        
        public System.DateTime DATE_BEG { get; set; }//;
        
        public System.Nullable<System.DateTime> DATE_END { get; set; }//;
        
        public System.Nullable<long> BUILD_J_ID { get; set; }//;
        
        public string FLAT_J { get; set; }//;
        
        public string FLAT_P { get; set; }//;
        
        public System.Nullable<long> BUILD_P_ID { get; set; }//;
        
        public string PARTNER_NAME { get; set; }//;
        
        public string PARTNER_SNAME { get; set; }//;
        
        public string INN { get; set; }//;
        
        public System.Nullable<long> WORK_GRAPH_ID { get; set; }//;
        
        public string PASS_NUM { get; set; }//;
        
        public string PASS_SERIES { get; set; }//;
        
        public string PASS_ISSUER { get; set; }//;
        
        public System.Nullable<System.DateTime> PASS_DATE { get; set; }//;
        
        public string PASS_UNIT_CODE { get; set; }//;
        
        public System.Nullable<System.DateTime> CRT_DATE { get; set; }//;
        
        public System.Nullable<System.DateTime> MFY_DATE { get; set; }//;
        
        public System.Nullable<int> MFY_SUSER_ID { get; set; }//;
        
        public System.Nullable<long> BUILD_POST_ID { get; set; }//;
        
        public string FLAT_POST { get; set; }//;
        
        public string KPP { get; set; }//;
        
        public System.Nullable<int> ACTIVITY_TYPE { get; set; }//;
        
        public string BRAND_NAME { get; set; }//;
        
        public System.Nullable<long> BUILD_DELIVERY_ID { get; set; }//;
        
        public string FLAT_D { get; set; }//;
        
        public System.Guid SYN_GUID { get; set; }//;
        
        public System.Nullable<int> NOKOPF_ID { get; set; }//;
        #endregion
        
        #region Navigation - parents
        // FK_PARTNER_EXT_BUILD
        [InverseProperty("BUILD_DELIVERY_ID")]
        public virtual BUILD BUILD { get; set; }//;
        
        // FK_PARTNER_EXT_NSI_OKOPF
        [InverseProperty("NOKOPF_ID")]
        public virtual NSI_OKOPF NSI_OKOPF { get; set; }//;
        
        // FK_PARTNER_EXT_PARTNER
        [InverseProperty("PARTNER_ID")]
        public virtual PARTNER PARTNER { get; set; }//;
        #endregion
    }
}
