//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Core.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    
    public partial class PARTNER_CONTACT : IEntityObject, IEntityLog
    {
        
        #region Columns
        long IEntityObject.Id { get { return PARTNER_CONTACT_ID; } }//;
        
        [KeyAttribute()]
        public long PARTNER_CONTACT_ID { get; set; }//;
        
        public System.Nullable<long> PARTNER_ID { get; set; }//;
        
        public System.Nullable<int> NCONTACT_ID { get; set; }//;
        
        public string VALUE { get; set; }//;
        
        public System.Nullable<int> NCONTACT_DESTINATION_ID { get; set; }//;
        
        public string COMMENT { get; set; }//;
        
        public string INTERNAL_VALUE { get; set; }//;
        
        public System.Nullable<short> DENIED { get; set; }//;
        
        public System.Nullable<System.DateTime> CRT_DATE { get; set; }//;
        
        public System.Nullable<System.DateTime> MFY_DATE { get; set; }//;
        
        public System.Nullable<int> MFY_SUSER_ID { get; set; }//;
        
        public System.Guid SYN_GUID { get; set; }//;
        
        public System.Nullable<int> OUTDATE { get; set; }//;
        
        public string PUSH_TOKEN { get; set; }//;
        #endregion
        
        #region Navigation - parents
        // FK_PARTNER_CONTACT_NSI_CONTACT
        [InverseProperty("NCONTACT_ID")]
        public virtual NSI_CONTACT NSI_CONTACT { get; set; }//;
        
        // FK_PARTNER_CONTA_PARTNER
        [InverseProperty("PARTNER_ID")]
        public virtual PARTNER PARTNER { get; set; }//;
        #endregion
        
        #region Navigation - children
        // FK_EVENT_PARTNER_CONTACT
        public virtual ICollection<EVENT> EVENT { get; set; }//;
        
        // FK_PARTNER_RELATION_PARTNER_CONTACT
        public virtual ICollection<PARTNER_RELATION> PARTNER_RELATION { get; set; }//;
        #endregion
        
        #region Constructor
        public PARTNER_CONTACT()
        {
            this.EVENT = new HashSet<EVENT>();
            this.PARTNER_RELATION = new HashSet<PARTNER_RELATION>();
        }
        #endregion
    }
}
