//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Core.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    
    public partial class REPORT : IEntityObject, IEntityLog
    {
        
        #region Columns
        long IEntityObject.Id { get { return REPORT_ID; } }//;
        
        [KeyAttribute()]
        public long REPORT_ID { get; set; }//;
        
        public string REPORT_NAME { get; set; }//;
        
        public string TEMPLATE { get; set; }//;
        
        public string PARAMS { get; set; }//;
        
        public System.Nullable<int> REPORT_KIND { get; set; }//;
        
        public System.Nullable<long> PARENT_ID { get; set; }//;
        
        public System.Nullable<int> NREPORT_ID { get; set; }//;
        
        public System.Nullable<short> TASK_CREATE { get; set; }//;
        
        public int REPORT_ENGINE { get; set; }//;
        
        public System.Nullable<int> OUTPUT_FORMAT { get; set; }//;
        
        public System.Nullable<int> GEN_STRATEGY { get; set; }//;
        
        public System.Nullable<int> NODE_TYPE_ID { get; set; }//;
        
        public string DLG_CONFIG { get; set; }//;
        
        public string CONNECTION_NAME { get; set; }//;
        
        public System.Nullable<System.DateTime> CRT_DATE { get; set; }//;
        
        public System.Nullable<System.DateTime> MFY_DATE { get; set; }//;
        
        public System.Nullable<int> MFY_SUSER_ID { get; set; }//;
        
        public System.Nullable<int> SAVE_DEST { get; set; }//;
        
        public System.Nullable<int> PATH_DEST { get; set; }//;
        
        public System.Nullable<int> CREATE_DIRS { get; set; }//;
        #endregion
        
        #region Navigation - parents
        // FK_REPORT_REPORT
        [InverseProperty("PARENT_ID")]
        public virtual REPORT REPORT { get; set; }//;
        #endregion
        
        #region Navigation - children
        // FK_DOCUMENT_STORAGE_REPORT
        public virtual ICollection<DOCUMENT_STORAGE> DOCUMENT_STORAGE { get; set; }//;
        
        // FK_REPORT_REPORT
        public virtual ICollection<REPORT> REPORT { get; set; }//;
        
        // FK_REPORT_TABLE_REPORT
        public virtual ICollection<REPORT_TABLE> REPORT_TABLE { get; set; }//;
        #endregion
        
        #region Constructor
        public REPORT()
        {
            this.DOCUMENT_STORAGE = new HashSet<DOCUMENT_STORAGE>();
            this.REPORT = new HashSet<REPORT>();
            this.REPORT_TABLE = new HashSet<REPORT_TABLE>();
        }
        #endregion
    }
}
