//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Core.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class SYS_TABLE_COLUMN_ENUM : IEntityObject, IEntityLog
    {
        #region Columns
        long IEntityObject.Id { get { return STABLE_COLUMN_ENUM_ID; } }//;
        [KeyAttribute()]
        public int STABLE_COLUMN_ENUM_ID { get; set; }//;
        public System.Nullable<int> STABLE_COLUMN_ENUM_GROUP_ID { get; set; }//;
        public System.Nullable<int> ID { get; set; }//;
        public string STABLE_COLUMN_ENUM_NAME { get; set; }//;
        public System.Nullable<System.DateTime> CRT_DATE { get; set; }//;
        public System.Nullable<System.DateTime> MFY_DATE { get; set; }//;
        public System.Nullable<int> MFY_SUSER_ID { get; set; }//;
        #endregion
        #region Navigation - parents
        // 
        // FK_SYS_TABLE_COLUMN_ENUM_GROUP_SYS_TABLE_COLUMN_ENUM   [SYS_TABLE_COLUMN_ENUM_GROUP.STABLE_COLUMN_ENUM_GROUP_ID]
        [ForeignKey("STABLE_COLUMN_ENUM_GROUP_ID")]
        public virtual SYS_TABLE_COLUMN_ENUM_GROUP SYS_TABLE_COLUMN_ENUM_GROUP { get; set; }//;
        #endregion
    }
}
