//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Core.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    
    public partial class SYS_USER : IEntityObject, IEntityLog
    {
        
        #region Columns
        long IEntityObject.Id { get { return SUSER_ID; } }//;
        
        [KeyAttribute()]
        public int SUSER_ID { get; set; }//;
        
        public string SUSER_NAME { get; set; }//;
        
        public System.Nullable<int> SUSER_GROUP_ID { get; set; }//;
        
        public System.Nullable<int> DEFAULT_SGROUP_ID { get; set; }//;
        
        public System.Nullable<long> PARTNER_ID { get; set; }//;
        
        public System.Nullable<System.DateTime> CRT_DATE { get; set; }//;
        
        public System.Nullable<System.DateTime> MFY_DATE { get; set; }//;
        
        public System.Nullable<int> MFY_SUSER_ID { get; set; }//;
        #endregion
        
        #region Navigation - parents
        // FK_SYS_USER_PARTNER
        [InverseProperty("PARTNER_ID")]
        public virtual PARTNER PARTNER { get; set; }//;
        
        // FK_SYS_USER_SYS_GROUP
        [InverseProperty("DEFAULT_SGROUP_ID")]
        public virtual SYS_GROUP SYS_GROUP { get; set; }//;
        
        // FK_SYS_USER_SYS_USER_GROUP
        [InverseProperty("SUSER_GROUP_ID")]
        public virtual SYS_USER_GROUP SYS_USER_GROUP { get; set; }//;
        #endregion
        
        #region Navigation - children
        // FK_SYS_USER_CHAT
        public virtual ICollection<CHAT> CHAT { get; set; }//;
        
        // FK_SYS_USER_CALL_SYS_USER
        public virtual ICollection<SYS_USER_CALL> SYS_USER_CALL { get; set; }//;
        
        // FK_SYS_USER_DATA_SYS_USER
        public virtual ICollection<SYS_USER_DATA> SYS_USER_DATA { get; set; }//;
        #endregion
        
        #region Constructor
        public SYS_USER()
        {
            this.CHAT = new HashSet<CHAT>();
            this.SYS_USER_CALL = new HashSet<SYS_USER_CALL>();
            this.SYS_USER_DATA = new HashSet<SYS_USER_DATA>();
        }
        #endregion
    }
}
