//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Core.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class SYS_TABLE_TREE : IEntityObject, IEntityLog
    {
        #region Columns
        long IEntityObject.Id { get { return STABLE_TREE_ID; } }//;
        [KeyAttribute()]
        public int STABLE_TREE_ID { get; set; }//;
        public System.Nullable<int> PARENT_ID { get; set; }//;
        public System.Nullable<int> STABLE_ID { get; set; }//;
        public System.Nullable<long> ID { get; set; }//;
        public System.Nullable<int> TYPE_ID { get; set; }//;
        public string STABLE_TREE_NAME { get; set; }//;
        public string NUM { get; set; }//;
        public string DETAIL { get; set; }//;
        public System.Nullable<System.DateTime> CRT_DATE { get; set; }//;
        public System.Nullable<System.DateTime> MFY_DATE { get; set; }//;
        public System.Nullable<int> MFY_SUSER_ID { get; set; }//;
        public string STABLE_TREE_SNAME { get; set; }//;
        #endregion
        #region Navigation - parents
        // 
        // FK_SYS_TABLE_TREE_SYS_TABLE   [SYS_TABLE.STABLE_ID]
        [ForeignKey("STABLE_ID")]
        public virtual SYS_TABLE SYS_TABLE { get; set; }//;
        // 
        // FK_SYS_TABLE_TREE_SYS_TABLE_TREE   [SYS_TABLE_TREE.STABLE_TREE_ID]   #1
        [ForeignKey("PARENT_ID")]
        public virtual SYS_TABLE_TREE SYS_TABLE_TREE1 { get; set; }//;
        #endregion
        #region Navigation - children
        // 
        // FK_SYS_TABLE_TREE_SYS_TABLE_TREE   [SYS_TABLE_TREE.PARENT_ID]   #2
        public virtual ICollection<SYS_TABLE_TREE> SYS_TABLE_TREE2 { get; set; }//;
        // 
        // FK_SYS_TABLE_TREE_RELATION_SYS_TABLE_TREE   [SYS_TABLE_TREE_RELATION.STABLE_TREE_ID]
        public virtual ICollection<SYS_TABLE_TREE_RELATION> SYS_TABLE_TREE_RELATION { get; set; }//;
        #endregion
        #region Constructor
        public SYS_TABLE_TREE()
        {
            this.SYS_TABLE_TREE2 = new HashSet<SYS_TABLE_TREE>();
            this.SYS_TABLE_TREE_RELATION = new HashSet<SYS_TABLE_TREE_RELATION>();
        }
        #endregion
    }
}
