//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Core.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    
    public partial class SYS_AUTO_TEST_DETAIL : IEntityObject, IEntityLog
    {
        
        #region Columns
        long IEntityObject.Id { get { return SAUTO_TEST_DETAIL_ID; } }//;
        
        [KeyAttribute()]
        public long SAUTO_TEST_DETAIL_ID { get; set; }//;
        
        public long SAUTO_TEST_ID { get; set; }//;
        
        public System.Nullable<long> PARENT_ID { get; set; }//;
        
        public System.Nullable<int> TYPE_ID { get; set; }//;
        
        public System.Nullable<int> LEVEL { get; set; }//;
        
        public System.Nullable<int> BROWSER_TYPE { get; set; }//;
        
        public System.Nullable<System.DateTime> CRT_DATE { get; set; }//;
        
        public System.Nullable<System.DateTime> MFY_DATE { get; set; }//;
        
        public System.Nullable<int> MFY_SUSER_ID { get; set; }//;
        #endregion
        
        #region Navigation - parents
        // FK_SYS_AUTO_TEST_SYS_AUTO_TEST_DETAIL
        [InverseProperty("SAUTO_TEST_ID")]
        public virtual SYS_AUTO_TEST SYS_AUTO_TEST { get; set; }//;
        
        // FK_SYS_AUTO_TEST_DETAIL_SYS_AUTO_TEST_DETAIL_PARENT
        [InverseProperty("PARENT_ID")]
        public virtual SYS_AUTO_TEST_DETAIL SYS_AUTO_TEST_DETAIL1 { get; set; }//;
        #endregion
        
        #region Navigation - children
        // FK_SYS_AUTO_TEST_DETAIL_SYS_AUTO_TEST_DETAIL_PARENT
        public virtual ICollection<SYS_AUTO_TEST_DETAIL> SYS_AUTO_TEST_DETAIL2 { get; set; }//;
        #endregion
        
        #region Constructor
        public SYS_AUTO_TEST_DETAIL()
        {
            this.SYS_AUTO_TEST_DETAIL2 = new HashSet<SYS_AUTO_TEST_DETAIL>();
        }
        #endregion
    }
}
