//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Core.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    
    public partial class SYS_USER_CALL : IEntityObject, IEntityLog
    {
        
        #region Columns
        long IEntityObject.Id { get { return SUSER_CALL_ID; } }//;
        
        [KeyAttribute()]
        public long SUSER_CALL_ID { get; set; }//;
        
        public System.Nullable<int> SUSER_ID { get; set; }//;
        
        public string EXT_NUM { get; set; }//;
        
        public System.Nullable<short> DIRECTION { get; set; }//;
        
        public System.Nullable<short> MISSED { get; set; }//;
        
        public System.Nullable<System.DateTime> CALL_TIME { get; set; }//;
        
        public System.Nullable<System.DateTime> TALK_START { get; set; }//;
        
        public System.Nullable<System.DateTime> TALK_END { get; set; }//;
        
        public string NUM { get; set; }//;
        
        public System.Nullable<long> EVENT_ID { get; set; }//;
        
        public System.Nullable<System.DateTime> CRT_DATE { get; set; }//;
        
        public System.Nullable<System.DateTime> MFY_DATE { get; set; }//;
        
        public System.Nullable<int> MFY_SUSER_ID { get; set; }//;
        #endregion
        
        #region Navigation - parents
        // FK_SYS_USER_CALL_EVENT
        [InverseProperty("EVENT_ID")]
        public virtual EVENT EVENT { get; set; }//;
        
        // FK_SYS_USER_CALL_SYS_USER
        [InverseProperty("SUSER_ID")]
        public virtual SYS_USER SYS_USER { get; set; }//;
        #endregion
    }
}
