//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Core.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class SYS_GROUP_FILTER : IEntityObject, IEntityLog
    {
        #region Columns
        long IEntityObject.Id { get { return SGROUP_FILTER_ID; } }//;
        [KeyAttribute()]
        public int SGROUP_FILTER_ID { get; set; }//;
        public int SGROUP_ID { get; set; }//;
        public int STABLE_ID { get; set; }//;
        public string FILTER { get; set; }//;
        public short MODE { get; set; }//;
        public System.Nullable<System.DateTime> CRT_DATE { get; set; }//;
        public System.Nullable<System.DateTime> MFY_DATE { get; set; }//;
        public System.Nullable<int> MFY_SUSER_ID { get; set; }//;
        #endregion
        #region Navigation - parents
        // 
        // FK_SYS_GROUP_FILTER_SYS_GROUP   [SYS_GROUP.SGROUP_ID]
        [ForeignKey("SGROUP_ID")]
        public virtual SYS_GROUP SYS_GROUP { get; set; }//;
        // 
        // FK_SYS_GROUP_FILTER_SYS_TABLE   [SYS_TABLE.STABLE_ID]
        [ForeignKey("STABLE_ID")]
        public virtual SYS_TABLE SYS_TABLE { get; set; }//;
        #endregion
    }
}
