//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Core.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    
    public partial class SYS_COMBO_ITEM : IEntityObject
    {
        
        #region Columns
        long IEntityObject.Id { get { return KOD; } }//;
        
        [KeyAttribute()]
        public long KOD { get; set; }//;
        
        public string NAME { get; set; }//;
        
        public string SNAME { get; set; }//;
        
        public string XML { get; set; }//;
        
        public string NAME_IMAGE { get; set; }//;
        
        public System.Nullable<long> GROUP_ID { get; set; }//;
        
        public System.Nullable<long> GROUP2_ID { get; set; }//;
        #endregion
    }
}
