//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Core.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    
    public partial class SYS_CONFIG : IEntityObject, IEntityLog
    {
        
        #region Columns
        long IEntityObject.Id { get { return SCONFIG_ID; } }//;
        
        [KeyAttribute()]
        public int SCONFIG_ID { get; set; }//;
        
        public string SCONFIG_NAME { get; set; }//;
        
        public System.Nullable<int> SCONFIG_TYPE_ID { get; set; }//;
        
        public System.Nullable<int> SUSER_ID { get; set; }//;
        
        public System.Nullable<int> CONFIG_OBJECT_ID { get; set; }//;
        
        public string VALUE { get; set; }//;
        
        public System.Nullable<int> PARENT_ID { get; set; }//;
        
        public System.Nullable<int> PARAM1 { get; set; }//;
        
        public System.Nullable<int> PARAM2 { get; set; }//;
        
        public System.Nullable<long> ID { get; set; }//;
        
        public System.Nullable<System.DateTime> CRT_DATE { get; set; }//;
        
        public System.Nullable<System.DateTime> MFY_DATE { get; set; }//;
        
        public System.Nullable<int> MFY_SUSER_ID { get; set; }//;
        #endregion
        
        #region Navigation - children
        // FK_SYS_USER_DATA_SYS_CONFIG
        public virtual ICollection<SYS_USER_DATA> SYS_USER_DATA { get; set; }//;
        
        // FK_SYS_USER_GROUP_CONFIG_SYS_CONFIG
        public virtual ICollection<SYS_USER_GROUP_CONFIG> SYS_USER_GROUP_CONFIG { get; set; }//;
        #endregion
        
        #region Constructor
        public SYS_CONFIG()
        {
            this.SYS_USER_DATA = new HashSet<SYS_USER_DATA>();
            this.SYS_USER_GROUP_CONFIG = new HashSet<SYS_USER_GROUP_CONFIG>();
        }
        #endregion
    }
}
