//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Core.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    
    public partial class SYS_TABLE_TREE_RELATION : IEntityObject, IEntityLog, IEntityPeriod
    {
        
        #region Columns
        long IEntityObject.Id { get { return STABLE_TREE_RELATION_ID; } }//;
        
        [KeyAttribute()]
        public int STABLE_TREE_RELATION_ID { get; set; }//;
        
        public System.Nullable<int> STABLE_TREE_ID { get; set; }//;
        
        public System.Nullable<long> CHILD_ID { get; set; }//;
        
        public System.Nullable<int> NSYS_TABLE_TREE_RELATION_ID { get; set; }//;
        
        public string COMMENT { get; set; }//;
        
        public System.DateTime DATE_BEG { get; set; }//;
        
        public System.Nullable<System.DateTime> DATE_END { get; set; }//;
        
        public string DETAIL { get; set; }//;
        
        public System.Nullable<long> PARAM1 { get; set; }//;
        
        public System.Nullable<int> PARAM2 { get; set; }//;
        
        public System.Nullable<int> PARAM3 { get; set; }//;
        
        public System.Nullable<System.DateTime> CRT_DATE { get; set; }//;
        
        public System.Nullable<System.DateTime> MFY_DATE { get; set; }//;
        
        public System.Nullable<int> MFY_SUSER_ID { get; set; }//;
        #endregion
        
        #region Navigation - parents
        // FK_SYS_TABLE_TREE_RELATION_NSI_SYS_TABLE_TREE_RELATION
        [InverseProperty("NSYS_TABLE_TREE_RELATION_ID")]
        public virtual NSI_SYS_TABLE_TREE_RELATION NSI_SYS_TABLE_TREE_RELATION { get; set; }//;
        
        // FK_SYS_TABLE_TREE_RELATION_SYS_TABLE_TREE
        [InverseProperty("STABLE_TREE_ID")]
        public virtual SYS_TABLE_TREE SYS_TABLE_TREE { get; set; }//;
        #endregion
    }
}
