//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Core.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    
    public partial class SYS_VERSION : IEntityObject, IEntityLog
    {
        
        #region Columns
        long IEntityObject.Id { get { return SVERSION_ID; } }//;
        
        [KeyAttribute()]
        public int SVERSION_ID { get; set; }//;
        
        public string SVERSION_NAME { get; set; }//;
        
        public System.Nullable<System.DateTime> CRT_DATE { get; set; }//;
        
        public System.Nullable<System.DateTime> MFY_DATE { get; set; }//;
        
        public System.Nullable<int> MFY_SUSER_ID { get; set; }//;
        
        public int SMODULE_ID { get; set; }//;
        
        public int VERSION { get; set; }//;
        #endregion
        
        #region Navigation - parents
        // FK_SYS_VERSION_SYS_MODULE
        [InverseProperty("SMODULE_ID")]
        public virtual SYS_MODULE SYS_MODULE { get; set; }//;
        #endregion
        
        #region Navigation - children
        // FK_SYS_HELP_SYS_VERSION
        public virtual ICollection<SYS_HELP> SYS_HELP { get; set; }//;
        
        // FK_SYS_HELP_INDEX_SYS_VERSION
        public virtual ICollection<SYS_HELP_INDEX> SYS_HELP_INDEX { get; set; }//;
        #endregion
        
        #region Constructor
        public SYS_VERSION()
        {
            this.SYS_HELP = new HashSet<SYS_HELP>();
            this.SYS_HELP_INDEX = new HashSet<SYS_HELP_INDEX>();
        }
        #endregion
    }
}
