//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Core.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class TASK_TRIGGER_EVENT : IEntityObject, IEntityLog
    {
        #region Columns
        long IEntityObject.Id { get { return TASK_TRIGGER_ID; } }//;
        [KeyAttribute()]
        public long TASK_TRIGGER_ID { get; set; }//;
        public int NEVENT_ID { get; set; }//;
        public string PARAM { get; set; }//;
        public System.Nullable<System.DateTime> CRT_DATE { get; set; }//;
        public System.Nullable<System.DateTime> MFY_DATE { get; set; }//;
        public System.Nullable<int> MFY_SUSER_ID { get; set; }//;
        #endregion
        #region Navigation - parents
        // 
        // FK_TASK_EVENT_TRIGGER_NSI_EVENT   [NSI_EVENT.NEVENT_ID]
        [ForeignKey("NEVENT_ID")]
        public virtual NSI_EVENT NSI_EVENT { get; set; }//;
        // 
        // FK_TASK_TRIGGER_EVENT_TASK_TRIGGER   [TASK_TRIGGER.TASK_TRIGGER_ID]
        [ForeignKey("TASK_TRIGGER_ID")]
        public virtual TASK_TRIGGER TASK_TRIGGER { get; set; }//;
        #endregion
    }
}
