//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Core.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class TASK_TRIGGER : IEntityObject, IEntityLog, IEntityPeriod
    {
        #region Columns
        long IEntityObject.Id { get { return TASK_TRIGGER_ID; } }//;
        [KeyAttribute()]
        public long TASK_TRIGGER_ID { get; set; }//;
        public long TASK_ID { get; set; }//;
        public int NTASK_TRIGGER_ID { get; set; }//;
        public System.DateTime DATE_BEG { get; set; }//;
        public System.Nullable<System.DateTime> DATE_END { get; set; }//;
        public System.Nullable<int> DELAY { get; set; }//;
        public System.Nullable<int> REPETITION_INTERVAL { get; set; }//;
        public System.Nullable<int> REPETITION_DURATION { get; set; }//;
        public short ENABLED { get; set; }//;
        public System.Nullable<System.DateTime> CRT_DATE { get; set; }//;
        public System.Nullable<System.DateTime> MFY_DATE { get; set; }//;
        public System.Nullable<int> MFY_SUSER_ID { get; set; }//;
        #endregion
        #region Navigation - parents
        // 
        // FK_TASK_TRIGGER_NSI_TASK_TRIGGER   [NSI_TASK_TRIGGER.NTASK_TRIGGER_ID]
        [ForeignKey("NTASK_TRIGGER_ID")]
        public virtual NSI_TASK_TRIGGER NSI_TASK_TRIGGER { get; set; }//;
        // 
        // FK_TASK_TRIGGER_TASK   [TASK.TASK_ID]
        [ForeignKey("TASK_ID")]
        public virtual TASK TASK { get; set; }//;
        #endregion
        #region Navigation - children
        // 
        // FK_TASK_TRIGGER_EVENT_TASK_TRIGGER   [TASK_TRIGGER_EVENT.TASK_TRIGGER_ID]
        public virtual ICollection<TASK_TRIGGER_EVENT> TASK_TRIGGER_EVENT { get; set; }//;
        // 
        // FK_TASK_TRIGGER_TIME_TASK_TRIGGER   [TASK_TRIGGER_TIME.TASK_TRIGGER_ID]
        public virtual ICollection<TASK_TRIGGER_TIME> TASK_TRIGGER_TIME { get; set; }//;
        #endregion
        #region Constructor
        public TASK_TRIGGER()
        {
            this.TASK_TRIGGER_TIME = new HashSet<TASK_TRIGGER_TIME>();
            this.TASK_TRIGGER_EVENT = new HashSet<TASK_TRIGGER_EVENT>();
        }
        #endregion
    }
}
