//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Core.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    
    public partial class TASK : IEntityObject, IEntityLog
    {
        
        #region Columns
        long IEntityObject.Id { get { return TASK_ID; } }//;
        
        [KeyAttribute()]
        public long TASK_ID { get; set; }//;
        
        public System.Nullable<int> NTASK_ID { get; set; }//;
        
        public string TASK_NAME { get; set; }//;
        
        public System.Nullable<int> NTASK_STATUS_ID { get; set; }//;
        
        public System.Nullable<System.DateTime> DATE_CREATE { get; set; }//;
        
        public string PARAM { get; set; }//;
        
        public System.Nullable<int> TIMEOUT { get; set; }//;
        
        public System.Nullable<int> THREADS_COUNT { get; set; }//;
        
        public short STOP_EXECUTION_ON_START { get; set; }//;
        
        public System.Nullable<int> MAX_RESTART_ATTEMPT_COUNT { get; set; }//;
        
        public System.Nullable<short> START_EXECUTION_ON_CREATE { get; set; }//;
        
        public System.Nullable<System.DateTime> EXECUTION_INTERVAL_BEG { get; set; }//;
        
        public System.Nullable<System.DateTime> EXECUTION_INTERVAL_END { get; set; }//;
        
        public System.Nullable<int> RESTART_TIMEOUT { get; set; }//;
        
        public System.Nullable<short> MULTIPLE_EXECUTIONS_MODE { get; set; }//;
        
        public System.Nullable<int> APP_ID { get; set; }//;
        
        public System.Nullable<int> NALGORITHM_ID { get; set; }//;
        
        public System.Nullable<System.DateTime> CRT_DATE { get; set; }//;
        
        public System.Nullable<System.DateTime> MFY_DATE { get; set; }//;
        
        public System.Nullable<int> MFY_SUSER_ID { get; set; }//;
        #endregion
        
        #region Navigation - parents
        // FK_TASK_NSI_ALGORITHM
        [InverseProperty("NALGORITHM_ID")]
        public virtual NSI_ALGORITHM NSI_ALGORITHM { get; set; }//;
        
        // FK_TASK_REESTR_NSI_TASK
        [InverseProperty("NTASK_ID")]
        public virtual NSI_TASK NSI_TASK { get; set; }//;
        
        // FK_TASK_REESTR_NSI_TASK_STATUS
        [InverseProperty("NTASK_STATUS_ID")]
        public virtual NSI_TASK_STATUS NSI_TASK_STATUS { get; set; }//;
        #endregion
        
        #region Navigation - children
        // FK_TASK_EXECUTION_TASK
        public virtual ICollection<TASK_EXECUTION> TASK_EXECUTION { get; set; }//;
        
        // FK_TASK_TRIGGER_TASK
        public virtual ICollection<TASK_TRIGGER> TASK_TRIGGER { get; set; }//;
        #endregion
        
        #region Constructor
        public TASK()
        {
            this.TASK_EXECUTION = new HashSet<TASK_EXECUTION>();
            this.TASK_TRIGGER = new HashSet<TASK_TRIGGER>();
        }
        #endregion
    }
}
