//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tsb.Security.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class scr_session_claim
    {
        public long session_claim_id { get; set; }
        public long session_id { get; set; }
        public string claim_type { get; set; }
        public string claim_value { get; set; }
    
        public virtual scr_session scr_session { get; set; }
    }
}
