//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tsb.Security.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class scr_role
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public scr_role()
        {
            this.scr_role_principal = new HashSet<scr_role_principal>();
            this.scr_role_role = new HashSet<scr_role_role>();
            this.scr_role_role1 = new HashSet<scr_role_role>();
        }
    
        public int role_id { get; set; }
        public string role_name { get; set; }
        public short is_fixed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<scr_role_principal> scr_role_principal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<scr_role_role> scr_role_role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<scr_role_role> scr_role_role1 { get; set; }
    }
}
