//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tsb.Security.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class scr_session
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public scr_session()
        {
            this.scr_session_claim = new HashSet<scr_session_claim>();
        }
    
        public long session_id { get; set; }
        public System.Guid session_uid { get; set; }
        public int application_id { get; set; }
        public string security_token { get; set; }
        public System.DateTime date_beg { get; set; }
        public Nullable<System.DateTime> date_end { get; set; }
        public string email { get; set; }
        public short is_email_confirmed { get; set; }
        public Nullable<System.DateTime> email_confirmation_date { get; set; }
        public Nullable<System.DateTime> email_token_transfer_date { get; set; }
        public string phone_number { get; set; }
        public short is_phone_number_confirmed { get; set; }
        public Nullable<System.DateTime> phone_number_confirmation_date { get; set; }
        public Nullable<System.DateTime> phone_number_code_transfer_date { get; set; }
        public string login_provider { get; set; }
        public string provider_key { get; set; }
        public int register_type { get; set; }
        public string last_name { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<scr_session_claim> scr_session_claim { get; set; }
    }
}
