//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Core.Context
{
    using Microsoft.EntityFrameworkCore;
    using Server.Core.Model;
    
    public partial class EntityContext : DbContext
    {
        public virtual DbSet<NSI_STREET> NSI_STREET { get; set; }//;
        public virtual DbSet<NSI_STREET_TYPE> NSI_STREET_TYPE { get; set; }//;
        public virtual DbSet<NSI_VILLAGE> NSI_VILLAGE { get; set; }//;
        public virtual DbSet<NSI_VILLAGE_TYPE> NSI_VILLAGE_TYPE { get; set; }//;
        public virtual DbSet<zzExcel> zzExcel { get; set; }//;
        // 
        // Create navigation props
        private void createNavigations(ModelBuilder builder)
        {
            // 
            // FK_NSI_STREET_NSI_VILLAGE []
            builder.Entity<NSI_STREET>().HasOne(u => u.NSI_VILLAGE).WithMany(t => t.NSI_STREET).HasForeignKey(t => t.NVILLAGE_ID);//();
            // 
            // FK_NSI_STREET_NSI_STREET_TYPE []
            builder.Entity<NSI_STREET>().HasOne(u => u.NSI_STREET_TYPE).WithMany(t => t.NSI_STREET).HasForeignKey(t => t.NSTREET_TYPE_ID);//();
            // 
            // FK_NSI_VILLAGE_NSI_VILLAGE_TYPE []
            builder.Entity<NSI_VILLAGE>().HasOne(u => u.NSI_VILLAGE_TYPE).WithMany(t => t.NSI_VILLAGE).HasForeignKey(t => t.NVILLAGE_TYPE_ID);//();
            // 
            // FK_NSI_VILLAGE_NSI_VILLAGE [1]
            builder.Entity<NSI_VILLAGE>().HasOne(u => u.NSI_VILLAGE1).WithMany(t => t.NSI_VILLAGE2).HasForeignKey(t => t.PARENT_ID);//();
        }
    }
}
