//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Core.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class NSI_STREET : IEntityObject, IEntityLog
    {
        #region Columns
        long IEntityObject.Id { get { return NSTREET_ID; } }//;
        [KeyAttribute()]
        public long NSTREET_ID { get; set; }//;
        public System.Nullable<long> NVILLAGE_ID { get; set; }//;
        public System.Nullable<long> NSTREET_TYPE_ID { get; set; }//;
        public string NSTREET_NAME { get; set; }//;
        public string GNI_CODE { get; set; }//;
        public string FIAS { get; set; }//;
        public System.Nullable<int> NDATA_SOURCE_ID { get; set; }//;
        public System.Nullable<System.DateTime> CRT_DATE { get; set; }//;
        public System.Nullable<System.DateTime> MFY_DATE { get; set; }//;
        public System.Nullable<int> MFY_SUSER_ID { get; set; }//;
        #endregion
        #region Navigation - parents
        // 
        // FK_NSI_STREET_NSI_STREET_TYPE   [NSI_STREET_TYPE.NSTREET_TYPE_ID]
        [ForeignKey("NSTREET_TYPE_ID")]
        public virtual NSI_STREET_TYPE NSI_STREET_TYPE { get; set; }//;
        // 
        // FK_NSI_STREET_NSI_VILLAGE   [NSI_VILLAGE.NVILLAGE_ID]
        [ForeignKey("NVILLAGE_ID")]
        public virtual NSI_VILLAGE NSI_VILLAGE { get; set; }//;
        #endregion
    }
}
