// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Hcs.Model
{
    public partial class AckImportResult
    {
        public AckImportResult()
        {
            AckImportResultErrors = new HashSet<AckImportResultError>();
        }

        public long uniqueId { get; set; }
        public Guid TransactionGUID { get; set; }
        [StringLength(32)]
        public string objectId { get; set; }
        [Key]
        public Guid TransportGUID { get; set; }
        public Guid? AckGUID { get; set; }
        [StringLength(128)]
        public string UniqueNumber { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdateDate { get; set; }

        [InverseProperty(nameof(AckImportResultError.AckImportTransportGU))]
        public virtual ICollection<AckImportResultError> AckImportResultErrors { get; set; }
    }
}