// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Hcs.Model
{
    public partial class OrganizationExportResult
    {
        public OrganizationExportResult()
        {
            OrganizationExportResultRoles = new HashSet<OrganizationExportResultRole>();
        }

        public long uniqueId { get; set; }
        public Guid TransactionGUID { get; set; }
        [Key]
        public Guid TransportGUID { get; set; }
        public byte orgType { get; set; }
        public Guid OrgGUID { get; set; }
        public Guid OrgVersionGUID { get; set; }
        [StringLength(1)]
        public string RegistryOrganizationStatus { get; set; }
        public Guid? OrgPPAGUID { get; set; }
        public bool? IsRegistered { get; set; }
        public bool IsVersionActual { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime VersionLastEditingDate { get; set; }

        [InverseProperty("TransportGU")]
        public virtual OrganizationExportResultEntp OrganizationExportResultEntp { get; set; }
        [InverseProperty("TransportGU")]
        public virtual OrganizationExportResultLegal OrganizationExportResultLegal { get; set; }
        [InverseProperty(nameof(OrganizationExportResultRole.OrganizationExportTransportGU))]
        public virtual ICollection<OrganizationExportResultRole> OrganizationExportResultRoles { get; set; }
    }
}