// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Hcs.Model
{
    public partial class AccountCloseResultAccountError
    {
        public long uniqueId { get; set; }
        public Guid TransactionGUID { get; set; }
        [StringLength(32)]
        public string objectId { get; set; }
        [Key]
        public Guid TransportGUID { get; set; }
        public Guid AccountCloseAccountTransportGUID { get; set; }
        [Required]
        [StringLength(32)]
        public string ErrorCode { get; set; }
        [Required]
        [StringLength(1024)]
        public string ErrorDescription { get; set; }

        [ForeignKey(nameof(AccountCloseAccountTransportGUID))]
        [InverseProperty(nameof(AccountCloseResultAccount.AccountCloseResultAccountErrors))]
        public virtual AccountCloseResultAccount AccountCloseAccountTransportGU { get; set; }
    }
}