
INSERT INTO "tsb"."SysOperation" ("OperationId", "OperationName", "Name", "PacketSize") VALUES ('2', 'NsiExport', 'Экспорт справочников', '2');
INSERT INTO "tsb"."SysOperation" ("OperationId", "OperationName", "Name", "PacketSize") VALUES ('5', 'AttachmentPost', 'Выгрузка файлов', '5');
INSERT INTO "tsb"."SysOperation" ("OperationId", "OperationName", "Name", "PacketSize") VALUES ('12', 'OrganizationExport', 'Экспорт контрагентов', '12');
INSERT INTO "tsb"."SysOperation" ("OperationId", "OperationName", "Name", "PacketSize") VALUES ('21', 'ContractImport', 'Импорт договоров', '21');
INSERT INTO "tsb"."SysOperation" ("OperationId", "OperationName", "Name", "PacketSize") VALUES ('22', 'ContractExport', 'Экспорт договоров', '22');
INSERT INTO "tsb"."SysOperation" ("OperationId", "OperationName", "Name", "PacketSize") VALUES ('31', 'HouseImport', 'Импорт объектов жилого фонда', '31');
INSERT INTO "tsb"."SysOperation" ("OperationId", "OperationName", "Name", "PacketSize") VALUES ('32', 'HouseExport', 'Экспорт объектов жилого фонда', '32');
INSERT INTO "tsb"."SysOperation" ("OperationId", "OperationName", "Name", "PacketSize") VALUES ('33', 'HouseAnnul', 'Аннулирование объектов жилого фонда', '33');
INSERT INTO "tsb"."SysOperation" ("OperationId", "OperationName", "Name", "PacketSize") VALUES ('41', 'AccountImport', 'Импорт лицевых счетов', '41');
INSERT INTO "tsb"."SysOperation" ("OperationId", "OperationName", "Name", "PacketSize") VALUES ('42', 'AccountExport', 'Экспорт лицевых счетов', '42');
INSERT INTO "tsb"."SysOperation" ("OperationId", "OperationName", "Name", "PacketSize") VALUES ('43', 'AccountClose', 'Закрытие лицевых счетов', '43');
INSERT INTO "tsb"."SysOperation" ("OperationId", "OperationName", "Name", "PacketSize") VALUES ('51', 'SettlementImport', 'Импорт состояний расчетов', '51');
INSERT INTO "tsb"."SysOperation" ("OperationId", "OperationName", "Name", "PacketSize") VALUES ('61', 'PaymentImport', 'Импорт платежных документов', '61');
INSERT INTO "tsb"."SysOperation" ("OperationId", "OperationName", "Name", "PacketSize") VALUES ('62', 'PaymentExport', 'Экспорт платежных документов', '62');
INSERT INTO "tsb"."SysOperation" ("OperationId", "OperationName", "Name", "PacketSize") VALUES ('71', 'DeviceImport', 'Импорт приборов учета', '71');
INSERT INTO "tsb"."SysOperation" ("OperationId", "OperationName", "Name", "PacketSize") VALUES ('72', 'DeviceExport', 'Экспорт приборов учета', '72');
INSERT INTO "tsb"."SysOperation" ("OperationId", "OperationName", "Name", "PacketSize") VALUES ('81', 'DeviceValueImport', 'Импорт показаний', '81');
INSERT INTO "tsb"."SysOperation" ("OperationId", "OperationName", "Name", "PacketSize") VALUES ('82', 'DeviceValueExport', 'Экспорт показаний', '82');
INSERT INTO "tsb"."SysOperation" ("OperationId", "OperationName", "Name", "PacketSize") VALUES ('101', 'OrderImport', 'Импорт оплат', '101');
INSERT INTO "tsb"."SysOperation" ("OperationId", "OperationName", "Name", "PacketSize") VALUES ('111', 'AckImport', 'Импорт разносок', '111');
