 
CREATE UNIQUE INDEX "UQ_AccountExportRequest" ON "tsb"."AccountExportRequest" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_AccountExportRequest" ON "tsb"."AccountExportRequest" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_1" ON "tsb"."AccountExportRequest" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_AccountExportResult" ON "tsb"."AccountExportResult" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_AccountExportResult" ON "tsb"."AccountExportResult" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_2" ON "tsb"."AccountExportResult" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_AccountExportResultPercentPremise" ON "tsb"."AccountExportResultPercentPremise" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_AccountExportResultPercentPremise" ON "tsb"."AccountExportResultPercentPremise" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_3" ON "tsb"."AccountExportResultPercentPremise" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_AccountImportRequest" ON "tsb"."AccountImportRequest" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_AccountImportRequest" ON "tsb"."AccountImportRequest" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_4" ON "tsb"."AccountImportRequest" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_AccountImportRequestPayer" ON "tsb"."AccountImportRequestPayer" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_AccountImportRequestPayer" ON "tsb"."AccountImportRequestPayer" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_5" ON "tsb"."AccountImportRequestPayer" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_AccountImportRequestPercentPremise" ON "tsb"."AccountImportRequestPercentPremise" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_AccountImportRequestPercentPremise" ON "tsb"."AccountImportRequestPercentPremise" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_6" ON "tsb"."AccountImportRequestPercentPremise" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_AccountImportRequestReason" ON "tsb"."AccountImportRequestReason" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_AccountImportRequestReason1" ON "tsb"."AccountImportRequestReason" USING btree ("AccountImportTransportGUID" ,"ContractGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_AccountImportRequestReason" ON "tsb"."AccountImportRequestReason" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_7" ON "tsb"."AccountImportRequestReason" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_AccountImportResult" ON "tsb"."AccountImportResult" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_AccountImportResult" ON "tsb"."AccountImportResult" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_8" ON "tsb"."AccountImportResult" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_AccountImportResultError" ON "tsb"."AccountImportResultError" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_AccountImportResultError" ON "tsb"."AccountImportResultError" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_9" ON "tsb"."AccountImportResultError" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_AckImportCancellationRequest" ON "tsb"."AckImportCancellationRequest" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_AckImportCancellationRequest" ON "tsb"."AckImportCancellationRequest" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_10" ON "tsb"."AckImportCancellationRequest" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_AckImportRequest" ON "tsb"."AckImportRequest" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_AckImportRequest" ON "tsb"."AckImportRequest" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_11" ON "tsb"."AckImportRequest" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_AckImportResult" ON "tsb"."AckImportResult" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_AckImportResult" ON "tsb"."AckImportResult" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_12" ON "tsb"."AckImportResult" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_AckImportResultError" ON "tsb"."AckImportResultError" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_AckImportResultError" ON "tsb"."AckImportResultError" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_13" ON "tsb"."AckImportResultError" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_AttachmentPostRequest" ON "tsb"."AttachmentPostRequest" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_AttachmentPostRequest" ON "tsb"."AttachmentPostRequest" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_14" ON "tsb"."AttachmentPostRequest" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_AttachmentPostResult" ON "tsb"."AttachmentPostResult" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_AttachmentPostResult" ON "tsb"."AttachmentPostResult" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_15" ON "tsb"."AttachmentPostResult" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_AttachmentPostResultCopy" ON "tsb"."AttachmentPostResultCopy" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_AttachmentPostResultCopy" ON "tsb"."AttachmentPostResultCopy" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_16" ON "tsb"."AttachmentPostResultCopy" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_ContractImportRequest" ON "tsb"."ContractImportRequest" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_ContractImportRequest" ON "tsb"."ContractImportRequest" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_17" ON "tsb"."ContractImportRequest" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_ContractImportRequestAttachment" ON "tsb"."ContractImportRequestAttachment" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_ContractImportRequestAttachment" ON "tsb"."ContractImportRequestAttachment" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_18" ON "tsb"."ContractImportRequestAttachment" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_ContractImportRequestObjectAddress" ON "tsb"."ContractImportRequestObjectAddress" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_ContractImportRequestObjectAddress" ON "tsb"."ContractImportRequestObjectAddress" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_19" ON "tsb"."ContractImportRequestObjectAddress" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_ContractImportRequestObjectServiceResource" ON "tsb"."ContractImportRequestObjectServiceResource" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_ContractImportRequestObjectServiceResource" ON "tsb"."ContractImportRequestObjectServiceResource" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_20" ON "tsb"."ContractImportRequestObjectServiceResource" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_ContractImportRequestParty" ON "tsb"."ContractImportRequestParty" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_ContractImportRequestParty" ON "tsb"."ContractImportRequestParty" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_21" ON "tsb"."ContractImportRequestParty" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_ContractImportRequestSubject" ON "tsb"."ContractImportRequestSubject" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_ContractImportRequestSubject" ON "tsb"."ContractImportRequestSubject" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_22" ON "tsb"."ContractImportRequestSubject" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_ContractImportRequestSubjectQualityIndicator" ON "tsb"."ContractImportRequestSubjectQualityIndicator" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_ContractImportRequestSubjectQualityIndicator" ON "tsb"."ContractImportRequestSubjectQualityIndicator" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_23" ON "tsb"."ContractImportRequestSubjectQualityIndicator" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_ContractImportResult" ON "tsb"."ContractImportResult" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_ContractImportResult" ON "tsb"."ContractImportResult" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_24" ON "tsb"."ContractImportResult" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_ContractImportResultError" ON "tsb"."ContractImportResultError" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_ContractImportResultError" ON "tsb"."ContractImportResultError" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_25" ON "tsb"."ContractImportResultError" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_DeviceExportRequest" ON "tsb"."DeviceExportRequest" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_DeviceExportRequest" ON "tsb"."DeviceExportRequest" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_26" ON "tsb"."DeviceExportRequest" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_DeviceExportResult" ON "tsb"."DeviceExportResult" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_DeviceExportResult" ON "tsb"."DeviceExportResult" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_27" ON "tsb"."DeviceExportResult" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_DeviceExportResultAccount" ON "tsb"."DeviceExportResultAccount" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_DeviceExportResultAccount" ON "tsb"."DeviceExportResultAccount" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_28" ON "tsb"."DeviceExportResultAccount" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_DeviceExportResultAddress" ON "tsb"."DeviceExportResultAddress" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_DeviceExportResultAddress" ON "tsb"."DeviceExportResultAddress" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_29" ON "tsb"."DeviceExportResultAddress" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_DeviceImportArchiveRequest" ON "tsb"."DeviceImportArchiveRequest" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_DeviceImportArchiveRequest" ON "tsb"."DeviceImportArchiveRequest" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_30" ON "tsb"."DeviceImportArchiveRequest" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_DeviceImportReplaceRequest" ON "tsb"."DeviceImportReplaceRequest" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_DeviceImportReplaceRequest" ON "tsb"."DeviceImportReplaceRequest" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_31" ON "tsb"."DeviceImportReplaceRequest" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_DeviceImportReplaceRequestValue" ON "tsb"."DeviceImportReplaceRequestValue" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_DeviceImportReplaceRequestValue" ON "tsb"."DeviceImportReplaceRequestValue" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_32" ON "tsb"."DeviceImportReplaceRequestValue" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_DeviceImportRequest" ON "tsb"."DeviceImportRequest" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_DeviceImportRequest" ON "tsb"."DeviceImportRequest" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_33" ON "tsb"."DeviceImportRequest" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_DeviceImportRequestAccount" ON "tsb"."DeviceImportRequestAccount" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_DeviceImportRequestAccount1" ON "tsb"."DeviceImportRequestAccount" USING btree ("DeviceImportTransportGUID" ,"AccountGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_DeviceImportRequestAccount" ON "tsb"."DeviceImportRequestAccount" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_34" ON "tsb"."DeviceImportRequestAccount" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_DeviceImportRequestAddress" ON "tsb"."DeviceImportRequestAddress" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_DeviceImportRequestAddress1" ON "tsb"."DeviceImportRequestAddress" USING btree ("DeviceImportTransportGUID" ,"AddressGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_DeviceImportRequestAddress" ON "tsb"."DeviceImportRequestAddress" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_35" ON "tsb"."DeviceImportRequestAddress" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_DeviceImportRequestLinkedDevice" ON "tsb"."DeviceImportRequestLinkedDevice" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_DeviceImportRequestLinkedDevice1" ON "tsb"."DeviceImportRequestLinkedDevice" USING btree ("DeviceImportTransportGUID" ,"DeviceVersionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_DeviceImportRequestLinkedDevice" ON "tsb"."DeviceImportRequestLinkedDevice" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_36" ON "tsb"."DeviceImportRequestLinkedDevice" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_DeviceImportRequestValue" ON "tsb"."DeviceImportRequestValue" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_DeviceImportRequestValue" ON "tsb"."DeviceImportRequestValue" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_37" ON "tsb"."DeviceImportRequestValue" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_DeviceImportResult" ON "tsb"."DeviceImportResult" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_DeviceImportResult" ON "tsb"."DeviceImportResult" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_38" ON "tsb"."DeviceImportResult" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_DeviceImportResultError" ON "tsb"."DeviceImportResultError" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_DeviceImportResultError" ON "tsb"."DeviceImportResultError" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_39" ON "tsb"."DeviceImportResultError" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_DeviceValueExportRequest" ON "tsb"."DeviceValueExportRequest" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_DeviceValueExportRequest" ON "tsb"."DeviceValueExportRequest" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_40" ON "tsb"."DeviceValueExportRequest" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_DeviceValueExportRequestDevice" ON "tsb"."DeviceValueExportRequestDevice" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_DeviceValueExportRequestDevice" ON "tsb"."DeviceValueExportRequestDevice" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_41" ON "tsb"."DeviceValueExportRequestDevice" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_DeviceValueExportRequestDeviceType" ON "tsb"."DeviceValueExportRequestDeviceType" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_DeviceValueExportRequestDeviceType" ON "tsb"."DeviceValueExportRequestDeviceType" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_42" ON "tsb"."DeviceValueExportRequestDeviceType" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_DeviceValueExportRequestMunicipalResource" ON "tsb"."DeviceValueExportRequestMunicipalResource" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_DeviceValueExportRequestMunicipalResource" ON "tsb"."DeviceValueExportRequestMunicipalResource" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_43" ON "tsb"."DeviceValueExportRequestMunicipalResource" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_DeviceValueExportResult" ON "tsb"."DeviceValueExportResult" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_DeviceValueExportResult" ON "tsb"."DeviceValueExportResult" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_44" ON "tsb"."DeviceValueExportResult" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_DeviceValueImportRequest" ON "tsb"."DeviceValueImportRequest" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_DeviceValueImportRequest" ON "tsb"."DeviceValueImportRequest" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_45" ON "tsb"."DeviceValueImportRequest" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_DeviceValueImportResult" ON "tsb"."DeviceValueImportResult" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_DeviceValueImportResult" ON "tsb"."DeviceValueImportResult" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_46" ON "tsb"."DeviceValueImportResult" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_DeviceValueImportResultError" ON "tsb"."DeviceValueImportResultError" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_DeviceValueImportResultError" ON "tsb"."DeviceValueImportResultError" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_47" ON "tsb"."DeviceValueImportResultError" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_HouseExportRequest" ON "tsb"."HouseExportRequest" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_HouseExportRequest" ON "tsb"."HouseExportRequest" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_48" ON "tsb"."HouseExportRequest" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_HouseExportResult" ON "tsb"."HouseExportResult" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_HouseExportResult" ON "tsb"."HouseExportResult" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_49" ON "tsb"."HouseExportResult" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_HouseExportResultBlock" ON "tsb"."HouseExportResultBlock" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_HouseExportResultBlock" ON "tsb"."HouseExportResultBlock" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_50" ON "tsb"."HouseExportResultBlock" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_HouseExportResultEntrance" ON "tsb"."HouseExportResultEntrance" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_HouseExportResultEntrance" ON "tsb"."HouseExportResultEntrance" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_51" ON "tsb"."HouseExportResultEntrance" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_HouseExportResultLivingRoom" ON "tsb"."HouseExportResultLivingRoom" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_HouseExportResultLivingRoom" ON "tsb"."HouseExportResultLivingRoom" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_52" ON "tsb"."HouseExportResultLivingRoom" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_HouseExportResultPremise" ON "tsb"."HouseExportResultPremise" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_HouseExportResultPremise" ON "tsb"."HouseExportResultPremise" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_53" ON "tsb"."HouseExportResultPremise" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_HouseImportRequest" ON "tsb"."HouseImportRequest" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_HouseImportRequest" ON "tsb"."HouseImportRequest" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_54" ON "tsb"."HouseImportRequest" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_HouseImportRequestBlock" ON "tsb"."HouseImportRequestBlock" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_HouseImportRequestBlock" ON "tsb"."HouseImportRequestBlock" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_55" ON "tsb"."HouseImportRequestBlock" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_HouseImportRequestEntrance" ON "tsb"."HouseImportRequestEntrance" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_HouseImportRequestEntrance" ON "tsb"."HouseImportRequestEntrance" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_56" ON "tsb"."HouseImportRequestEntrance" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_HouseImportRequestLivingRoom" ON "tsb"."HouseImportRequestLivingRoom" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_HouseImportRequestLivingRoom" ON "tsb"."HouseImportRequestLivingRoom" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_57" ON "tsb"."HouseImportRequestLivingRoom" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_HouseImportRequestPremise" ON "tsb"."HouseImportRequestPremise" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_HouseImportRequestPremise" ON "tsb"."HouseImportRequestPremise" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_58" ON "tsb"."HouseImportRequestPremise" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_HouseImportResult" ON "tsb"."HouseImportResult" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_HouseImportResult" ON "tsb"."HouseImportResult" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_59" ON "tsb"."HouseImportResult" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_HouseImportResultBlock" ON "tsb"."HouseImportResultBlock" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_HouseImportResultBlock" ON "tsb"."HouseImportResultBlock" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_60" ON "tsb"."HouseImportResultBlock" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_HouseImportResultBlockError" ON "tsb"."HouseImportResultBlockError" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_HouseImportResultBlockError" ON "tsb"."HouseImportResultBlockError" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_61" ON "tsb"."HouseImportResultBlockError" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_HouseImportResultEntrance" ON "tsb"."HouseImportResultEntrance" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_HouseImportResultEntrance" ON "tsb"."HouseImportResultEntrance" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_62" ON "tsb"."HouseImportResultEntrance" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_HouseImportResultEntranceError" ON "tsb"."HouseImportResultEntranceError" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_HouseImportResultEntranceError" ON "tsb"."HouseImportResultEntranceError" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_63" ON "tsb"."HouseImportResultEntranceError" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_HouseImportResultError" ON "tsb"."HouseImportResultError" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_HouseImportResultError" ON "tsb"."HouseImportResultError" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_64" ON "tsb"."HouseImportResultError" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_HouseImportResultLivingRoom" ON "tsb"."HouseImportResultLivingRoom" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_HouseImportResultLivingRoom" ON "tsb"."HouseImportResultLivingRoom" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_65" ON "tsb"."HouseImportResultLivingRoom" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_HouseImportResultLivingRoomError" ON "tsb"."HouseImportResultLivingRoomError" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_HouseImportResultLivingRoomError" ON "tsb"."HouseImportResultLivingRoomError" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_66" ON "tsb"."HouseImportResultLivingRoomError" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_HouseImportResultPremise" ON "tsb"."HouseImportResultPremise" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_HouseImportResultPremise" ON "tsb"."HouseImportResultPremise" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_67" ON "tsb"."HouseImportResultPremise" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_HouseImportResultPremiseError" ON "tsb"."HouseImportResultPremiseError" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_HouseImportResultPremiseError" ON "tsb"."HouseImportResultPremiseError" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_68" ON "tsb"."HouseImportResultPremiseError" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_NotificationImportDeleteRequest" ON "tsb"."NotificationImportDeleteRequest" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_NotificationImportDeleteRequest" ON "tsb"."NotificationImportDeleteRequest" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_69" ON "tsb"."NotificationImportDeleteRequest" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_NotificationImportRequest" ON "tsb"."NotificationImportRequest" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_NotificationImportRequest" ON "tsb"."NotificationImportRequest" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_70" ON "tsb"."NotificationImportRequest" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_NotificationImportRequestAccountDebt" ON "tsb"."NotificationImportRequestAccountDebt" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_NotificationImportRequestAccountDebt" ON "tsb"."NotificationImportRequestAccountDebt" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_71" ON "tsb"."NotificationImportRequestAccountDebt" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_NotificationImportResult" ON "tsb"."NotificationImportResult" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_NotificationImportResult" ON "tsb"."NotificationImportResult" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_72" ON "tsb"."NotificationImportResult" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_NotificationImportResultError" ON "tsb"."NotificationImportResultError" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_NotificationImportResultError" ON "tsb"."NotificationImportResultError" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_73" ON "tsb"."NotificationImportResultError" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_NsiExportRequest" ON "tsb"."NsiExportRequest" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_NsiExportRequest" ON "tsb"."NsiExportRequest" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_74" ON "tsb"."NsiExportRequest" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_NsiExportResult" ON "tsb"."NsiExportResult" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_NsiExportResult" ON "tsb"."NsiExportResult" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_75" ON "tsb"."NsiExportResult" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_NsiExportResultField" ON "tsb"."NsiExportResultField" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_NsiExportResultField" ON "tsb"."NsiExportResultField" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_76" ON "tsb"."NsiExportResultField" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_OrderImportCancellationRequest" ON "tsb"."OrderImportCancellationRequest" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_OrderImportCancellationRequest" ON "tsb"."OrderImportCancellationRequest" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_77" ON "tsb"."OrderImportCancellationRequest" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_OrderImportRequest" ON "tsb"."OrderImportRequest" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_OrderImportRequest" ON "tsb"."OrderImportRequest" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_78" ON "tsb"."OrderImportRequest" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_OrderImportResult" ON "tsb"."OrderImportResult" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_OrderImportResult" ON "tsb"."OrderImportResult" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_79" ON "tsb"."OrderImportResult" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_OrderImportResultError" ON "tsb"."OrderImportResultError" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_OrderImportResultError" ON "tsb"."OrderImportResultError" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_80" ON "tsb"."OrderImportResultError" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_OrganizationExportRequest" ON "tsb"."OrganizationExportRequest" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_OrganizationExportRequest" ON "tsb"."OrganizationExportRequest" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_81" ON "tsb"."OrganizationExportRequest" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_OrganizationExportRequestData" ON "tsb"."OrganizationExportRequestData" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_OrganizationExportRequestData" ON "tsb"."OrganizationExportRequestData" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_82" ON "tsb"."OrganizationExportRequestData" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_OrganizationExportResult" ON "tsb"."OrganizationExportResult" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_OrganizationExportResult" ON "tsb"."OrganizationExportResult" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_83" ON "tsb"."OrganizationExportResult" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_OrganizationExportResultEntp" ON "tsb"."OrganizationExportResultEntp" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_OrganizationExportResultEntp" ON "tsb"."OrganizationExportResultEntp" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_84" ON "tsb"."OrganizationExportResultEntp" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_OrganizationExportResultLegal" ON "tsb"."OrganizationExportResultLegal" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_OrganizationExportResultLegal" ON "tsb"."OrganizationExportResultLegal" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_85" ON "tsb"."OrganizationExportResultLegal" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_OrganizationExportResultRole" ON "tsb"."OrganizationExportResultRole" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_OrganizationExportResultRole" ON "tsb"."OrganizationExportResultRole" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_86" ON "tsb"."OrganizationExportResultRole" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_PaymentExportRequest" ON "tsb"."PaymentExportRequest" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_PaymentExportRequest" ON "tsb"."PaymentExportRequest" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_87" ON "tsb"."PaymentExportRequest" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_PaymentExportRequestAccount" ON "tsb"."PaymentExportRequestAccount" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_PaymentExportRequestAccount" ON "tsb"."PaymentExportRequestAccount" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_88" ON "tsb"."PaymentExportRequestAccount" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_PaymentExportRequestDocument" ON "tsb"."PaymentExportRequestDocument" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_PaymentExportRequestDocument" ON "tsb"."PaymentExportRequestDocument" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_89" ON "tsb"."PaymentExportRequestDocument" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_PaymentExportResult" ON "tsb"."PaymentExportResult" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_PaymentExportResult" ON "tsb"."PaymentExportResult" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_90" ON "tsb"."PaymentExportResult" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_PaymentImportRequest" ON "tsb"."PaymentImportRequest" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_PaymentImportRequest" ON "tsb"."PaymentImportRequest" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_91" ON "tsb"."PaymentImportRequest" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_PaymentImportRequestChargesMunicipalService" ON "tsb"."PaymentImportRequestChargesMunicipalService" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_PaymentImportRequestChargesMunicipalService" ON "tsb"."PaymentImportRequestChargesMunicipalService" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_92" ON "tsb"."PaymentImportRequestChargesMunicipalService" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_PaymentImportRequestChargesMunicipalServiceNorm" ON "tsb"."PaymentImportRequestChargesMunicipalServiceNorm" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_PaymentImportRequestChargesMunicipalServiceNorm" ON "tsb"."PaymentImportRequestChargesMunicipalServiceNorm" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_93" ON "tsb"."PaymentImportRequestChargesMunicipalServiceNorm" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_PaymentImportRequestDebtMunicipalService" ON "tsb"."PaymentImportRequestDebtMunicipalService" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_PaymentImportRequestDebtMunicipalService" ON "tsb"."PaymentImportRequestDebtMunicipalService" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_94" ON "tsb"."PaymentImportRequestDebtMunicipalService" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_PaymentImportRequestPenaltyAndCourtCost" ON "tsb"."PaymentImportRequestPenaltyAndCourtCost" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_PaymentImportRequestPenaltyAndCourtCost" ON "tsb"."PaymentImportRequestPenaltyAndCourtCost" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_95" ON "tsb"."PaymentImportRequestPenaltyAndCourtCost" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_PaymentImportResult" ON "tsb"."PaymentImportResult" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_PaymentImportResult" ON "tsb"."PaymentImportResult" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_96" ON "tsb"."PaymentImportResult" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_PaymentImportResultError" ON "tsb"."PaymentImportResultError" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_PaymentImportResultError" ON "tsb"."PaymentImportResultError" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_97" ON "tsb"."PaymentImportResultError" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_PaymentImportWithdrawRequest" ON "tsb"."PaymentImportWithdrawRequest" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_PaymentImportWithdrawRequest" ON "tsb"."PaymentImportWithdrawRequest" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_98" ON "tsb"."PaymentImportWithdrawRequest" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_SettlementImportAnnulmentRequest" ON "tsb"."SettlementImportAnnulmentRequest" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_SettlementImportAnnulmentRequest" ON "tsb"."SettlementImportAnnulmentRequest" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_99" ON "tsb"."SettlementImportAnnulmentRequest" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_SettlementImportRequest" ON "tsb"."SettlementImportRequest" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_SettlementImportRequest" ON "tsb"."SettlementImportRequest" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_100" ON "tsb"."SettlementImportRequest" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_SettlementImportRequestPeriod" ON "tsb"."SettlementImportRequestPeriod" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_SettlementImportRequestPeriod1" ON "tsb"."SettlementImportRequestPeriod" USING btree ("SettlementImportTransportGUID" ,"Month" ,"Year") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_SettlementImportRequestPeriod" ON "tsb"."SettlementImportRequestPeriod" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_101" ON "tsb"."SettlementImportRequestPeriod" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_SettlementImportRequestPeriodAnnulment" ON "tsb"."SettlementImportRequestPeriodAnnulment" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_SettlementImportRequestPeriodAnnulment" ON "tsb"."SettlementImportRequestPeriodAnnulment" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_102" ON "tsb"."SettlementImportRequestPeriodAnnulment" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_SettlementImportRequestPeriodInfo" ON "tsb"."SettlementImportRequestPeriodInfo" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_SettlementImportRequestPeriodInfo" ON "tsb"."SettlementImportRequestPeriodInfo" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_103" ON "tsb"."SettlementImportRequestPeriodInfo" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_SettlementImportResult" ON "tsb"."SettlementImportResult" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_SettlementImportResult" ON "tsb"."SettlementImportResult" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_104" ON "tsb"."SettlementImportResult" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "UQ_SettlementImportResultrror" ON "tsb"."SettlementImportResultError" USING btree ("uniqueId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_SettlementImportResultError" ON "tsb"."SettlementImportResultError" USING btree ("TransportGUID") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID_105" ON "tsb"."SettlementImportResultError" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_SysOperation" ON "tsb"."SysOperation" USING btree ("OperationId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_SysParams" ON "tsb"."SysParams" USING btree ("Id") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_SysRegistry" ON "tsb"."SysRegistry" USING btree ("RegistryId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_SysTransaction" ON "tsb"."SysTransaction" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_SysTransactionLog" ON "tsb"."SysTransactionLog" USING btree ("TransactionLogId") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_SysTransactionLog" ON "tsb"."SysTransactionLog" USING btree ("TransactionGUID" ,"LogDate") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_SysTransactionObject" ON "tsb"."SysTransactionObject" USING btree ("TransactionObjectId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "IX_SysTransactionObject" ON "tsb"."SysTransactionObject" USING btree ("TransactionGUID" ,"objectId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_SysTransactionObjectError" ON "tsb"."SysTransactionObjectError" USING btree ("TransactionObjectErrorId") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_SysTransactionObjectError" ON "tsb"."SysTransactionObjectError" USING btree ("TransactionGUID" ,"objectId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_SysTransactionParam" ON "tsb"."SysTransactionParam" USING btree ("TransactionParamId") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "IX_SysTransactionParam" ON "tsb"."SysTransactionParam" USING btree ("TransactionGUID" ,"ParamName") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_SysTransactionState2" ON "tsb"."SysTransactionState2" USING btree ("TransactionStateId") TABLESPACE "pg_default"; 
CREATE  INDEX "IX_TransactionGUID" ON "tsb"."SysTransactionState2" USING btree ("TransactionGUID") TABLESPACE "pg_default"; 
CREATE UNIQUE INDEX "PK_SysTransactionStateType" ON "tsb"."SysTransactionStateType" USING btree ("TransactionStateTypeId") TABLESPACE "pg_default";
