 
CREATE TABLE "tsb"."AccountExportRequest" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "TransportGUID" uuid PRIMARY KEY , 
   "FIASHouseGuid" uuid NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."AccountExportRequest" OWNER to "postgres";
 
CREATE TABLE "tsb"."AccountExportResult" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "TransportGUID" uuid PRIMARY KEY , 
   "AccountGUID" uuid NOT NULL , 
   "AccountNumber" character varying(30) COLLATE pg_catalog."default" , 
   "UnifiedAccountNumber" character varying(10) COLLATE pg_catalog."default" NOT NULL , 
   "ServiceID" character varying(13) COLLATE pg_catalog."default" , 
   "IsRSOAccount" bool NOT NULL , 
   "CreationDate" timestamp , 
   "LivingPersonsNumber" smallint , 
   "TotalSquare" numeric(20,10) , 
   "ResidentialSquare" numeric(20,10) , 
   "HeatedArea" numeric(20,10) , 
   "AccountCloseReasonCode" character varying(20) COLLATE pg_catalog."default" , 
   "AccountCloseReasonGUID" uuid , 
   "CloseDate" timestamp , 
   "CloseDescription" character varying(250) COLLATE pg_catalog."default" , 
   "IsRenter" bool , 
   "IsAccountsDivided" bool , 
   "OrgVersionGUID" uuid 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."AccountExportResult" OWNER to "postgres";
 
CREATE TABLE "tsb"."AccountExportResultPercentPremise" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "TransportGUID" uuid PRIMARY KEY , 
   "AccountExportTransportGUID" uuid NOT NULL , 
   "FIASHouseGuid" uuid , 
   "PremisesGUID" uuid , 
   "LivingRoomGUID" uuid , 
   "SharePercent" numeric(20,10) 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."AccountExportResultPercentPremise" OWNER to "postgres";
 
CREATE TABLE "tsb"."AccountImportRequest" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid PRIMARY KEY , 
   "AccountGUID" uuid , 
   "AccountNumber" character varying(30) COLLATE pg_catalog."default" NOT NULL , 
   "IsRSOAccount" bool NOT NULL , 
   "CreationDate" timestamp , 
   "LivingPersonsNumber" smallint , 
   "TotalSquare" numeric(20,10) , 
   "ResidentialSquare" numeric(20,10) , 
   "HeatedArea" numeric(20,10) , 
   "AccountCloseReasonCode" character varying(20) COLLATE pg_catalog."default" , 
   "AccountCloseReasonGUID" uuid , 
   "CloseDate" timestamp , 
   "CloseDescription" character varying(250) COLLATE pg_catalog."default" , 
   "IsRenter" bool , 
   "IsAccountsDivided" bool , 
   "OrgVersionGUID" uuid 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."AccountImportRequest" OWNER to "postgres";
 
CREATE TABLE "tsb"."AccountImportRequestPayer" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid PRIMARY KEY , 
   "Surname" character varying(256) COLLATE pg_catalog."default" NOT NULL , 
   "FirstName" character varying(256) COLLATE pg_catalog."default" NOT NULL , 
   "Patronymic" character varying(256) COLLATE pg_catalog."default" , 
   "Sex" character varying(1) COLLATE pg_catalog."default" , 
   "DateOfBirth" timestamp , 
   "SNILS" character varying(11) COLLATE pg_catalog."default" , 
   "DocumentTypeCode" character varying(20) COLLATE pg_catalog."default" , 
   "DocumentTypeGUID" uuid , 
   "Series" character varying(45) COLLATE pg_catalog."default" , 
   "Number" character varying(45) COLLATE pg_catalog."default" , 
   "IssueDate" timestamp 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."AccountImportRequestPayer" OWNER to "postgres";
 
CREATE TABLE "tsb"."AccountImportRequestPercentPremise" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid PRIMARY KEY , 
   "AccountImportTransportGUID" uuid NOT NULL , 
   "FIASHouseGuid" uuid , 
   "PremisesGUID" uuid , 
   "LivingRoomGUID" uuid , 
   "SharePercent" numeric(20,10) 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."AccountImportRequestPercentPremise" OWNER to "postgres";
 
CREATE TABLE "tsb"."AccountImportRequestReason" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid PRIMARY KEY , 
   "AccountImportTransportGUID" uuid NOT NULL , 
   "ContractGUID" uuid NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."AccountImportRequestReason" OWNER to "postgres";
 
CREATE TABLE "tsb"."AccountImportResult" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid PRIMARY KEY , 
   "AccountGUID" uuid , 
   "UnifiedAccountNumber" character varying(10) COLLATE pg_catalog."default" , 
   "ServiceID" character varying(13) COLLATE pg_catalog."default" , 
   "UpdateDate" timestamp 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."AccountImportResult" OWNER to "postgres";
 
CREATE TABLE "tsb"."AccountImportResultError" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid PRIMARY KEY , 
   "AccountImportTransportGUID" uuid NOT NULL , 
   "ErrorCode" character varying(32) COLLATE pg_catalog."default" NOT NULL , 
   "ErrorDescription" text COLLATE pg_catalog."default" NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."AccountImportResultError" OWNER to "postgres";
 
CREATE TABLE "tsb"."AckImportCancellationRequest" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid PRIMARY KEY , 
   "OrderGUID" uuid NOT NULL , 
   "PaymentDocumentID" character varying(18) COLLATE pg_catalog."default" 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."AckImportCancellationRequest" OWNER to "postgres";
 
CREATE TABLE "tsb"."AckImportRequest" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid PRIMARY KEY , 
   "OrderGUID" uuid NOT NULL , 
   "PaymentDocumentID" character varying(18) COLLATE pg_catalog."default" , 
   "AckImpossible" bool NOT NULL , 
   "AckImpossibleReason" character varying(210) COLLATE pg_catalog."default" , 
   "AmountRub" numeric(20,10) , 
   "HousingServiceCode" character varying(20) COLLATE pg_catalog."default" , 
   "HousingServiceGUID" uuid , 
   "MainMunicipalServiceCode" character varying(20) COLLATE pg_catalog."default" , 
   "MainMunicipalServiceGUID" uuid , 
   "AdditionalServiceCode" character varying(20) COLLATE pg_catalog."default" , 
   "AdditionalServiceGUID" uuid , 
   "PenaltyAndCourtCostCode" character varying(20) COLLATE pg_catalog."default" , 
   "PenaltyAndCourtCostGUID" uuid , 
   "MunicipalServiceCode" character varying(20) COLLATE pg_catalog."default" , 
   "MunicipalServiceGUID" uuid , 
   "BankBIK" character varying(9) COLLATE pg_catalog."default" , 
   "OperatingAccountNumber" character varying(20) COLLATE pg_catalog."default" , 
   "DelayPeriodMonth" smallint , 
   "DelayPeriodYear" smallint , 
   "CapitalRepairPeriodMonth" smallint , 
   "CapitalRepairPeriodYear" smallint 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."AckImportRequest" OWNER to "postgres";
 
CREATE TABLE "tsb"."AckImportResult" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid PRIMARY KEY , 
   "AckGUID" uuid , 
   "UniqueNumber" character varying(128) COLLATE pg_catalog."default" , 
   "UpdateDate" timestamp 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."AckImportResult" OWNER to "postgres";
 
CREATE TABLE "tsb"."AckImportResultError" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid PRIMARY KEY , 
   "AckImportTransportGUID" uuid NOT NULL , 
   "ErrorCode" character varying(32) COLLATE pg_catalog."default" NOT NULL , 
   "ErrorDescription" text COLLATE pg_catalog."default" NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."AckImportResultError" OWNER to "postgres";
 
CREATE TABLE "tsb"."AttachmentPostRequest" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid PRIMARY KEY , 
   "Name" character varying(1024) COLLATE pg_catalog."default" NOT NULL , 
   "Description" character varying(500) COLLATE pg_catalog."default" NOT NULL , 
   "AttachmentBody" text COLLATE pg_catalog."default" NOT NULL , 
   "numCopies" smallint NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."AttachmentPostRequest" OWNER to "postgres";
 
CREATE TABLE "tsb"."AttachmentPostResult" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid PRIMARY KEY , 
   "AttachmentHASH" character varying(1024) COLLATE pg_catalog."default" NOT NULL , 
   "ErrorCode" character varying(32) COLLATE pg_catalog."default" , 
   "ErrorDescription" character varying(128) COLLATE pg_catalog."default" 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."AttachmentPostResult" OWNER to "postgres";
 
CREATE TABLE "tsb"."AttachmentPostResultCopy" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid PRIMARY KEY , 
   "AttachmentPostTransportGUID" uuid NOT NULL , 
   "AttachmentGUID" uuid NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."AttachmentPostResultCopy" OWNER to "postgres";
 
CREATE TABLE "tsb"."ContractImportRequest" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid PRIMARY KEY , 
   "ContractGUID" uuid , 
   "ComptetionDate" timestamp , 
   "ShowStartDate" smallint , 
   "ShowStartDateNextMonth" bool , 
   "ShowEndDate" smallint , 
   "ShowEndDateNextMonth" bool , 
   "ContractConclusionReasonCode" character varying(20) COLLATE pg_catalog."default" , 
   "ContractConclusionReasonGUID" uuid , 
   "ContractingParty" smallint NOT NULL , 
   "CountingResource" character varying(1) COLLATE pg_catalog."default" , 
   "IsContract" bool NOT NULL , 
   "ContractNumber" character varying(30) COLLATE pg_catalog."default" , 
   "SigningDate" timestamp , 
   "EffectiveDate" timestamp , 
   "BillingDate" smallint , 
   "PaymentDate" smallint , 
   "ProvidingInformationDate" smallint , 
   "BillingDateType" character varying(1) COLLATE pg_catalog."default" , 
   "PaymentDateType" character varying(1) COLLATE pg_catalog."default" , 
   "ProvidingInformationDateType" character varying(1) COLLATE pg_catalog."default" , 
   "IsPlannedVolume" bool NOT NULL , 
   "SpecifyingQualityIndicators" character varying(1) COLLATE pg_catalog."default" NOT NULL , 
   "MeteringDeviceInformation" bool , 
   "VolumeDepends" bool , 
   "OneTimePayment" bool , 
   "IndefiniteTerm" bool , 
   "AutomaticRollOverOneYear" bool , 
   "AccrualProcedure" character varying(1) COLLATE pg_catalog."default" , 
   "IndicationsAnyDay" bool , 
   "PlannedVolumeType" character varying(1) COLLATE pg_catalog."default" , 
   "OrgGUID" uuid 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."ContractImportRequest" OWNER to "postgres";
 
CREATE TABLE "tsb"."ContractImportRequestAttachment" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid PRIMARY KEY , 
   "ContractImportTransportGUID" uuid NOT NULL , 
   "Name" character varying(1024) COLLATE pg_catalog."default" NOT NULL , 
   "Description" character varying(500) COLLATE pg_catalog."default" NOT NULL , 
   "AttachmentBody" text COLLATE pg_catalog."default" , 
   "AttachmentHASH" text COLLATE pg_catalog."default" , 
   "AttachmentGUID" uuid 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."ContractImportRequestAttachment" OWNER to "postgres";
 
CREATE TABLE "tsb"."ContractImportRequestObjectAddress" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid PRIMARY KEY , 
   "ContractImportTransportGUID" uuid NOT NULL , 
   "houseType" smallint , 
   "FIASHouseGuid" uuid NOT NULL , 
   "ApartmentNumber" character varying(255) COLLATE pg_catalog."default" , 
   "RoomNumber" character varying(255) COLLATE pg_catalog."default" 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."ContractImportRequestObjectAddress" OWNER to "postgres";
 
CREATE TABLE "tsb"."ContractImportRequestObjectServiceResource" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid PRIMARY KEY , 
   "ContractImportObjectAddressTransportGUID" uuid NOT NULL , 
   "ContractImportSubjectTransportGUID" uuid NOT NULL , 
   "StartSupplyDate" timestamp NOT NULL , 
   "EndSupplyDate" timestamp , 
   "OpenOrNot" character varying(32) COLLATE pg_catalog."default" , 
   "CentralizedOrNot" character varying(32) COLLATE pg_catalog."default" 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."ContractImportRequestObjectServiceResource" OWNER to "postgres";
 
CREATE TABLE "tsb"."ContractImportRequestParty" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid PRIMARY KEY , 
   "FirstName" character varying(60) COLLATE pg_catalog."default" NOT NULL , 
   "Surname" character varying(60) COLLATE pg_catalog."default" NOT NULL , 
   "Patronymic" character varying(60) COLLATE pg_catalog."default" , 
   "Sex" character varying(1) COLLATE pg_catalog."default" , 
   "DateOfBirth" timestamp , 
   "DocumentTypeCode" character varying(20) COLLATE pg_catalog."default" , 
   "DocumentTypeGUID" uuid , 
   "Series" character varying(45) COLLATE pg_catalog."default" , 
   "Number" character varying(45) COLLATE pg_catalog."default" , 
   "IssueDate" timestamp , 
   "SNILS" character varying(11) COLLATE pg_catalog."default" , 
   "PlaceBirth" character varying(255) COLLATE pg_catalog."default" 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."ContractImportRequestParty" OWNER to "postgres";
 
CREATE TABLE "tsb"."ContractImportRequestSubject" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid PRIMARY KEY , 
   "ContractImportTransportGUID" uuid NOT NULL , 
   "MunicipalServiceCode" character varying(20) COLLATE pg_catalog."default" NOT NULL , 
   "MunicipalServiceGUID" uuid NOT NULL , 
   "ChargeableResourceCode" character varying(20) COLLATE pg_catalog."default" NOT NULL , 
   "ChargeableResourceGUID" uuid NOT NULL , 
   "StartSupplyDate" timestamp NOT NULL , 
   "EndSupplyDate" timestamp , 
   "Volume" numeric(20,10) , 
   "Unit" character varying(4) COLLATE pg_catalog."default" , 
   "FeedingMode" character varying(250) COLLATE pg_catalog."default" 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."ContractImportRequestSubject" OWNER to "postgres";
 
CREATE TABLE "tsb"."ContractImportRequestSubjectQualityIndicator" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid PRIMARY KEY , 
   "ContractImportSubjectTransportGUID" uuid NOT NULL , 
   "ContractImportObjectAddressTransportGUID" uuid , 
   "QualityIndicatorCode" character varying(20) COLLATE pg_catalog."default" , 
   "QualityIndicatorGUID" uuid , 
   "Number" numeric(20,10) , 
   "StartRange" numeric(20,10) , 
   "EndRange" numeric(20,10) , 
   "OKEI" character varying(4) COLLATE pg_catalog."default" , 
   "Correspond" bool , 
   "IndicatorName" character varying(1000) COLLATE pg_catalog."default" 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."ContractImportRequestSubjectQualityIndicator" OWNER to "postgres";
 
CREATE TABLE "tsb"."ContractImportResult" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid PRIMARY KEY , 
   "ContractGUID" uuid , 
   "ContractVersionGUID" uuid , 
   "UpdateDate" timestamp 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."ContractImportResult" OWNER to "postgres";
 
CREATE TABLE "tsb"."ContractImportResultError" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid PRIMARY KEY , 
   "ContractImportTransportGUID" uuid NOT NULL , 
   "ContractImportObjectAddressTransportGUID" uuid , 
   "ContractImportSubjectTransportGUID" uuid , 
   "ErrorCode" character varying(32) COLLATE pg_catalog."default" NOT NULL , 
   "ErrorDescription" text COLLATE pg_catalog."default" NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."ContractImportResultError" OWNER to "postgres";
 
CREATE TABLE "tsb"."DeviceExportRequest" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "TransportGUID" uuid PRIMARY KEY , 
   "DeviceGUID" uuid , 
   "FIASHouseGuid" uuid 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."DeviceExportRequest" OWNER to "postgres";
 
CREATE TABLE "tsb"."DeviceExportResult" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "TransportGUID" uuid PRIMARY KEY , 
   "DeviceGUID" uuid NOT NULL , 
   "DeviceVersionGUID" uuid NOT NULL , 
   "StatusRootDoc" character varying(32) COLLATE pg_catalog."default" NOT NULL , 
   "deviceType" smallint NOT NULL , 
   "individualDeviceType" smallint , 
   "DeviceNumber" character varying(50) COLLATE pg_catalog."default" NOT NULL , 
   "DeviceStamp" character varying(100) COLLATE pg_catalog."default" , 
   "DeviceModel" character varying(100) COLLATE pg_catalog."default" , 
   "InstallationDate" timestamp , 
   "CommissioningDate" timestamp , 
   "RemoteMeteringMode" bool NOT NULL , 
   "RemoteMeteringInfo" character varying(2000) COLLATE pg_catalog."default" , 
   "FirstVerificationDate" timestamp , 
   "DeviceCalibrationIntervalCode" character varying(20) COLLATE pg_catalog."default" , 
   "DeviceCalibrationIntervalGUID" uuid , 
   "FactorySealDate" timestamp , 
   "TemperatureSensor" bool NOT NULL , 
   "PressureSensor" bool NOT NULL , 
   "ConsumedVolume" bool 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."DeviceExportResult" OWNER to "postgres";
 
CREATE TABLE "tsb"."DeviceExportResultAccount" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "TransportGUID" uuid PRIMARY KEY , 
   "DeviceExportTransportGUID" uuid NOT NULL , 
   "AccountGUID" uuid NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."DeviceExportResultAccount" OWNER to "postgres";
 
CREATE TABLE "tsb"."DeviceExportResultAddress" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "TransportGUID" uuid PRIMARY KEY , 
   "DeviceExportTransportGUID" uuid NOT NULL , 
   "AddressGUID" uuid NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."DeviceExportResultAddress" OWNER to "postgres";
 
CREATE TABLE "tsb"."DeviceImportArchiveRequest" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid PRIMARY KEY , 
   "DeviceVersionGUID" uuid NOT NULL , 
   "DeviceArchivingReasonCode" character varying(20) COLLATE pg_catalog."default" NOT NULL , 
   "DeviceArchivingReasonGUID" uuid NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."DeviceImportArchiveRequest" OWNER to "postgres";
 
CREATE TABLE "tsb"."DeviceImportReplaceRequest" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid PRIMARY KEY , 
   "DeviceVersionGUID" uuid NOT NULL , 
   "VerificationDate" timestamp NOT NULL , 
   "PlannedVerification" bool , 
   "DeviceFaultReasonCode" character varying(20) COLLATE pg_catalog."default" , 
   "DeviceFaultReasonGUID" uuid , 
   "ReplacingDeviceVersionGUID" uuid NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."DeviceImportReplaceRequest" OWNER to "postgres";
 
CREATE TABLE "tsb"."DeviceImportReplaceRequestValue" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid PRIMARY KEY , 
   "DeviceImportReplaceTransportGUID" uuid NOT NULL , 
   "MunicipalResourceCode" character varying(20) COLLATE pg_catalog."default" NOT NULL , 
   "MunicipalResourceGUID" uuid NOT NULL , 
   "ValueT1" numeric(20,10) NOT NULL , 
   "ValueT2" numeric(20,10) , 
   "ValueT3" numeric(20,10) 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."DeviceImportReplaceRequestValue" OWNER to "postgres";
 
CREATE TABLE "tsb"."DeviceImportRequest" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid PRIMARY KEY , 
   "DeviceVersionGUID" uuid , 
   "deviceType" smallint NOT NULL , 
   "individualDeviceType" smallint , 
   "DeviceNumber" character varying(50) COLLATE pg_catalog."default" NOT NULL , 
   "DeviceStamp" character varying(100) COLLATE pg_catalog."default" NOT NULL , 
   "DeviceModel" character varying(100) COLLATE pg_catalog."default" NOT NULL , 
   "InstallationDate" timestamp , 
   "CommissioningDate" timestamp , 
   "RemoteMeteringMode" bool NOT NULL , 
   "RemoteMeteringInfo" character varying(2000) COLLATE pg_catalog."default" , 
   "FirstVerificationDate" timestamp , 
   "DeviceCalibrationIntervalCode" character varying(20) COLLATE pg_catalog."default" , 
   "DeviceCalibrationIntervalGUID" uuid , 
   "FactorySealDate" timestamp NOT NULL , 
   "TemperatureSensor" bool NOT NULL , 
   "TemperatureSensingElementInfo" character varying(2000) COLLATE pg_catalog."default" , 
   "PressureSensor" bool NOT NULL , 
   "PressureSensingElementInfo" character varying(2000) COLLATE pg_catalog."default" , 
   "InstallationPlace" character varying(1) COLLATE pg_catalog."default" , 
   "ConsumedVolume" bool 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."DeviceImportRequest" OWNER to "postgres";
 
CREATE TABLE "tsb"."DeviceImportRequestAccount" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid PRIMARY KEY , 
   "DeviceImportTransportGUID" uuid NOT NULL , 
   "AccountGUID" uuid NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."DeviceImportRequestAccount" OWNER to "postgres";
 
CREATE TABLE "tsb"."DeviceImportRequestAddress" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid PRIMARY KEY , 
   "DeviceImportTransportGUID" uuid NOT NULL , 
   "AddressGUID" uuid NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."DeviceImportRequestAddress" OWNER to "postgres";
 
CREATE TABLE "tsb"."DeviceImportRequestLinkedDevice" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid PRIMARY KEY , 
   "DeviceImportTransportGUID" uuid NOT NULL , 
   "DeviceVersionGUID" uuid NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."DeviceImportRequestLinkedDevice" OWNER to "postgres";
 
CREATE TABLE "tsb"."DeviceImportRequestValue" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid PRIMARY KEY , 
   "DeviceImportTransportGUID" uuid NOT NULL , 
   "MunicipalResourceCode" character varying(20) COLLATE pg_catalog."default" NOT NULL , 
   "MunicipalResourceGUID" uuid NOT NULL , 
   "ValueT1" numeric(20,10) NOT NULL , 
   "ValueT2" numeric(20,10) , 
   "ValueT3" numeric(20,10) , 
   "TransformationRatio" numeric(20,10) 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."DeviceImportRequestValue" OWNER to "postgres";
 
CREATE TABLE "tsb"."DeviceImportResult" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid PRIMARY KEY , 
   "DeviceGUID" uuid , 
   "DeviceVersionGUID" uuid , 
   "DeviceUniqueNumber" character varying(128) COLLATE pg_catalog."default" , 
   "UpdateDate" timestamp 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."DeviceImportResult" OWNER to "postgres";
 
CREATE TABLE "tsb"."DeviceImportResultError" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid PRIMARY KEY , 
   "DeviceImportTransportGUID" uuid NOT NULL , 
   "ErrorCode" character varying(32) COLLATE pg_catalog."default" NOT NULL , 
   "ErrorDescription" text COLLATE pg_catalog."default" NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."DeviceImportResultError" OWNER to "postgres";
 
CREATE TABLE "tsb"."DeviceValueExportRequest" 
( 
   "TransportGUID" uuid PRIMARY KEY , 
   "FIASHouseGuid" uuid NOT NULL , 
   "CommissioningDateFrom" timestamp , 
   "CommissioningDateTo" timestamp , 
   "SearchArchived" bool , 
   "ArchiveDateFrom" timestamp , 
   "ArchiveDateTo" timestamp , 
   "InputDateFrom" timestamp , 
   "InputDateTo" timestamp , 
   "ExcludePersonAsDataSource" bool , 
   "ExcludeCurrentOrgAsDataSource" bool , 
   "ExcludeOtherOrgAsDataSource" bool , 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."DeviceValueExportRequest" OWNER to "postgres";
 
CREATE TABLE "tsb"."DeviceValueExportRequestDevice" 
( 
   "TransportGUID" uuid PRIMARY KEY , 
   "DeviceValueExportTransportGUID" uuid NOT NULL , 
   "DeviceGUID" uuid NOT NULL , 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."DeviceValueExportRequestDevice" OWNER to "postgres";
 
CREATE TABLE "tsb"."DeviceValueExportRequestDeviceType" 
( 
   "TransportGUID" uuid PRIMARY KEY , 
   "DeviceValueExportTransportGUID" uuid NOT NULL , 
   "DeviceTypeCode" character varying(20) COLLATE pg_catalog."default" NOT NULL , 
   "DeviceTypeGUID" uuid NOT NULL , 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."DeviceValueExportRequestDeviceType" OWNER to "postgres";
 
CREATE TABLE "tsb"."DeviceValueExportRequestMunicipalResource" 
( 
   "TransportGUID" uuid PRIMARY KEY , 
   "DeviceValueExportTransportGUID" uuid NOT NULL , 
   "MunicipalResourceCode" character varying(20) COLLATE pg_catalog."default" NOT NULL , 
   "MunicipalResourceGUID" uuid NOT NULL , 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."DeviceValueExportRequestMunicipalResource" OWNER to "postgres";
 
CREATE TABLE "tsb"."DeviceValueExportResult" 
( 
   "TransportGUID" uuid PRIMARY KEY , 
   "DeviceGUID" uuid NOT NULL , 
   "deviceShowValueType" smallint NOT NULL , 
   "DateValue" timestamp , 
   "MunicipalResourceCode" character varying(20) COLLATE pg_catalog."default" NOT NULL , 
   "MunicipalResourceGUID" uuid NOT NULL , 
   "ValueT1" numeric(20,10) NOT NULL , 
   "ValueT2" numeric(20,10) , 
   "ValueT3" numeric(20,10) , 
   "EnterIntoSystem" timestamp NOT NULL , 
   "OrgPPAGUID" uuid , 
   "ReadingsSource" character varying(1024) COLLATE pg_catalog."default" , 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."DeviceValueExportResult" OWNER to "postgres";
 
CREATE TABLE "tsb"."DeviceValueImportRequest" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid PRIMARY KEY , 
   "DeviceVersionGUID" uuid NOT NULL , 
   "deviceShowValueType" smallint NOT NULL , 
   "DateValue" timestamp NOT NULL , 
   "MunicipalResourceCode" character varying(20) COLLATE pg_catalog."default" NOT NULL , 
   "MunicipalResourceGUID" uuid NOT NULL , 
   "ValueT1" numeric(20,10) NOT NULL , 
   "ValueT2" numeric(20,10) , 
   "ValueT3" numeric(20,10) 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."DeviceValueImportRequest" OWNER to "postgres";
 
CREATE TABLE "tsb"."DeviceValueImportResult" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid PRIMARY KEY , 
   "DeviceValueGUID" uuid , 
   "UpdateDate" timestamp 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."DeviceValueImportResult" OWNER to "postgres";
 
CREATE TABLE "tsb"."DeviceValueImportResultError" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid PRIMARY KEY , 
   "DeviceValueImportTransportGUID" uuid NOT NULL , 
   "ErrorCode" character varying(32) COLLATE pg_catalog."default" NOT NULL , 
   "ErrorDescription" text COLLATE pg_catalog."default" NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."DeviceValueImportResultError" OWNER to "postgres";
 
CREATE TABLE "tsb"."HouseExportRequest" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "TransportGUID" uuid PRIMARY KEY , 
   "FIASHouseGuid" uuid NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."HouseExportRequest" OWNER to "postgres";
 
CREATE TABLE "tsb"."HouseExportResult" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "TransportGUID" uuid PRIMARY KEY , 
   "HouseGUID" uuid , 
   "HouseUniqueNumber" character varying(31) COLLATE pg_catalog."default" NOT NULL , 
   "ModificationDate" timestamp NOT NULL , 
   "houseType" smallint NOT NULL , 
   "FIASHouseGuid" uuid NOT NULL , 
   "OKTMO" character varying(11) COLLATE pg_catalog."default" , 
   "OlsonTZCode" character varying(20) COLLATE pg_catalog."default" , 
   "OlsonTZGUID" uuid , 
   "CadastralNumber" character varying(255) COLLATE pg_catalog."default" , 
   "TerminationDate" timestamp , 
   "AnnulmentReasonCode" character varying(20) COLLATE pg_catalog."default" , 
   "AnnulmentReasonGUID" uuid , 
   "AnnulmentInfo" character varying(1024) COLLATE pg_catalog."default" , 
   "MultipleHousesAddress" bool 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."HouseExportResult" OWNER to "postgres";
 
CREATE TABLE "tsb"."HouseExportResultBlock" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "TransportGUID" uuid PRIMARY KEY , 
   "HouseExportTransportGUID" uuid NOT NULL , 
   "BlockGUID" uuid NOT NULL , 
   "BlockUniqueNumber" character varying(31) COLLATE pg_catalog."default" NOT NULL , 
   "ModificationDate" timestamp NOT NULL , 
   "blockType" smallint NOT NULL , 
   "BlockNum" character varying(255) COLLATE pg_catalog."default" NOT NULL , 
   "TotalArea" numeric(20,10) , 
   "ResidentPremiseTypeCode" character varying(20) COLLATE pg_catalog."default" , 
   "ResidentPremiseTypeGUID" uuid , 
   "CadastralNumber" character varying(255) COLLATE pg_catalog."default" , 
   "TerminationDate" timestamp , 
   "AnnulmentReasonCode" character varying(20) COLLATE pg_catalog."default" , 
   "AnnulmentReasonGUID" uuid , 
   "AnnulmentInfo" character varying(1024) COLLATE pg_catalog."default" , 
   "InformationConfirmed" bool 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."HouseExportResultBlock" OWNER to "postgres";
 
CREATE TABLE "tsb"."HouseExportResultEntrance" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "TransportGUID" uuid PRIMARY KEY , 
   "HouseExportTransportGUID" uuid NOT NULL , 
   "EntranceGUID" uuid NOT NULL , 
   "ModificationDate" timestamp NOT NULL , 
   "EntranceNum" character varying(255) COLLATE pg_catalog."default" , 
   "TerminationDate" timestamp , 
   "AnnulmentReasonCode" character varying(20) COLLATE pg_catalog."default" , 
   "AnnulmentReasonGUID" uuid , 
   "AnnulmentInfo" character varying(1024) COLLATE pg_catalog."default" , 
   "InformationConfirmed" bool 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."HouseExportResultEntrance" OWNER to "postgres";
 
CREATE TABLE "tsb"."HouseExportResultLivingRoom" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "TransportGUID" uuid PRIMARY KEY , 
   "HouseExportTransportGUID" uuid NOT NULL , 
   "HouseExportPremiseTransportGUID" uuid , 
   "HouseExportBlockTransportGUID" uuid , 
   "LivingRoomGUID" uuid NOT NULL , 
   "LivingRoomUniqueNumber" character varying(31) COLLATE pg_catalog."default" NOT NULL , 
   "ModificationDate" timestamp NOT NULL , 
   "RoomNumber" character varying(255) COLLATE pg_catalog."default" , 
   "Square" numeric(20,10) , 
   "CadastralNumber" character varying(255) COLLATE pg_catalog."default" , 
   "TerminationDate" timestamp , 
   "AnnulmentReasonCode" character varying(20) COLLATE pg_catalog."default" , 
   "AnnulmentReasonGUID" uuid , 
   "AnnulmentInfo" character varying(1024) COLLATE pg_catalog."default" , 
   "InformationConfirmed" bool 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."HouseExportResultLivingRoom" OWNER to "postgres";
 
CREATE TABLE "tsb"."HouseExportResultPremise" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "TransportGUID" uuid PRIMARY KEY , 
   "HouseExportTransportGUID" uuid NOT NULL , 
   "HouseExportEntranceTransportGUID" uuid , 
   "PremisesGUID" uuid NOT NULL , 
   "PremisesUniqueNumber" character varying(31) COLLATE pg_catalog."default" NOT NULL , 
   "ModificationDate" timestamp NOT NULL , 
   "premiseType" smallint NOT NULL , 
   "PremisesNum" character varying(255) COLLATE pg_catalog."default" , 
   "TotalArea" numeric(20,10) , 
   "ResidentPremiseTypeCode" character varying(20) COLLATE pg_catalog."default" , 
   "ResidentPremiseTypeGUID" uuid , 
   "CadastralNumber" character varying(255) COLLATE pg_catalog."default" , 
   "TerminationDate" timestamp , 
   "AnnulmentReasonCode" character varying(20) COLLATE pg_catalog."default" , 
   "AnnulmentReasonGUID" uuid , 
   "AnnulmentInfo" character varying(1024) COLLATE pg_catalog."default" , 
   "InformationConfirmed" bool 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."HouseExportResultPremise" OWNER to "postgres";
 
CREATE TABLE "tsb"."HouseImportRequest" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid PRIMARY KEY , 
   "HouseGUID" uuid , 
   "houseType" smallint NOT NULL , 
   "FIASHouseGuid" uuid NOT NULL , 
   "OKTMO" character varying(11) COLLATE pg_catalog."default" , 
   "OlsonTZCode" character varying(20) COLLATE pg_catalog."default" , 
   "OlsonTZGUID" uuid , 
   "CadastralNumber" character varying(255) COLLATE pg_catalog."default" , 
   "InheritMissingValues" bool , 
   "MultipleHousesAddress" bool 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."HouseImportRequest" OWNER to "postgres";
 
CREATE TABLE "tsb"."HouseImportRequestBlock" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid PRIMARY KEY , 
   "HouseImportTransportGUID" uuid NOT NULL , 
   "BlockGUID" uuid , 
   "blockType" smallint NOT NULL , 
   "BlockNum" character varying(255) COLLATE pg_catalog."default" NOT NULL , 
   "TotalArea" numeric(20,10) , 
   "ResidentPremiseTypeCode" character varying(20) COLLATE pg_catalog."default" , 
   "ResidentPremiseTypeGUID" uuid , 
   "CadastralNumber" character varying(255) COLLATE pg_catalog."default" , 
   "AnnulmentReasonCode" character varying(20) COLLATE pg_catalog."default" , 
   "AnnulmentReasonGUID" uuid , 
   "AnnulmentInfo" character varying(1024) COLLATE pg_catalog."default" 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."HouseImportRequestBlock" OWNER to "postgres";
 
CREATE TABLE "tsb"."HouseImportRequestEntrance" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid PRIMARY KEY , 
   "HouseImportTransportGUID" uuid NOT NULL , 
   "EntranceGUID" uuid , 
   "EntranceNum" character varying(255) COLLATE pg_catalog."default" NOT NULL , 
   "AnnulmentReasonCode" character varying(20) COLLATE pg_catalog."default" , 
   "AnnulmentReasonGUID" uuid , 
   "AnnulmentInfo" character varying(1024) COLLATE pg_catalog."default" 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."HouseImportRequestEntrance" OWNER to "postgres";
 
CREATE TABLE "tsb"."HouseImportRequestLivingRoom" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid PRIMARY KEY , 
   "HouseImportTransportGUID" uuid NOT NULL , 
   "HouseImportPremiseTransportGUID" uuid , 
   "HouseImportBlockTransportGUID" uuid , 
   "LivingRoomGUID" uuid , 
   "RoomNumber" character varying(255) COLLATE pg_catalog."default" NOT NULL , 
   "Square" numeric(20,10) , 
   "CadastralNumber" character varying(255) COLLATE pg_catalog."default" , 
   "AnnulmentReasonCode" character varying(20) COLLATE pg_catalog."default" , 
   "AnnulmentReasonGUID" uuid , 
   "AnnulmentInfo" character varying(1024) COLLATE pg_catalog."default" 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."HouseImportRequestLivingRoom" OWNER to "postgres";
 
CREATE TABLE "tsb"."HouseImportRequestPremise" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid PRIMARY KEY , 
   "HouseImportTransportGUID" uuid NOT NULL , 
   "HouseImportEntranceTransportGUID" uuid , 
   "PremisesGUID" uuid , 
   "premiseType" smallint NOT NULL , 
   "PremisesNum" character varying(255) COLLATE pg_catalog."default" NOT NULL , 
   "TotalArea" numeric(20,10) , 
   "ResidentPremiseTypeCode" character varying(20) COLLATE pg_catalog."default" , 
   "ResidentPremiseTypeGUID" uuid , 
   "CadastralNumber" character varying(255) COLLATE pg_catalog."default" , 
   "AnnulmentReasonCode" character varying(20) COLLATE pg_catalog."default" , 
   "AnnulmentReasonGUID" uuid , 
   "AnnulmentInfo" character varying(1024) COLLATE pg_catalog."default" 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."HouseImportRequestPremise" OWNER to "postgres";
 
CREATE TABLE "tsb"."HouseImportResult" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid PRIMARY KEY , 
   "HouseGUID" uuid , 
   "HouseUniqueNumber" character varying(31) COLLATE pg_catalog."default" , 
   "UpdateDate" timestamp 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."HouseImportResult" OWNER to "postgres";
 
CREATE TABLE "tsb"."HouseImportResultBlock" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid PRIMARY KEY , 
   "HouseImportTransportGUID" uuid NOT NULL , 
   "BlockGUID" uuid , 
   "BlockUniqueNumber" character varying(31) COLLATE pg_catalog."default" , 
   "UpdateDate" timestamp 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."HouseImportResultBlock" OWNER to "postgres";
 
CREATE TABLE "tsb"."HouseImportResultBlockError" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid PRIMARY KEY , 
   "HouseImportBlockTransportGUID" uuid NOT NULL , 
   "ErrorCode" character varying(32) COLLATE pg_catalog."default" NOT NULL , 
   "ErrorDescription" text COLLATE pg_catalog."default" NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."HouseImportResultBlockError" OWNER to "postgres";
 
CREATE TABLE "tsb"."HouseImportResultEntrance" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid PRIMARY KEY , 
   "HouseImportTransportGUID" uuid NOT NULL , 
   "EntranceGUID" uuid , 
   "UpdateDate" timestamp 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."HouseImportResultEntrance" OWNER to "postgres";
 
CREATE TABLE "tsb"."HouseImportResultEntranceError" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid PRIMARY KEY , 
   "HouseImportEntranceTransportGUID" uuid NOT NULL , 
   "ErrorCode" character varying(32) COLLATE pg_catalog."default" NOT NULL , 
   "ErrorDescription" text COLLATE pg_catalog."default" NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."HouseImportResultEntranceError" OWNER to "postgres";
 
CREATE TABLE "tsb"."HouseImportResultError" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid PRIMARY KEY , 
   "HouseImportTransportGUID" uuid NOT NULL , 
   "ErrorCode" character varying(32) COLLATE pg_catalog."default" NOT NULL , 
   "ErrorDescription" text COLLATE pg_catalog."default" NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."HouseImportResultError" OWNER to "postgres";
 
CREATE TABLE "tsb"."HouseImportResultLivingRoom" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid PRIMARY KEY , 
   "HouseImportTransportGUID" uuid NOT NULL , 
   "LivingRoomGUID" uuid , 
   "LivingRoomUniqueNumber" character varying(31) COLLATE pg_catalog."default" , 
   "UpdateDate" timestamp 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."HouseImportResultLivingRoom" OWNER to "postgres";
 
CREATE TABLE "tsb"."HouseImportResultLivingRoomError" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid PRIMARY KEY , 
   "HouseImportLivingRoomTransportGUID" uuid NOT NULL , 
   "ErrorCode" character varying(32) COLLATE pg_catalog."default" NOT NULL , 
   "ErrorDescription" text COLLATE pg_catalog."default" NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."HouseImportResultLivingRoomError" OWNER to "postgres";
 
CREATE TABLE "tsb"."HouseImportResultPremise" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid PRIMARY KEY , 
   "HouseImportTransportGUID" uuid NOT NULL , 
   "PremisesGUID" uuid , 
   "PremisesUniqueNumber" character varying(31) COLLATE pg_catalog."default" , 
   "UpdateDate" timestamp 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."HouseImportResultPremise" OWNER to "postgres";
 
CREATE TABLE "tsb"."HouseImportResultPremiseError" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid PRIMARY KEY , 
   "HouseImportPremiseTransportGUID" uuid NOT NULL , 
   "ErrorCode" character varying(32) COLLATE pg_catalog."default" NOT NULL , 
   "ErrorDescription" text COLLATE pg_catalog."default" NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."HouseImportResultPremiseError" OWNER to "postgres";
 
CREATE TABLE "tsb"."NotificationImportDeleteRequest" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid PRIMARY KEY , 
   "NotificationGUID" uuid NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."NotificationImportDeleteRequest" OWNER to "postgres";
 
CREATE TABLE "tsb"."NotificationImportRequest" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid PRIMARY KEY , 
   "NotificationGUID" uuid , 
   "Topic" character varying(200) COLLATE pg_catalog."default" NOT NULL , 
   "Content" character varying(2000) COLLATE pg_catalog."default" , 
   "IsImportant" bool NOT NULL , 
   "StartDate" timestamp , 
   "EndDate" timestamp 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."NotificationImportRequest" OWNER to "postgres";
 
CREATE TABLE "tsb"."NotificationImportRequestAccountDebt" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid PRIMARY KEY , 
   "NotificationImportTransportGUID" uuid NOT NULL , 
   "UnifiedAccountNumber" character varying(10) COLLATE pg_catalog."default" NOT NULL , 
   "TotalDebt" numeric(20,10) NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."NotificationImportRequestAccountDebt" OWNER to "postgres";
 
CREATE TABLE "tsb"."NotificationImportResult" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid PRIMARY KEY , 
   "NotificationGUID" uuid , 
   "UpdateDate" timestamp 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."NotificationImportResult" OWNER to "postgres";
 
CREATE TABLE "tsb"."NotificationImportResultError" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid PRIMARY KEY , 
   "NotificationImportTransportGUID" uuid NOT NULL , 
   "ErrorCode" character varying(32) COLLATE pg_catalog."default" NOT NULL , 
   "ErrorDescription" text COLLATE pg_catalog."default" NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."NotificationImportResultError" OWNER to "postgres";
 
CREATE TABLE "tsb"."NsiExportRequest" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "TransportGUID" uuid PRIMARY KEY , 
   "RegistryNumber" integer NOT NULL , 
   "ModifiedAfter" timestamp 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."NsiExportRequest" OWNER to "postgres";
 
CREATE TABLE "tsb"."NsiExportResult" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "TransportGUID" uuid PRIMARY KEY , 
   "RegistryNumber" integer NOT NULL , 
   "Code" character varying(20) COLLATE pg_catalog."default" NOT NULL , 
   "GUID" uuid NOT NULL , 
   "Modified" timestamp NOT NULL , 
   "IsActual" bool NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."NsiExportResult" OWNER to "postgres";
 
CREATE TABLE "tsb"."NsiExportResultField" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "TransportGUID" uuid PRIMARY KEY , 
   "NsiExportTransportGUID" uuid NOT NULL , 
   "Name" character varying(200) COLLATE pg_catalog."default" NOT NULL , 
   "Value" character varying(1024) COLLATE pg_catalog."default" NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."NsiExportResultField" OWNER to "postgres";
 
CREATE TABLE "tsb"."OrderImportCancellationRequest" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid PRIMARY KEY , 
   "OrderID" character varying(32) COLLATE pg_catalog."default" NOT NULL , 
   "CancellationDate" timestamp NOT NULL , 
   "Comment" character varying(210) COLLATE pg_catalog."default" 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."OrderImportCancellationRequest" OWNER to "postgres";
 
CREATE TABLE "tsb"."OrderImportRequest" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid PRIMARY KEY , 
   "OrderDate" timestamp NOT NULL , 
   "AmountRub" numeric(20,10) NOT NULL , 
   "Year" smallint , 
   "Month" smallint , 
   "ServiceID" character varying(13) COLLATE pg_catalog."default" , 
   "PaymentDocumentID" character varying(18) COLLATE pg_catalog."default" 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."OrderImportRequest" OWNER to "postgres";
 
CREATE TABLE "tsb"."OrderImportResult" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid PRIMARY KEY , 
   "OrderGUID" uuid , 
   "OrderID" character varying(32) COLLATE pg_catalog."default" , 
   "UpdateDate" timestamp 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."OrderImportResult" OWNER to "postgres";
 
CREATE TABLE "tsb"."OrderImportResultError" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid PRIMARY KEY , 
   "OrderImportTransportGUID" uuid NOT NULL , 
   "ErrorCode" character varying(32) COLLATE pg_catalog."default" NOT NULL , 
   "ErrorDescription" text COLLATE pg_catalog."default" NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."OrderImportResultError" OWNER to "postgres";
 
CREATE TABLE "tsb"."OrganizationExportRequest" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "TransportGUID" uuid PRIMARY KEY , 
   "LastEditingDateFrom" timestamp 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."OrganizationExportRequest" OWNER to "postgres";
 
CREATE TABLE "tsb"."OrganizationExportRequestData" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "TransportGUID" uuid PRIMARY KEY , 
   "OrganizationExportTransportGUID" uuid NOT NULL , 
   "orgType" smallint NOT NULL , 
   "OrgGUID" uuid , 
   "OrgVersionGUID" uuid , 
   "OGRN" character varying(15) COLLATE pg_catalog."default" , 
   "KPP" character varying(9) COLLATE pg_catalog."default" , 
   "OrgPPAGUID" uuid , 
   "IsRegistered" bool 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."OrganizationExportRequestData" OWNER to "postgres";
 
CREATE TABLE "tsb"."OrganizationExportResult" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "TransportGUID" uuid PRIMARY KEY , 
   "orgType" smallint NOT NULL , 
   "OrgGUID" uuid NOT NULL , 
   "OrgVersionGUID" uuid NOT NULL , 
   "RegistryOrganizationStatus" character varying(1) COLLATE pg_catalog."default" , 
   "OrgPPAGUID" uuid , 
   "IsRegistered" bool , 
   "IsVersionActual" bool NOT NULL , 
   "VersionLastEditingDate" timestamp NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."OrganizationExportResult" OWNER to "postgres";
 
CREATE TABLE "tsb"."OrganizationExportResultEntp" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "TransportGUID" uuid PRIMARY KEY , 
   "FirstName" character varying(255) COLLATE pg_catalog."default" NOT NULL , 
   "Surname" character varying(255) COLLATE pg_catalog."default" NOT NULL , 
   "Patronymic" character varying(255) COLLATE pg_catalog."default" , 
   "Sex" character varying(1) COLLATE pg_catalog."default" , 
   "OGRN" character varying(15) COLLATE pg_catalog."default" NOT NULL , 
   "INN" character varying(12) COLLATE pg_catalog."default" , 
   "StateRegistrationDate" timestamp 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."OrganizationExportResultEntp" OWNER to "postgres";
 
CREATE TABLE "tsb"."OrganizationExportResultLegal" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "TransportGUID" uuid PRIMARY KEY , 
   "FullName" character varying(4000) COLLATE pg_catalog."default" NOT NULL , 
   "ShortName" character varying(500) COLLATE pg_catalog."default" , 
   "CommercialName" character varying(255) COLLATE pg_catalog."default" , 
   "OGRN" character varying(13) COLLATE pg_catalog."default" NOT NULL , 
   "INN" character varying(10) COLLATE pg_catalog."default" , 
   "KPP" character varying(9) COLLATE pg_catalog."default" , 
   "OKOPF" character varying(5) COLLATE pg_catalog."default" , 
   "StateRegistrationDate" timestamp , 
   "ActivityEndDate" timestamp , 
   "Address" text COLLATE pg_catalog."default" , 
   "FIASHouseGuid" uuid 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."OrganizationExportResultLegal" OWNER to "postgres";
 
CREATE TABLE "tsb"."OrganizationExportResultRole" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "TransportGUID" uuid PRIMARY KEY , 
   "OrganizationExportTransportGUID" uuid NOT NULL , 
   "OrganizationRoleCode" character varying(20) COLLATE pg_catalog."default" NOT NULL , 
   "OrganizationRoleGUID" uuid NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."OrganizationExportResultRole" OWNER to "postgres";
 
CREATE TABLE "tsb"."PaymentExportRequest" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "TransportGUID" uuid PRIMARY KEY , 
   "Month" smallint , 
   "Year" smallint , 
   "FIASHouseGuid" uuid 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."PaymentExportRequest" OWNER to "postgres";
 
CREATE TABLE "tsb"."PaymentExportRequestAccount" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid PRIMARY KEY , 
   "PaymentExportTransportGUID" uuid NOT NULL , 
   "AccountGUID" uuid , 
   "AccountNumber" character varying(30) COLLATE pg_catalog."default" , 
   "UnifiedAccountNumber" character varying(10) COLLATE pg_catalog."default" , 
   "ServiceID" character varying(13) COLLATE pg_catalog."default" 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."PaymentExportRequestAccount" OWNER to "postgres";
 
CREATE TABLE "tsb"."PaymentExportRequestDocument" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid PRIMARY KEY , 
   "PaymentExportTransportGUID" uuid NOT NULL , 
   "PaymentDocumentID" character varying(18) COLLATE pg_catalog."default" , 
   "PaymentDocumentNumber" character varying(30) COLLATE pg_catalog."default" 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."PaymentExportRequestDocument" OWNER to "postgres";
 
CREATE TABLE "tsb"."PaymentExportResult" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "TransportGUID" uuid PRIMARY KEY , 
   "PaymentDocumentID" character varying(18) COLLATE pg_catalog."default" NOT NULL , 
   "PaymentDocumentNumber" character varying(30) COLLATE pg_catalog."default" , 
   "AccountGUID" uuid NOT NULL , 
   "Withdraw" bool NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."PaymentExportResult" OWNER to "postgres";
 
CREATE TABLE "tsb"."PaymentImportRequest" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid PRIMARY KEY , 
   "PaymentDocumentID" character varying(18) COLLATE pg_catalog."default" , 
   "PaymentDocumentNumber" character varying(30) COLLATE pg_catalog."default" , 
   "AccountGUID" uuid NOT NULL , 
   "Month" smallint NOT NULL , 
   "Year" smallint NOT NULL , 
   "ConfirmAmountsCorrect" bool , 
   "BankBIK" character varying(9) COLLATE pg_catalog."default" NOT NULL , 
   "OperatingAccountNumber" character varying(20) COLLATE pg_catalog."default" NOT NULL , 
   "DebtPreviousPeriods" numeric(20,10) , 
   "AdvanceBllingPeriod" numeric(20,10) , 
   "TotalPiecemealPaymentSum" numeric(20,10) , 
   "PaymentsTaken" smallint , 
   "AdditionalInformation" character varying(1000) COLLATE pg_catalog."default" , 
   "TotalPayableByPD" numeric(20,10) , 
   "TotalPayableByChargeInfo" numeric(20,10) , 
   "TotalPayableByPDWithDebtAndAdvance" numeric(20,10) , 
   "TotalByPenaltiesAndCourtCosts" numeric(20,10) , 
   "PaidCash" numeric(20,10) , 
   "DateOfLastReceivedPayment" timestamp , 
   "LimitIndex" numeric(20,10) , 
   "SubsidiesCompensationSocialSupport" numeric(20,10) 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."PaymentImportRequest" OWNER to "postgres";
 
CREATE TABLE "tsb"."PaymentImportRequestChargesMunicipalService" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid PRIMARY KEY , 
   "PaymentImportTransportGUID" uuid NOT NULL , 
   "MainMunicipalServiceCode" character varying(20) COLLATE pg_catalog."default" NOT NULL , 
   "MainMunicipalServiceGUID" uuid NOT NULL , 
   "Rate" numeric(20,10) NOT NULL , 
   "TotalPayable" numeric(20,10) NOT NULL , 
   "AccountingPeriodTotal" numeric(20,10) , 
   "CalcExplanation" character varying(4000) COLLATE pg_catalog."default" , 
   "MoneyRecalculation" numeric(20,10) , 
   "MoneyDiscount" numeric(20,10) , 
   "VolumeI" numeric(20,10) , 
   "VolumeO" numeric(20,10) , 
   "DeterminingMethodI" character varying(1) COLLATE pg_catalog."default" , 
   "DeterminingMethodO" character varying(1) COLLATE pg_catalog."default" , 
   "RecalculationReason" character varying(500) COLLATE pg_catalog."default" , 
   "Sum" numeric(20,10) , 
   "IndividualConsumptionPayable" numeric(20,10) , 
   "CommunalConsumptionPayable" numeric(20,10) , 
   "MultiplyingFactorRatio" numeric(20,10) , 
   "MultiplyingFactorAmount" numeric(20,10) , 
   "AmountI" numeric(20,10) , 
   "AmountO" numeric(20,10) , 
   "DebtPreviousPeriodsOrAdvanceBillingPeriod" numeric(20,10) , 
   "Penalties" numeric(20,10) , 
   "StateFees" numeric(20,10) , 
   "CourtCosts" numeric(20,10) , 
   "TotalPayableOverall" numeric(20,10) 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."PaymentImportRequestChargesMunicipalService" OWNER to "postgres";
 
CREATE TABLE "tsb"."PaymentImportRequestChargesMunicipalServiceNorm" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid PRIMARY KEY , 
   "IndividualConsumptionCurrentValue" numeric(20,10) , 
   "HouseOverallNeedsCurrentValue" numeric(20,10) , 
   "HouseTotalIndividualConsumption" numeric(20,10) , 
   "HouseTotalHouseOverallNeeds" numeric(20,10) , 
   "HouseOverallNeedsNorm" numeric(20,10) , 
   "IndividualConsumptionNorm" numeric(20,10) 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."PaymentImportRequestChargesMunicipalServiceNorm" OWNER to "postgres";
 
CREATE TABLE "tsb"."PaymentImportRequestDebtMunicipalService" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid PRIMARY KEY , 
   "PaymentImportTransportGUID" uuid NOT NULL , 
   "MainMunicipalServiceCode" character varying(20) COLLATE pg_catalog."default" NOT NULL , 
   "MainMunicipalServiceGUID" uuid NOT NULL , 
   "Month" smallint NOT NULL , 
   "Year" smallint NOT NULL , 
   "TotalPayable" numeric(20,10) NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."PaymentImportRequestDebtMunicipalService" OWNER to "postgres";
 
CREATE TABLE "tsb"."PaymentImportRequestPenaltyAndCourtCost" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid PRIMARY KEY , 
   "PaymentImportTransportGUID" uuid NOT NULL , 
   "PenaltyAndCourtCostCode" character varying(20) COLLATE pg_catalog."default" NOT NULL , 
   "PenaltyAndCourtCostGUID" uuid NOT NULL , 
   "Cause" character varying(1000) COLLATE pg_catalog."default" NOT NULL , 
   "TotalPayable" numeric(20,10) NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."PaymentImportRequestPenaltyAndCourtCost" OWNER to "postgres";
 
CREATE TABLE "tsb"."PaymentImportResult" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid PRIMARY KEY , 
   "PaymentDocumentGUID" uuid , 
   "PaymentDocumentID" character varying(18) COLLATE pg_catalog."default" , 
   "UpdateDate" timestamp 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."PaymentImportResult" OWNER to "postgres";
 
CREATE TABLE "tsb"."PaymentImportResultError" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid PRIMARY KEY , 
   "PaymentImportTransportGUID" uuid NOT NULL , 
   "ErrorCode" character varying(32) COLLATE pg_catalog."default" NOT NULL , 
   "ErrorDescription" text COLLATE pg_catalog."default" NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."PaymentImportResultError" OWNER to "postgres";
 
CREATE TABLE "tsb"."PaymentImportWithdrawRequest" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid PRIMARY KEY , 
   "PaymentDocumentID" character varying(18) COLLATE pg_catalog."default" NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."PaymentImportWithdrawRequest" OWNER to "postgres";
 
CREATE TABLE "tsb"."SettlementImportAnnulmentRequest" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid PRIMARY KEY , 
   "SettlementGUID" uuid NOT NULL , 
   "ReasonOfAnnulment" character varying(2000) COLLATE pg_catalog."default" NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."SettlementImportAnnulmentRequest" OWNER to "postgres";
 
CREATE TABLE "tsb"."SettlementImportRequest" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid PRIMARY KEY , 
   "SettlementGUID" uuid , 
   "ContractGUID" uuid NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."SettlementImportRequest" OWNER to "postgres";
 
CREATE TABLE "tsb"."SettlementImportRequestPeriod" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid PRIMARY KEY , 
   "SettlementImportTransportGUID" uuid NOT NULL , 
   "Month" smallint NOT NULL , 
   "Year" smallint NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."SettlementImportRequestPeriod" OWNER to "postgres";
 
CREATE TABLE "tsb"."SettlementImportRequestPeriodAnnulment" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid PRIMARY KEY , 
   "ReasonOfAnnulment" character varying(2000) COLLATE pg_catalog."default" NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."SettlementImportRequestPeriodAnnulment" OWNER to "postgres";
 
CREATE TABLE "tsb"."SettlementImportRequestPeriodInfo" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid PRIMARY KEY , 
   "Credted" numeric(20,10) NOT NULL , 
   "Receipt" numeric(20,10) NOT NULL , 
   "Debts" numeric(20,10) NOT NULL , 
   "Overpayment" numeric(20,10) NOT NULL , 
   "Paid" numeric(20,10) 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."SettlementImportRequestPeriodInfo" OWNER to "postgres";
 
CREATE TABLE "tsb"."SettlementImportResult" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid PRIMARY KEY , 
   "SettlementGUID" uuid , 
   "UpdateDate" timestamp 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."SettlementImportResult" OWNER to "postgres";
 
CREATE TABLE "tsb"."SettlementImportResultError" 
( 
   "uniqueId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" , 
   "TransportGUID" uuid PRIMARY KEY , 
   "SettlementImportTransportGUID" uuid NOT NULL , 
   "ErrorCode" character varying(32) COLLATE pg_catalog."default" NOT NULL , 
   "ErrorDescription" text COLLATE pg_catalog."default" NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."SettlementImportResultError" OWNER to "postgres";
 
CREATE TABLE "tsb"."SysOperation" 
( 
   "OperationId" integer PRIMARY KEY , 
   "OperationName" character varying(128) COLLATE pg_catalog."default" NOT NULL , 
   "Name" character varying(1024) COLLATE pg_catalog."default" NOT NULL , 
   "PacketSize" integer NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."SysOperation" OWNER to "postgres";
 
CREATE TABLE "tsb"."SysParams" 
( 
   "Id" integer PRIMARY KEY , 
   "VersionNumber" character varying(32) COLLATE pg_catalog."default" NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."SysParams" OWNER to "postgres";
 
CREATE TABLE "tsb"."SysRegistry" 
( 
   "RegistryId" integer PRIMARY KEY , 
   "RegistryName" character varying(128) COLLATE pg_catalog."default" NOT NULL , 
   "Name" character varying(1024) COLLATE pg_catalog."default" NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."SysRegistry" OWNER to "postgres";
 
CREATE TABLE "tsb"."SysTransaction" 
( 
   "TransactionGUID" uuid PRIMARY KEY , 
   "ListGUID" uuid , 
   "ClientId" character varying(32) COLLATE pg_catalog."default" NOT NULL , 
   "OperationId" integer NOT NULL , 
   "StartDate" timestamp NOT NULL , 
   "EndDate" timestamp , 
   "StatusId" integer NOT NULL , 
   "LastExecutionDate" timestamp , 
   "NextExecutionDate" timestamp , 
   "ResultId" integer , 
   "ErrorCode" character varying(32) COLLATE pg_catalog."default" , 
   "ErrorDescription" character varying(4000) COLLATE pg_catalog."default" 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."SysTransaction" OWNER to "postgres";
 
CREATE TABLE "tsb"."SysTransactionLog" 
( 
   "TransactionLogId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "LogDate" timestamp NOT NULL , 
   "LogData" character varying(1024) COLLATE pg_catalog."default" , 
   "ErrorCode" character varying(32) COLLATE pg_catalog."default" , 
   "ErrorDescription" text COLLATE pg_catalog."default" , 
   "ErrorStackTrace" text COLLATE pg_catalog."default" 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."SysTransactionLog" OWNER to "postgres";
 
CREATE TABLE "tsb"."SysTransactionObject" 
( 
   "TransactionObjectId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" NOT NULL , 
   "comment" text COLLATE pg_catalog."default" , 
   "operation" integer NOT NULL , 
   "group" integer , 
   "param" text COLLATE pg_catalog."default" 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."SysTransactionObject" OWNER to "postgres";
 
CREATE TABLE "tsb"."SysTransactionObjectError" 
( 
   "TransactionObjectErrorId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "objectId" character varying(32) COLLATE pg_catalog."default" NOT NULL , 
   "errorCode" character varying(32) COLLATE pg_catalog."default" NOT NULL , 
   "errorDescription" text COLLATE pg_catalog."default" 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."SysTransactionObjectError" OWNER to "postgres";
 
CREATE TABLE "tsb"."SysTransactionParam" 
( 
   "TransactionParamId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "TransactionGUID" uuid NOT NULL , 
   "ParamName" character varying(128) COLLATE pg_catalog."default" NOT NULL , 
   "ParamValue" character varying(1024) COLLATE pg_catalog."default" 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."SysTransactionParam" OWNER to "postgres";
 
CREATE TABLE "tsb"."SysTransactionState2" 
( 
   "TransactionStateId" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
   "StateGUID" uuid NOT NULL , 
   "AsyncStateGUID" uuid , 
   "TransactionGUID" uuid NOT NULL , 
   "OperationId" integer NOT NULL , 
   "StateTypeId" smallint NOT NULL , 
   "StateDate" timestamp NOT NULL , 
   "StateData" text COLLATE pg_catalog."default" 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."SysTransactionState2" OWNER to "postgres";
 
CREATE TABLE "tsb"."SysTransactionStateType" 
( 
   "TransactionStateTypeId" smallint PRIMARY KEY , 
   "TransactionStateTypeName" character varying(128) COLLATE pg_catalog."default" NOT NULL 
) TABLESPACE "pg_default"; 
 ALTER TABLE "tsb"."SysTransactionStateType" OWNER to "postgres";

