// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Hcs.Model
{
    public partial class AccountImportRequest : ITransactionObjectEntity
    {
        public AccountImportRequest()
        {
            AccountImportRequestPercentPremises = new HashSet<AccountImportRequestPercentPremise>();
            AccountImportRequestReasons = new HashSet<AccountImportRequestReason>();
        }

        public long uniqueId { get; set; }
        public Guid TransactionGUID { get; set; }
        [StringLength(32)]
        public string objectId { get; set; }
        [Key]
        public Guid TransportGUID { get; set; }
        public Guid? AccountGUID { get; set; }
        [Required]
        [StringLength(30)]
        public string AccountNumber { get; set; }
        public bool IsRSOAccount { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreationDate { get; set; }
        public short? LivingPersonsNumber { get; set; }
        [Column(TypeName = "decimal(25, 4)")]
        public decimal? TotalSquare { get; set; }
        [Column(TypeName = "decimal(25, 4)")]
        public decimal? ResidentialSquare { get; set; }
        [Column(TypeName = "decimal(25, 4)")]
        public decimal? HeatedArea { get; set; }
        [StringLength(20)]
        public string AccountCloseReasonCode { get; set; }
        public Guid? AccountCloseReasonGUID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CloseDate { get; set; }
        [StringLength(250)]
        public string CloseDescription { get; set; }
        public bool? IsRenter { get; set; }
        public bool? IsAccountsDivided { get; set; }
        public Guid? OrgVersionGUID { get; set; }

        [InverseProperty("TransportGU")]
        public virtual AccountImportRequestPayer AccountImportRequestPayer { get; set; }
        [InverseProperty(nameof(AccountImportRequestPercentPremise.AccountImportTransportGU))]
        public virtual ICollection<AccountImportRequestPercentPremise> AccountImportRequestPercentPremises { get; set; }
        [InverseProperty(nameof(AccountImportRequestReason.AccountImportTransportGU))]
        public virtual ICollection<AccountImportRequestReason> AccountImportRequestReasons { get; set; }
    }
}