// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Hcs.Model
{
    public partial class ContractImportRequestSubjectQualityIndicator : ITransactionObjectEntity
    {
        public long uniqueId { get; set; }
        public Guid TransactionGUID { get; set; }
        [StringLength(32)]
        public string objectId { get; set; }
        [Key]
        public Guid TransportGUID { get; set; }
        public Guid ContractImportSubjectTransportGUID { get; set; }
        public Guid? ContractImportObjectAddressTransportGUID { get; set; }
        [StringLength(20)]
        public string QualityIndicatorCode { get; set; }
        public Guid? QualityIndicatorGUID { get; set; }
        [Column(TypeName = "decimal(20, 6)")]
        public decimal? Number { get; set; }
        [Column(TypeName = "decimal(20, 6)")]
        public decimal? StartRange { get; set; }
        [Column(TypeName = "decimal(20, 6)")]
        public decimal? EndRange { get; set; }
        [StringLength(4)]
        public string OKEI { get; set; }
        public bool? Correspond { get; set; }
        [StringLength(1000)]
        public string IndicatorName { get; set; }

        [ForeignKey(nameof(ContractImportObjectAddressTransportGUID))]
        [InverseProperty(nameof(ContractImportRequestObjectAddress.ContractImportRequestSubjectQualityIndicators))]
        public virtual ContractImportRequestObjectAddress ContractImportObjectAddressTransportGU { get; set; }
        [ForeignKey(nameof(ContractImportSubjectTransportGUID))]
        [InverseProperty(nameof(ContractImportRequestSubject.ContractImportRequestSubjectQualityIndicators))]
        public virtual ContractImportRequestSubject ContractImportSubjectTransportGU { get; set; }
    }
}