// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Hcs.Model
{
    public partial class DeviceImportRequestValue : ITransactionObjectEntity
    {
        public long uniqueId { get; set; }
        public Guid TransactionGUID { get; set; }
        [StringLength(32)]
        public string objectId { get; set; }
        [Key]
        public Guid TransportGUID { get; set; }
        public Guid DeviceImportTransportGUID { get; set; }
        [Required]
        [StringLength(20)]
        public string MunicipalResourceCode { get; set; }
        public Guid MunicipalResourceGUID { get; set; }
        [Column(TypeName = "decimal(22, 7)")]
        public decimal ValueT1 { get; set; }
        [Column(TypeName = "decimal(22, 7)")]
        public decimal? ValueT2 { get; set; }
        [Column(TypeName = "decimal(22, 7)")]
        public decimal? ValueT3 { get; set; }
        [Column(TypeName = "decimal(14, 4)")]
        public decimal? TransformationRatio { get; set; }

        [ForeignKey(nameof(DeviceImportTransportGUID))]
        [InverseProperty(nameof(DeviceImportRequest.DeviceImportRequestValues))]
        public virtual DeviceImportRequest DeviceImportTransportGU { get; set; }
    }
}