// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Hcs.Model
{
    public partial class NotificationImportRequestAccountDebt : ITransactionObjectEntity
    {
        public long uniqueId { get; set; }
        public Guid TransactionGUID { get; set; }
        [StringLength(32)]
        public string objectId { get; set; }
        [Key]
        public Guid TransportGUID { get; set; }
        public Guid NotificationImportTransportGUID { get; set; }
        [Required]
        [StringLength(10)]
        public string UnifiedAccountNumber { get; set; }
        [Column(TypeName = "decimal(20, 2)")]
        public decimal TotalDebt { get; set; }

        [ForeignKey(nameof(NotificationImportTransportGUID))]
        [InverseProperty(nameof(NotificationImportRequest.NotificationImportRequestAccountDebts))]
        public virtual NotificationImportRequest NotificationImportTransportGU { get; set; }
    }
}