// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Hcs.Model
{
    public partial class NotificationImportRequest : ITransactionObjectEntity
    {
        public NotificationImportRequest()
        {
            NotificationImportRequestAccountDebts = new HashSet<NotificationImportRequestAccountDebt>();
        }

        public long uniqueId { get; set; }
        public Guid TransactionGUID { get; set; }
        [StringLength(32)]
        public string objectId { get; set; }
        [Key]
        public Guid TransportGUID { get; set; }
        public Guid? NotificationGUID { get; set; }
        [Required]
        [StringLength(200)]
        public string Topic { get; set; }
        [StringLength(2000)]
        public string Content { get; set; }
        public bool IsImportant { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? StartDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? EndDate { get; set; }

        [InverseProperty(nameof(NotificationImportRequestAccountDebt.NotificationImportTransportGU))]
        public virtual ICollection<NotificationImportRequestAccountDebt> NotificationImportRequestAccountDebts { get; set; }
    }
}