// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Hcs.Model
{
    public partial class OrganizationExportRequestData
    {
        public long uniqueId { get; set; }
        public Guid TransactionGUID { get; set; }
        [Key]
        public Guid TransportGUID { get; set; }
        public Guid OrganizationExportTransportGUID { get; set; }
        public byte orgType { get; set; }
        public Guid? OrgGUID { get; set; }
        public Guid? OrgVersionGUID { get; set; }
        [StringLength(15)]
        public string OGRN { get; set; }
        [StringLength(9)]
        public string KPP { get; set; }
        public Guid? OrgPPAGUID { get; set; }
        public bool? IsRegistered { get; set; }

        [ForeignKey(nameof(OrganizationExportTransportGUID))]
        [InverseProperty(nameof(OrganizationExportRequest.OrganizationExportRequestData))]
        public virtual OrganizationExportRequest OrganizationExportTransportGU { get; set; }
    }
}