// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Hcs.Model
{
    public partial class PaymentExportResult
    {
        public long uniqueId { get; set; }
        public Guid TransactionGUID { get; set; }
        [Key]
        public Guid TransportGUID { get; set; }
        [Required]
        [StringLength(18)]
        public string PaymentDocumentID { get; set; }
        [StringLength(30)]
        public string PaymentDocumentNumber { get; set; }
        public Guid AccountGUID { get; set; }
        public bool Withdraw { get; set; }
    }
}