// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Hcs.Model
{
    public partial class AccountImportRequestReason : ITransactionObjectEntity
    {
        public long uniqueId { get; set; }
        public Guid TransactionGUID { get; set; }
        [StringLength(32)]
        public string objectId { get; set; }
        [Key]
        public Guid TransportGUID { get; set; }
        public Guid AccountImportTransportGUID { get; set; }
        public Guid ContractGUID { get; set; }

        [ForeignKey(nameof(AccountImportTransportGUID))]
        [InverseProperty(nameof(AccountImportRequest.AccountImportRequestReasons))]
        public virtual AccountImportRequest AccountImportTransportGU { get; set; }
    }
}