// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Hcs.Model
{
    public partial class ContractImportRequestObjectServiceResource : ITransactionObjectEntity
    {
        public long uniqueId { get; set; }
        public Guid TransactionGUID { get; set; }
        [StringLength(32)]
        public string objectId { get; set; }
        [Key]
        public Guid TransportGUID { get; set; }
        public Guid ContractImportObjectAddressTransportGUID { get; set; }
        public Guid ContractImportSubjectTransportGUID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime StartSupplyDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? EndSupplyDate { get; set; }
        [StringLength(32)]
        public string OpenOrNot { get; set; }
        [StringLength(32)]
        public string CentralizedOrNot { get; set; }

        [ForeignKey(nameof(ContractImportObjectAddressTransportGUID))]
        [InverseProperty(nameof(ContractImportRequestObjectAddress.ContractImportRequestObjectServiceResources))]
        public virtual ContractImportRequestObjectAddress ContractImportObjectAddressTransportGU { get; set; }
        [ForeignKey(nameof(ContractImportSubjectTransportGUID))]
        [InverseProperty(nameof(ContractImportRequestSubject.ContractImportRequestObjectServiceResources))]
        public virtual ContractImportRequestSubject ContractImportSubjectTransportGU { get; set; }
    }
}