// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Hcs.Model
{
    public partial class ContractImportResultError : ITransactionObjectEntity
    {
        public long uniqueId { get; set; }
        public Guid TransactionGUID { get; set; }
        [StringLength(32)]
        public string objectId { get; set; }
        [Key]
        public Guid TransportGUID { get; set; }
        public Guid ContractImportTransportGUID { get; set; }
        public Guid? ContractImportObjectAddressTransportGUID { get; set; }
        public Guid? ContractImportSubjectTransportGUID { get; set; }
        [Required]
        [StringLength(32)]
        public string ErrorCode { get; set; }
        [Required]
        public string ErrorDescription { get; set; }

        [ForeignKey(nameof(ContractImportTransportGUID))]
        [InverseProperty(nameof(ContractImportResult.ContractImportResultErrors))]
        public virtual ContractImportResult ContractImportTransportGU { get; set; }
    }
}