// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Hcs.Model
{
    public partial class DeviceImportReplaceRequest : ITransactionObjectEntity
    {
        public DeviceImportReplaceRequest()
        {
            DeviceImportReplaceRequestValues = new HashSet<DeviceImportReplaceRequestValue>();
        }

        public long uniqueId { get; set; }
        public Guid TransactionGUID { get; set; }
        [StringLength(32)]
        public string objectId { get; set; }
        [Key]
        public Guid TransportGUID { get; set; }
        public Guid DeviceVersionGUID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime VerificationDate { get; set; }
        public bool? PlannedVerification { get; set; }
        [StringLength(20)]
        public string DeviceFaultReasonCode { get; set; }
        public Guid? DeviceFaultReasonGUID { get; set; }
        public Guid ReplacingDeviceVersionGUID { get; set; }

        [InverseProperty(nameof(DeviceImportReplaceRequestValue.DeviceImportReplaceTransportGU))]
        public virtual ICollection<DeviceImportReplaceRequestValue> DeviceImportReplaceRequestValues { get; set; }
    }
}