// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Hcs.Model
{
    public partial class DeviceImportArchiveRequest : ITransactionObjectEntity
    {
        public long uniqueId { get; set; }
        public Guid TransactionGUID { get; set; }
        [StringLength(32)]
        public string objectId { get; set; }
        [Key]
        public Guid TransportGUID { get; set; }
        public Guid DeviceVersionGUID { get; set; }
        [Required]
        [StringLength(20)]
        public string DeviceArchivingReasonCode { get; set; }
        public Guid DeviceArchivingReasonGUID { get; set; }
    }
}