// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Hcs.Model
{
    public partial class DeviceValueExportRequest
    {
        public DeviceValueExportRequest()
        {
            DeviceValueExportRequestDeviceTypes = new HashSet<DeviceValueExportRequestDeviceType>();
            DeviceValueExportRequestDevices = new HashSet<DeviceValueExportRequestDevice>();
            DeviceValueExportRequestMunicipalResources = new HashSet<DeviceValueExportRequestMunicipalResource>();
        }

        [Key]
        public Guid TransportGUID { get; set; }
        public Guid FIASHouseGuid { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CommissioningDateFrom { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CommissioningDateTo { get; set; }
        public bool? SearchArchived { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ArchiveDateFrom { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ArchiveDateTo { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? InputDateFrom { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? InputDateTo { get; set; }
        public bool? ExcludePersonAsDataSource { get; set; }
        public bool? ExcludeCurrentOrgAsDataSource { get; set; }
        public bool? ExcludeOtherOrgAsDataSource { get; set; }
        public long uniqueId { get; set; }
        public Guid TransactionGUID { get; set; }

        [InverseProperty(nameof(DeviceValueExportRequestDeviceType.DeviceValueExportTransportGU))]
        public virtual ICollection<DeviceValueExportRequestDeviceType> DeviceValueExportRequestDeviceTypes { get; set; }
        [InverseProperty(nameof(DeviceValueExportRequestDevice.DeviceValueExportTransportGU))]
        public virtual ICollection<DeviceValueExportRequestDevice> DeviceValueExportRequestDevices { get; set; }
        [InverseProperty(nameof(DeviceValueExportRequestMunicipalResource.DeviceValueExportTransportGU))]
        public virtual ICollection<DeviceValueExportRequestMunicipalResource> DeviceValueExportRequestMunicipalResources { get; set; }
    }
}