// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Hcs.Model
{
    public partial class OrderImportRequest : ITransactionObjectEntity
    {
        public long uniqueId { get; set; }
        public Guid TransactionGUID { get; set; }
        [StringLength(32)]
        public string objectId { get; set; }
        [Key]
        public Guid TransportGUID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime OrderDate { get; set; }
        [Column(TypeName = "decimal(13, 2)")]
        public decimal AmountRub { get; set; }
        public short? Year { get; set; }
        public byte? Month { get; set; }
        [StringLength(13)]
        public string ServiceID { get; set; }
        [StringLength(18)]
        public string PaymentDocumentID { get; set; }
    }
}