// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Hcs.Model
{
    public partial class PaymentImportRequestChargesMunicipalService : ITransactionObjectEntity
    {
        public long uniqueId { get; set; }
        public Guid TransactionGUID { get; set; }
        [StringLength(32)]
        public string objectId { get; set; }
        [Key]
        public Guid TransportGUID { get; set; }
        public Guid PaymentImportTransportGUID { get; set; }
        [Required]
        [StringLength(20)]
        public string MainMunicipalServiceCode { get; set; }
        public Guid MainMunicipalServiceGUID { get; set; }
        [Column(TypeName = "decimal(14, 6)")]
        public decimal Rate { get; set; }
        [Column(TypeName = "decimal(13, 2)")]
        public decimal TotalPayable { get; set; }
        [Column(TypeName = "decimal(13, 2)")]
        public decimal? AccountingPeriodTotal { get; set; }
        [StringLength(4000)]
        public string CalcExplanation { get; set; }
        [Column(TypeName = "decimal(13, 2)")]
        public decimal? MoneyRecalculation { get; set; }
        [Column(TypeName = "decimal(13, 2)")]
        public decimal? MoneyDiscount { get; set; }
        [Column(TypeName = "decimal(14, 6)")]
        public decimal? VolumeI { get; set; }
        [Column(TypeName = "decimal(14, 6)")]
        public decimal? VolumeO { get; set; }
        [StringLength(1)]
        public string DeterminingMethodI { get; set; }
        [StringLength(1)]
        public string DeterminingMethodO { get; set; }
        [StringLength(500)]
        public string RecalculationReason { get; set; }
        [Column(TypeName = "decimal(12, 2)")]
        public decimal? Sum { get; set; }
        [Column(TypeName = "decimal(13, 2)")]
        public decimal? IndividualConsumptionPayable { get; set; }
        [Column(TypeName = "decimal(13, 2)")]
        public decimal? CommunalConsumptionPayable { get; set; }
        [Column(TypeName = "decimal(5, 2)")]
        public decimal? MultiplyingFactorRatio { get; set; }
        [Column(TypeName = "decimal(13, 2)")]
        public decimal? MultiplyingFactorAmount { get; set; }
        [Column(TypeName = "decimal(13, 2)")]
        public decimal? AmountI { get; set; }
        [Column(TypeName = "decimal(13, 2)")]
        public decimal? AmountO { get; set; }
        [Column(TypeName = "decimal(13, 2)")]
        public decimal? DebtPreviousPeriodsOrAdvanceBillingPeriod { get; set; }
        [Column(TypeName = "decimal(13, 2)")]
        public decimal? Penalties { get; set; }
        [Column(TypeName = "decimal(13, 2)")]
        public decimal? StateFees { get; set; }
        [Column(TypeName = "decimal(13, 2)")]
        public decimal? CourtCosts { get; set; }
        [Column(TypeName = "decimal(13, 2)")]
        public decimal? TotalPayableOverall { get; set; }

        [ForeignKey(nameof(PaymentImportTransportGUID))]
        [InverseProperty(nameof(PaymentImportRequest.PaymentImportRequestChargesMunicipalServices))]
        public virtual PaymentImportRequest PaymentImportTransportGU { get; set; }
        [InverseProperty("TransportGU")]
        public virtual PaymentImportRequestChargesMunicipalServiceNorm PaymentImportRequestChargesMunicipalServiceNorm { get; set; }
    }
}