// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Hcs.Model
{
    public partial class PaymentImportRequest : ITransactionObjectEntity
    {
        public PaymentImportRequest()
        {
            PaymentImportRequestChargesMunicipalServices = new HashSet<PaymentImportRequestChargesMunicipalService>();
            PaymentImportRequestDebtMunicipalServices = new HashSet<PaymentImportRequestDebtMunicipalService>();
            PaymentImportRequestPenaltyAndCourtCosts = new HashSet<PaymentImportRequestPenaltyAndCourtCost>();
        }

        public long uniqueId { get; set; }
        public Guid TransactionGUID { get; set; }
        [StringLength(32)]
        public string objectId { get; set; }
        [Key]
        public Guid TransportGUID { get; set; }
        [StringLength(18)]
        public string PaymentDocumentID { get; set; }
        [StringLength(30)]
        public string PaymentDocumentNumber { get; set; }
        public Guid AccountGUID { get; set; }
        public byte Month { get; set; }
        public short Year { get; set; }
        public bool? ConfirmAmountsCorrect { get; set; }
        [Required]
        [StringLength(9)]
        public string BankBIK { get; set; }
        [Required]
        [StringLength(20)]
        public string OperatingAccountNumber { get; set; }
        [Column(TypeName = "decimal(10, 2)")]
        public decimal? DebtPreviousPeriods { get; set; }
        [Column(TypeName = "decimal(10, 2)")]
        public decimal? AdvanceBllingPeriod { get; set; }
        [Column(TypeName = "decimal(13, 2)")]
        public decimal? TotalPiecemealPaymentSum { get; set; }
        public byte? PaymentsTaken { get; set; }
        [StringLength(1000)]
        public string AdditionalInformation { get; set; }
        [Column(TypeName = "decimal(13, 2)")]
        public decimal? TotalPayableByPD { get; set; }
        [Column(TypeName = "decimal(13, 2)")]
        public decimal? TotalPayableByChargeInfo { get; set; }
        [Column(TypeName = "decimal(13, 2)")]
        public decimal? TotalPayableByPDWithDebtAndAdvance { get; set; }
        [Column(TypeName = "decimal(13, 2)")]
        public decimal? TotalByPenaltiesAndCourtCosts { get; set; }
        [Column(TypeName = "decimal(13, 2)")]
        public decimal? PaidCash { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateOfLastReceivedPayment { get; set; }
        [Column(TypeName = "decimal(5, 2)")]
        public decimal? LimitIndex { get; set; }
        [Column(TypeName = "decimal(10, 2)")]
        public decimal? SubsidiesCompensationSocialSupport { get; set; }

        [InverseProperty(nameof(PaymentImportRequestChargesMunicipalService.PaymentImportTransportGU))]
        public virtual ICollection<PaymentImportRequestChargesMunicipalService> PaymentImportRequestChargesMunicipalServices { get; set; }
        [InverseProperty(nameof(PaymentImportRequestDebtMunicipalService.PaymentImportTransportGU))]
        public virtual ICollection<PaymentImportRequestDebtMunicipalService> PaymentImportRequestDebtMunicipalServices { get; set; }
        [InverseProperty(nameof(PaymentImportRequestPenaltyAndCourtCost.PaymentImportTransportGU))]
        public virtual ICollection<PaymentImportRequestPenaltyAndCourtCost> PaymentImportRequestPenaltyAndCourtCosts { get; set; }
    }
}