// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Hcs.Model
{
    public partial class SettlementImportRequestPeriod : ITransactionObjectEntity
    {
        public long uniqueId { get; set; }
        public Guid TransactionGUID { get; set; }
        [StringLength(32)]
        public string objectId { get; set; }
        [Key]
        public Guid TransportGUID { get; set; }
        public Guid SettlementImportTransportGUID { get; set; }
        public byte Month { get; set; }
        public short Year { get; set; }

        [ForeignKey(nameof(SettlementImportTransportGUID))]
        [InverseProperty(nameof(SettlementImportRequest.SettlementImportRequestPeriods))]
        public virtual SettlementImportRequest SettlementImportTransportGU { get; set; }
        [InverseProperty("TransportGU")]
        public virtual SettlementImportRequestPeriodAnnulment SettlementImportRequestPeriodAnnulment { get; set; }
        [InverseProperty("TransportGU")]
        public virtual SettlementImportRequestPeriodInfo SettlementImportRequestPeriodInfo { get; set; }
    }
}