//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Core.Context
{
    using Microsoft.EntityFrameworkCore;
    using Server.Core.Model;
    
    public partial class EntityContext : DbContext
    {
        public virtual DbSet<Partners> Partners { get; set; }//;
        public virtual DbSet<payerlive> payerlive { get; set; }//;


        private void creatNavigations(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<payerlive>()
                .HasOne(u => u.Partners2)
                .WithMany(t => t.payerlive2)
                .HasForeignKey(t => t.reciever_id)
                ;

            modelBuilder.Entity<payerlive>()
                .HasOne(u => u.Partners3)
                .WithMany(t => t.payerlive3)
                .HasForeignKey(t => t.payer_id)
                ;

        }
    }
}
