//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Core.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class type_street : IEntityObject
    {
        #region Columns
        long IEntityObject.Id { get { return tstreet_id; } }//;
        public int Adr { get; set; }//;
        [KeyAttribute()]
        public int tstreet_id { get; set; }//;
        public string tstreet_name { get; set; }//;
        public System.Nullable<System.DateTime> ver_date { get; set; }//;
        public System.Nullable<short> ver_u_id { get; set; }//;
        public string tstreet_sname { get; set; }//;
        public string full_name { get; set; }//;
        #endregion
        #region Navigation - children
        // 
        // FK_type_street_street__tstreet_id_PK_type_street   [street.tstreet_id]
        public virtual ICollection<street> street { get; set; }//;
        #endregion
        #region Constructor
        public type_street()
        {
            this.street = new HashSet<street>();
        }
        #endregion
    }
}
